### ISSUE TITLE
Newest Version No Longer Works

### ISSUE THREAD

**Issue by atom0s** [shanalikhan/code-settings-sync#447] opened 2017-11-15 23:17 UTC
**Visual Studio Code Version :** 1.18.0
**Code Settings Sync Version :** 2.8.5
**Operating System :** Windows 8.1 / Windows 10 
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** N/A

At this time, the newest version of code-settings-sync no longer works for me. I have two systems I sync between and out of no where attempting to download on one of the machines stated my Gist/Github token was invalid and opened the Gist token generation page. I deleted the entire Gist holding my settings, deleted the old API token, and generated a new one.

On both machines, I reset the sync settings completely via > Sync: Reset Extension Settings. 
On one machine I did the normal steps to upload the settings, this worked fine.
On the second machine, I did the normal steps to download the settings, and it refuses to work. It will error that the Gist id is invalid. It will pop up the Gist API key page afterward. It also errors in the console the same error as this issue: #444

**Comment by shanalikhan** [comment] 2017-11-16 05:58
Duplicate of #144

**Comment by shanalikhan** [comment] 2017-11-16 05:59
Yes you are right, i will fix this bug in day or two.

**Closed by shanalikhan** 2017-11-16 05:59 UTC

**Comment by atom0s** [comment] 2017-11-20 21:17
Thanks, newest version is working again.
