### ISSUE TITLE
--user-data-dir and --extensions-dir command line option is not accomodated

### ISSUE THREAD

**Issue by jwstevensii** [shanalikhan/code-settings-sync#411] opened 2017-10-10 13:05 UTC
**Visual Studio Code Version : 1.70.0
**Code Settings Sync Version : 2.8.3
**Operating System : Windows 10
**Occurs On:** Download
**Proxy Enabled: No
**GIst Id: 2ff3a445e8abd98ec3037df1fa7d0200

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

Sync will not install extensions when **--extensions-dir** command line option is used (see https://code.visualstudio.com/docs/editor/command-line).

**Comment by shanalikhan** [comment] 2017-10-11 09:45
Thanks, Will work on it

**Comment by shanalikhan** [comment] 2017-11-04 07:51
Pending for 
https://github.com/Microsoft/vscode/issues/2741

**Comment by shanalikhan** [comment] 2018-02-04 22:09
Duplicate of #331

**Comment by shanalikhan** [comment] 2019-01-08 09:30
Issue opened, tracked at https://github.com/Microsoft/vscode/issues/66029

**Comment by shanalikhan** [comment] 2019-06-24 19:21
I have released new version of Settings Sync v3.3.0 fixing this issue. Im closing this ticket let me know if u guys run into some problem

**Closed by shanalikhan** 2019-06-24 19:21 UTC
Labels: code-limitation, feature-request  💡
