### ISSUE TITLE
can not upload seetings

### ISSUE THREAD

**Issue by koaqiu** [shanalikhan/code-settings-sync#69] opened 2016-08-21 16:51 UTC
**Visual Studio Code Version :** [ 1.5.0-insider ]
**Code Sync Settings Version :** [ 1.63]
**Operating System :** [ win 10 pro ]

Please make sure to write the versions and console logged error picture or copied text.
![default](https://cloud.githubusercontent.com/assets/542287/17838552/743682ee-6802-11e6-991e-b57a56b044c9.png)

**Comment by shanalikhan** [comment] 2016-08-21 17:11
Possible duplicate of [#59](https://github.com/shanalikhan/code-settings-sync/issues/59).
Check the solution. And feel free to reopen

**Closed by shanalikhan** 2016-08-21 17:11 UTC

**Comment by koaqiu** [comment] 2016-09-01 01:33
it is done.

My fault
