### ISSUE TITLE
Feature Request: Download settings on interval

### ISSUE THREAD

**Issue by MrTravisB** [shanalikhan/code-settings-sync#520] opened 2018-03-21 16:15 UTC
Auto download on start is a nice feature. Unfortunately I (and most developers I know) rarely if ever restart our computers and also don't restart VSCode. It would be nice if we could set an interval to check for new settings and download.

**Comment by shanalikhan** [comment] 2018-03-21 16:27
Duplicate of #318

**Closed by shanalikhan** 2018-03-21 16:27 UTC

**Comment by MrTravisB** [comment] 2018-03-21 16:32
@shanalikhan #318 is specifically about uploading changed settings not downloading changed settings which is why I didn't consider it a dupe.

**Comment by shanalikhan** [comment] 2018-03-22 16:19
Thanks, i have changed the title there.
Lets track it there.
