### ISSUE TITLE
can't upload settings

### ISSUE THREAD

**Issue by hxfdarling** [shanalikhan/code-settings-sync#264] opened 2017-03-24 03:04 UTC
got error:

```
workbench.main.js:136 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}d.logExtensionHostMessage @ workbench.main.js:136
workbench.main.js:103 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.
```

**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Settings Sync Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ ID_HERE ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment] 2017-03-25 17:29
Possible Duplicate of https://github.com/shanalikhan/code-settings-sync/issues/59
Let me know if error persists.

**Closed by shanalikhan** 2017-03-25 17:29 UTC
