### ISSUE TITLE
Slow startup times

### ISSUE THREAD

**Issue by fabiospampinato** [shanalikhan/code-settings-sync#673] opened 2018-10-11 19:19 UTC
I'm using VSC v1.28.0 and the latest version of this extension. I'm seeting startup times over 300ms on a mid-2014 MBP. 

I think this should be something very close to 0 since there's basically nothing going on, or there shouldn't be anything going on.

For starter this extension should be bundled with WebPack.

**Comment by shanalikhan** [comment] 2018-10-11 20:09
Duplicate of #656

**Closed** 2018-10-11 20:12 UTC

**Comment by fabiospampinato** [comment] 2018-10-11 20:29
@shanalikhan isn't that one about slowness "on the first start"? I'm seeing 300ms even on non-first starts.

**Comment by NavyAdmiral** [comment] 2018-10-12 19:59
@shanalikhan Just bundle the extension with webpack and you will see huge improvements. It's not a difficult job too, refer to @fabiospampinato 's https://github.com/fabiospampinato/vscode-todo-plus/commit/768d8983a269274dad852f4192e95f5bd2dc597f
