### ISSUE TITLE
Does not download extensions when switching to official user installation

### ISSUE THREAD

**Issue by stereokai** [shanalikhan/code-settings-sync#709] opened 2018-11-19 11:19 UTC
🐛 **Describe the bug**  
The original official installation of VSCode was system wide. Since then, Microsoft has released a user-only installation. After uninstalling the system-wide VSCode, and reinstalling the (latest) user-only VSCode, code-settings-sync is not capable of restoring backed up extensions.

🌴 **Visual Studio Code Version :** 1.29
🌴 **Code Settings Sync Version :** [ 3.2.0 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **OSS or Portable :** [ No ] 
🌴 **Operating System :** [ Win 10 1803 ] 
🌴 **Occurs On:** [ Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ [6922d55b455e32e9619195fd8aed0ccc](https://gist.github.com/stereokai/6922d55b455e32e9619195fd8aed0ccc) ]

📰 **To Reproduce**
1. Install older version of VSCode which is a system-wide installation
2. Install any extension
3. Back up to gist using sync
4. Uninstall VSCode, install latest version which is a user-only installation
5. Restore from gist using sync
6. Observe "No extensions installed" status message.

💪 **Expected behavior**
Backed up extensions should be installed.

📺 **Console Error Log** 
```
  ERR ENOENT: no such file or directory, open 'C:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\extension-output-#6': Error: ENOENT: no such file or directory, open 'C:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\extension-output-#6'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at TrailingSpaces.freezeLastVersion (C:\Users\Tom\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:266:51)
    at C:\Users\Tom\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:56:19
    at e.fire (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:585:804
    at e.fire (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at e.$acceptDocumentsAndEditorsDelta (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:496:483)
    at t._doInvokeHandler (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
    at t._invokeHandler (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
    at t._receiveRequest (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:15)
    at t._receiveOneMessage (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
    at c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
    at c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
    at e.fire (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
    at a (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
    at Socket._socketDataListener (c:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

📺  **Additional context**

**Comment by danielwagn3r** [comment] 2018-11-26 07:44
I've seen a slightly different behavior; everything seems to work during the Download of the settings, even the installation of the extension. However the aren't installed, and don't get visible after a restart of Code as well.

**Comment by shanalikhan** [comment] 2018-11-26 19:04
The problem is Code team doenst provide API for which we ( authors ) can get the required things.
If you look into the code base, all the paths are Hard Coded.


Why you want to use older version of Code. is there any scenario for which you need older version. Its better to use latest versions.

**Comment by JMLdev** [comment] 2019-01-03 23:52
Hi Shanalikhan,

I have experienced this exact same issue. The plugin was working fine until I switched to the user version of Visual Studio Code. Now it no longer works. I don't think Microsoft is distributing a system wide version of Code any more, so this is an issue that will need to be fixed if the plugin is going to continue offering value to the community.

Thanks

**Comment by shanalikhan** [comment] 2019-01-08 09:34
I have looked into this and found currently its a limitation for code API itself, Code team doesnt provide such identifier to let authors know either extension is running user wide or system wide.

They need to expose `user-data-dir` and `extensions-dir` . 

Issue is opened @ https://github.com/Microsoft/vscode/issues/66029
It would be great if you guys upvote that thread and let code team know about the urgency accordingly.

Similar issue but different scenario already opened - https://github.com/shanalikhan/code-settings-sync/issues/411

**Comment by shanalikhan** [comment] 2019-06-25 12:10
It is fixed now. Let me know if you find some problem.

**Closed by shanalikhan** 2019-06-25 12:10 UTC
Labels: bug 🐛, code-limitation
