### ISSUE TITLE
Sync Error for extensions (although stating settings.json would be the problem)

### ISSUE THREAD

**Issue by pseudonymcp** [shanalikhan/code-settings-sync#587] opened 2018-07-14 08:35 UTC
When I try to upload my settings, I get an error message

![image](https://user-images.githubusercontent.com/1522647/42722492-3209826a-874d-11e8-8811-c1385ad0ba7b.png)

saying that sync was unable to write to user settings.

![image](https://user-images.githubusercontent.com/1522647/42722511-7313934a-874d-11e8-9e62-85d9d80c0078.png)

I checked my token in advanced ync settings and I checked my user settings file. Both are fine. It worked with the same settings file, but stopped working some weeks ago.

If I make changes to my user settings file and sync it (ignoring the error message), and then compare the file to my gist, the changes have been synced. This happens for upload and download and this bug started appearing on both of my machines at the same time.

BUT: Extensions do not get synced. If I install a new extension on one machine, then sync settings (ignoring the error), the file gets sucessfully updated in my Gist. But when I sync download it on my other machine (ignoring the error), the extension does not get synced

**Visual Studio Code Version :** 1.25.1 (and 1.25.0)
**Code Settings Sync Version :** 3.0.0 (but happened also on earlier version)
**Operating System :** Windows 10 x64 (1803 and 1709) German
**Occurs On:** Upload and Download
**Proxy Enabled:** No

**To Reproduce**
1. Install a new extension and change user settings on machine 1
2. Sync: Upload setting on machine 1
3. See error for user settings
4. Go to GIST, settings.json and extensions.json are updated (despite the error)
5. Sync: Download settings on machine 2
6. See error for user settings
7. settings.json are updated, extensions are not

**Expected behavior**
All settings should be updated. The error message should not be shown for successful upload. For failed extension sync download, there should be an error message just for extensions, as user settings updated fine.

**Additional context**
Happend at the same time on both of my machines.

**Comment by shanalikhan** [comment] 2018-08-06 16:30
> settings.json are updated, extensions are not
Okay thanks, i think there might be some problem in extension downloading process might be vs code team has changed from their side.
Similar issue opened #566
I'm closing this issue and lets track that issue for progress.

**Comment by shanalikhan** [comment] 2018-08-06 16:30
Duplicate of #566

**Closed by shanalikhan** 2018-08-06 16:30 UTC
