### ISSUE TITLE
[Feature Request] Would like to sync to several accounts

### ISSUE THREAD

**Issue by RobFosterNYC** [shanalikhan/code-settings-sync#817] opened 2019-04-02 08:28 UTC
I would like to Sync to several accounts at the same time.
For example:  Two Github accounts and a  GitKraken account.

Currently I tried to add a new Github Token and a GitKraken token
but your extension only allows 1 Github Token at a time.

If this cant be done:
Then it would be nice if we could actually log into a Github or GitKraken account
And Sync to that account that we are currently logged into.
By being able to log in the regular way and then Sync as needed to that signed in account.

**Comment by shanalikhan** [comment] 2019-04-02 08:57
Duplicate of #413

**Comment by shanalikhan** [comment] 2019-04-02 08:57
When Settings Sync will have `git` support, you can easily upload where ever you like.

**Closed by shanalikhan** 2019-04-02 08:57 UTC
