### ISSUE TITLE
Can't upload and update settings

### ISSUE THREAD

**Issue by SamaneYaghoobi** [shanalikhan/code-settings-sync#844] opened 2019-04-13 09:15 UTC
🐛 **Describe the bug**  
I typed >Sync in command palette and clicked Update/Upload settings, then I got this error:
Cannot read property 'StopWatching' of undefined

🌴 **Visual Studio Code Version :** 1.33.0 
🌴 **Code Settings Sync Version :** v3.2.8 
🌴 **Operating System :** Linux Mint 18.3
🌴 **Occurs On:** Upload

📺  **Additional context**
![screenshot](https://user-images.githubusercontent.com/22401814/56077423-553be180-5df1-11e9-8677-70608c5703a7.png)

**Comment by arnohovhannisyan** [comment] 2019-04-13 23:01
Duplicate of #832

**Comment by arnohovhannisyan** [comment] 2019-04-13 23:03
@SamaneYaghoobi Try restarting vscode

**Comment by we-taper** [comment] 2019-04-14 11:19
Restarting vscode worked for me.

**Closed** 2019-04-15 03:54 UTC

**Comment by SamaneYaghoobi** [comment] 2019-05-03 15:13
@arnohovhannisyan Thanks, that's worked.
