### ISSUE TITLE
[IssueHuntFest] Backup/Restore option

### ISSUE THREAD

**Issue by Yash-Garg** [shanalikhan/code-settings-sync#725] opened 2018-12-06 15:19 UTC
💡 **Is your feature request related to a problem? Please describe.**
Adding a backup and restore option will be worth it in this because some people can be offline at times.

**Comment by shanalikhan** [comment] 2018-12-08 08:06
Yes, when the git repository sync is completed, we can always reset the settings to its local branch form.

**Comment by shanalikhan** [comment] 2018-12-08 08:06
Duplicate of #413

**Closed by shanalikhan** 2018-12-08 08:06 UTC
