### ISSUE TITLE
Unable to neither update settings nor reset the extension

### ISSUE THREAD

**Issue by dionisokan** [shanalikhan/code-settings-sync#862] opened 2019-04-25 14:58 UTC
🐛 **Describe the bug**  
Recently the Settings Sync extension reports "Cannot read property 'ignoreUploadFolders' of undefined" after choosing to upload settings.json. Selecting "Reset Extension Settings" reports "Sync : Unable to clear settings. Error logged on console. Please open an issue."

🌴 **Visual Studio Code Version :** Version 1.34.0-exploration (1.34.0-exploration)
🌴 **Code Settings Sync Version :** 3.2.9
🌴 **Standard or Insiders :** Exploration build
🌴 **Portable or Installed :** Installed
🌴 **OSS or Official Build :** Official Build (?)
🌴 **Operating System :** macOS Mojave 10.14.4
🌴 **Occurs On:** Upload (?) / Configure
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** (none)

📰 **To Reproduce**
1. Choose "**Sync : Upload / Upload Settings**";
2. Gets "Cannot read property 'ignoreUploadFolders' of undefined" notification;
3. Choose "**Sync : Reset Extension Settings**";
4. Gets "Sync : Unable to clear settings. Error logged on console. Please open an issue."

💪 **Expected behavior**
Syncing settings.json (uploading and downloading) normally happens.

📺 **Console Error Log** 
[Console output for choosing "Update / Upload"](https://pastebin.com/24fk5KaE)
[Console output for choosing "Reset Extension Settings"](https://pastebin.com/DLz4dXY5)

📺  **Additional context**
(None.)

**Comment by shanalikhan** [comment] 2019-05-02 14:10
Duplicate of #668

**Closed by shanalikhan** 2019-05-02 14:10 UTC
