### ISSUE TITLE
connection error with proxy setting.

### ISSUE THREAD

**Issue by TYZRPVX** [shanalikhan/code-settings-sync#597] opened 2018-07-18 13:40 UTC
```
Error: getaddrinfo ENOTFOUND 8080 8080:80
	at module.exports.sendError (C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\github\lib\index.js:860:19)
	at C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\github\lib\index.js:871:29
	at callCallback (C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\github\lib\index.js:734:17)
	at ClientRequest.<anonymous> (C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\github\lib\index.js:813:17)
	at emitOne (events.js:96:13)
	at ClientRequest.emit (events.js:191:7)
	at emitErr (C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\agent-base\agent.js:88:11)
	at C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\agent-base\agent.js:99:9
	at Socket.onerror (C:\Users\rio\.vscode\extensions\shan.code-settings-sync-3.0.0\node_modules\github\node_modules\https-proxy-agent\https-proxy-agent.js:104:5)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at connectErrorNT (net.js:1032:8)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

The error stack post above. My computer can connect to github by setting proxy with dev-proxy.oa.com:8080. So I set proxy like wiki hint, but it still throw a connection error.

**Comment by shanalikhan** [comment] 2018-08-17 21:41
In next version, github API will be upgraded to most recent one.
Currently its very old and depreciated. Once i release that version i will handle the proxy issues :slightly_smiling_face:

**Comment by shanalikhan** [comment] 2018-08-26 22:16
This has been fixed as a part of `v3.1.0`
Have a look.

let me know, i will reopen this issue.

**Comment by TYZRPVX** [comment] 2018-08-27 03:40
```
C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:272 [Extension Host] HttpError: request to https://api.github.com/gists?access_token=3d8ad38aab1083da81d5ee332598d9b643955b6a failed, reason: getaddrinfo ENOTFOUND 8080 8080:80
	at fetch.then.then.catch.error (C:\Users\xxx\.vscode\extensions\shan.code-settings-sync-3.1.0\node_modules\@octokit\rest\lib\request\request.js:105:13)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
```

I update this plugin, problem occured again, note that proxy can be connected by other Browsers. Thanks for your help.

**Comment by TYZRPVX** [comment] 2018-08-27 09:33
config post like this
```
{"ignoreUploadFiles":["projects.json","projects_cache_vscode.json","projects_cache_git.json","projects_cache_svn.json","gpm_projects.json","gpm-recentItems.json"],"ignoreUploadFolders":["workspaceStorage"],"ignoreExtensions":[],"replaceCodeSettings":{"http.proxy":"127.0.0.1:12759"},"gistDescription":"Visual Studio Code Settings Sync Gist","version":310,"token":"3d8ad38aab1083da81d5ee332598d9b643955b6a","downloadPublicGist":false,"supportedFileExtensions":["json","code-snippets"],"openTokenLink":true,"useCliBaseInstallation":true,"lastUpload":null,"lastDownload":null,"githubEnterpriseUrl":null,"askGistName":false}
```

**Comment by shanalikhan** [comment] 2018-08-27 09:37
Read this:
https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support

**Comment by shanalikhan** [comment] 2018-09-04 21:44
Is this duplicate of #597 ?

**Comment by duanehutchins** [comment] 2018-09-06 15:36
did you mean #376 ?

**Comment by shanalikhan** [comment] 2018-09-06 16:17
Pending for https://github.com/Microsoft/vscode/issues/12588
As discussed in https://github.com/shanalikhan/code-settings-sync/issues/376#issuecomment-419139603

**Closed by shanalikhan** 2018-09-06 16:17 UTC
Labels: bug 🐛, code-limitation

**Comment by TYZRPVX** [comment] 2018-09-28 12:36
Problem solved by setting global proxy of vscode today.

Very thanks for your help.

**Comment by eromoe** [comment] 2018-12-11 08:45
![image](https://user-images.githubusercontent.com/3938751/49788290-f04d7d80-fd63-11e8-904d-fc98715a7a15.png)
system proxy seems still not work . 

I click the "显示匹配的扩展"(view compatible extention) .
`code-settings-sync` doesn't come out.
