### ISSUE TITLE
Add gist ID from command line to force sync on VSC install

### ISSUE THREAD

**Issue by idoo** [shanalikhan/code-settings-sync#1050] opened 2019-09-26 14:46 UTC
I'm creating bash scripts to allow me setup dev configuration by running few commands.

Currently I'm installing VSC from brew, running 
`code --install-extension Shan.code-settings-sync`

And then I want to pass GIST id and force sync on VSC start. However looks like it's not possible now, as I could understood (https://github.com/shanalikhan/code-settings-sync/issues/465#issuecomment-349903749). Guys, maybe you have any ideas how I could implement it?

**Comment by shanalikhan** [comment] 2019-09-26 14:47
Duplicate of #403

**Comment by shanalikhan** [comment] 2019-09-26 14:48
If you want to perform upload / download on code start

Checkout `autoUpload` and `autoDownload` configurations. Download can be performed on startup. Upload can be performed on settings changed.

If you have questions regarding command line automation, pls discuss over the main attached issue.

**Closed as completed by shanalikhan** 2019-09-26 14:47 UTC

**Comment by idoo** [comment] 2019-09-26 14:50
@shanalikhan what do yo mean by `autoUpload` ? there are no comments related such sections on issue that you've provided ¯\_(ツ)_/¯

**Comment by shanalikhan** [comment] 2019-09-26 14:52
Check the features on Readme.

https://github.com/shanalikhan/code-settings-sync#features

If you want to do manually see the [Global Settings](https://github.com/shanalikhan/code-settings-sync#global-settings)

**Comment by Zireael** [comment] 2019-11-17 23:50
I'm doing settings sync on first run like this in my Linux docker file with online version of VSCode called [code-server](https://github.com/cdr/code-server). If you change `code-server` in script below to `code`, it will work for normal VSCode too.

```Dockerfile
RUN code-server --install-extension Shan.code-settings-sync

RUN echo "{}" >> /root/.local/share/code-server/User/settings.json

RUN tmp=$(mktemp) && \
  jq -M '. +{ \
  "sync.syncExtensions": true,\
  "sync.autoDownload": true,\
  "sync.gist":"abc123def987",\
  "telemetry.enableTelemetry": false }' /root/.local/share/code-server/User/settings.json > "$tmp" && mv "$tmp" /root/.local/share/code-server/User/settings.json

RUN echo "{}" >> /root/.local/share/code-server/User/syncLocalSettings.json

RUN tmp=$(mktemp) && \
  jq -M '. +{ "downloadPublicGist": true }' /root/.local/share/code-server/User/syncLocalSettings.json > "$tmp" && mv "$tmp" /root/.local/share/code-server/User/syncLocalSettings.json
```


Basically creating VSCode `settings.json` and adding gist ID to it using `jq` and then creating `syncLocalSettings.json` config with `"downloadPublicGist": true`.
When VSCode (code-server) is opened first time, settings download gets successfully started.
If you don't want auto-download to start, change `"sync.autoDownload": true` to `false`

Now I only need to find a way to initialize VSCode first run bootstrap through command line /bash
