### ISSUE TITLE
Ability to ignore auto sync trigger on some settings.

### ISSUE THREAD

**Issue by wsantos** [shanalikhan/code-settings-sync#553] opened 2018-05-16 14:44 UTC
[Vim extension](https://github.com/VSCodeVim/Vim) has a setting to emulate `vim-airline` so it change the status bar depending on which mode Vim is, but due to API Limitations they keep changing the settings.json for it, and it unfortunately triggers the sync, would be nice if we could exclude some settings from the auto sync.

In this case if `settings.json` change and the only changed settings is the excluded one, we do no trigger the auto-sync.

Links:
https://github.com/VSCodeVim/Vim#status-bar-color-settings

**Comment by shanalikhan** [comment] 2018-05-17 06:54
Nice idea.

**Comment by fakhamatia** [comment] 2018-12-29 10:39
sorry for bad English
i have two OS , Linux and windows
in windows directory of java is :  "java.home": "C:\\Program Files\\Java\\jdk-11.0.1",
but in Linux its different , and when i sync setting its mixed up .

**Comment by shanalikhan** [comment] 2019-01-03 10:09
@fakhamatia 
See this wiki for handling scenarios like yours.

**Comment by shanalikhan** [comment] 2019-04-04 08:35
Duplicate of #754

**Closed by shanalikhan** 2019-04-04 08:35 UTC
Labels: feature-request  💡
