### ISSUE TITLE
Thoughts on upcoming native support in VS Code?

### ISSUE THREAD

**Issue by anishkny** [shanalikhan/code-settings-sync#1238] opened 2020-07-25 17:03 UTC
Looks like VS Code is planning to support settings sync **natively** - see [June 2020 Update](https://code.visualstudio.com/updates/v1_47#_settings-sync) and https://github.com/microsoft/vscode/issues/2743

What does this mean for the future of this plugin? @shanalikhan @arnohovhannisyan

**Comment by shanalikhan** [comment] 2020-09-28 12:10
Duplicate of #1188

**Closed as completed by shanalikhan** 2020-09-28 12:10 UTC
