### ISSUE TITLE
setting export functionality

### ISSUE THREAD

**Issue by zzzgit** [shanalikhan/code-settings-sync#596] opened 2018-07-18 01:32 UTC
**Is your feature request related to a problem? Please describe.**
I want to export my vs-code settings to a file.

**Describe the solution you'd like**
Sometimes github.com is banned by the network manager, I can't sync the settings to cloud, so I want to export settings to a locale file.
Is it possible? 

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by shanalikhan** [comment] 2018-07-18 09:16
Duplicate of #256

**Closed by shanalikhan** 2018-07-18 09:16 UTC
