### ISSUE TITLE
The extension is not working in vscodium, though it works in vscode as well as vscode-insiders

### ISSUE THREAD

**Issue by sanjarcode** [shanalikhan/code-settings-sync#911] opened 2019-06-16 02:00 UTC
Issue Type: <b>Bug</b>

I use this extension for synching my settings, keymaps etc on for vscode. I switched to vscodium but this extension is not working. Settings sync by Shan Khan. ext install Shan.code-settings-sync.

Extension version: 3.2.9
VS Code version: VSCodium 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-13T10:36:20.055Z)
OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core CPU       T4500  @ 2.30GHz (2 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|5.79GB (1.34GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by arnohovhannisyan** [comment] 2019-06-16 03:24
Duplicate of #668, fixed in v3.3.0

**Comment by shanalikhan** [comment] 2019-06-16 19:02
Duplicate of #668

**Closed by shanalikhan** 2019-06-16 19:02 UTC
