### ISSUE TITLE
Support remote-server mode settings sync

### ISSUE THREAD

**Issue by whusnoopy** [shanalikhan/code-settings-sync#913] opened 2019-06-19 07:38 UTC
💡 **Is your feature request related to a problem? Please describe.**

As VSCode 1.35 turned [remote development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) to stable version, can we support sync settings on remote vscode server?

I'm using VSCode 1.35.1 on Windows 10 x64 1903 with WSL, when I use remote mode, VSCode will install a server version on `~/.vscode-server` on WSL, and the settings located on `~/.vscode-server/data/Machine/settings.json`, which different to Linux default `~/.config/Code/User/settings.json`, so if I tried to upload or download settings, Settings Sync missing the config files and throw errors to debug console

Someone have figured this issue on https://github.com/shanalikhan/code-settings-sync/issues/870

Maybe there is same problem on Remote - SSH and Remote - Container, but I don't have any environment to test. 

💡 **Describe the solution you'd like**

Support sync on remote development, include SSH, Container, WSL.

💡 **Additional context**

Nothing.

Thank you for this extension, it helped me a lot on develop on different machines.

**Comment by arnohovhannisyan** [comment] 2019-06-19 07:46
Duplicate of #668

**Comment by shanalikhan** [comment] 2019-06-19 09:17
@whusnoopy 

Can you try this build by @arnohovhannisyan 
https://cdn.discordapp.com/attachments/549007146868539408/590821294811906069/code-settings-sync-3.2.9.vsix

and let me know if is helps, this build will be released in v3.3.0

**Comment by whusnoopy** [comment] 2019-06-20 02:06
@shanalikhan This version can work when all the config files under `~/.config/Code/User`, but VSCode on Windows with Remote - WSL placed config files under `~/.vscode-server/data/Machine`, as VSCode won't update settings under `~/.config/Code/User`, the Settings Sync always upload a wrong file

**Comment by arnohovhannisyan** [comment] 2019-06-20 04:48
@whusnoopy Can you please install it and see if it works? This build should work perfectly fine with WSL.

**Comment by whusnoopy** [comment] 2019-06-20 06:13
@arnohovhannisyan I've uninstalled old version in VSCode local and WSL then installed from the .vsix file, but I'm not sure which version I'm running now because the public version from market and the .vsix file both show version 3.2.9, I noticed the error message changed so I assumed I've installed the .vsix.

I will do a clean installation later today, and record everything I did to check which step get wrong.

**Comment by whusnoopy** [comment] 2019-06-20 11:56
Finally, I've use another computer to test install extension from the vsix file, and the Settings Sync appear on Local Installed section in extension page, won't show in WSL Installed, or can be installed on WSL.

This vsix file won't show any error or warning message with Remote WSL anymore. But I don't know how to install it on WSL side, so the settings in WSL still on local only.

Maybe we've talked on two different problems above, I want to sync settings in WSL or other remote server, you are fixing the extensions sync issues when connect to WSL.

**OS**: Windows 10 1903 x64, build 18362.175
**VSCode**: 1.35.1
**WSL**: Ubuntu 18.04.2 LTS

**Comment by shanalikhan** [comment] 2019-06-24 19:17
I have released new version of Settings Sync v3.3.0 fixing this issue. Im closing this ticket let me know if u guys run into some problem

**Closed by shanalikhan** 2019-06-24 19:17 UTC

**Comment by pecigonzalo** [comment] 2019-12-09 10:51
The remote extension list for WSL does not seem to sync yet was this working for you @shanalikhan ?

**Comment by coreydowning** [comment] 2020-01-03 23:08
This did not work for me, lost all my WSL extensions because I didn't verify the backup 😭

**Comment by branmay98** [comment] 2020-04-21 00:49
Any update on this? Seems to not be working by my cursory lookthrough.

**Comment by genomics-geek** [comment] 2020-05-25 18:15
From what I understand, remote development creates a folder `.vscode-server` on the host.  If you just create a tarball of your local extensions (i.e. `tar -czvf extensions.tar.gz extensions/`) and then scp that to the remote host and unarchive it in `.vscode-server/extensions` it works as expected.  Just stinks that the settings sync won't do it automatically for you

**Comment by theAkito** [comment] 2020-05-27 13:53
> From what I understand, remote development creates a folder `.vscode-server` on the host. If you just create a tarball of your local extensions (i.e. `tar -czvf extensions.tar.gz extensions/`) and then scp that to the remote host and unarchive it in `.vscode-server/extensions` it works as expected. Just stinks that the settings sync won't do it automatically for you

An utterly annoying workaround. What's the point of this sync, if I have to do the dirty work for it.

Any proper fix in the works yet? ~80% of my extensions are on WSL...

**Comment by AdsonCicilioti** [comment] 2020-05-28 16:32
That sad! I went to restore my configuration for my Windows WSL environment and nothing came in the settings.json file in WSL.

Sad!

**Comment by theAkito** [comment] 2020-05-28 16:34
@shanalikhan 

Any updates on this? This issue should also be re-opened...

**Comment by coreydowning** [comment] 2020-05-28 18:23
Preferences Sync now exists in VSCode Insiders Edition and seems to sync my settings between Mac, Windows, and WSL just fine. Not sure when it will hit the stable version of VSCode but insiders has worked well for me.

**Comment by theAkito** [comment] 2020-05-28 18:45
@coreydowning 

Thanks for the info. So it is up to VS Code for this to work?

**Comment by coreydowning** [comment] 2020-05-28 18:51
The VSCode preferences sync makes this extension mostly obsolete.

**Comment by theAkito** [comment] 2020-05-28 18:53
@coreydowning 

Oh, sorry, I misunderstood. So this is a setting within VS Code itself? I didn't know about that. Thanks for sharing!

**Comment by remidebette** [comment] 2020-06-03 15:45
Hi,

Indeed this is not solved.
After starting to work on the WSL (that is live since Windows 10 2004) on my windows PC and doing a mechanical "Sync: Upload Settings" I lost all my plugins on my other mac and linux machines.

I will have a look on the VSCode preferences sync
