### ISSUE TITLE
Exception : Unexpected token in JSON On Download During Proxy 

### ISSUE THREAD

**Issue by enigmab17** [shanalikhan/code-settings-sync#135] opened 2016-11-07 18:56 UTC
**Visual Studio Code Version :** 1.7.1 (Source & Target are the same version)
**Code Sync Settings Version :** 2.3.7
**Operating System :** Windows 10 Enterprise x64
**Occurs On:** Download
**Proxy Enabled:** Yes (currently running through CNTLM due to Corporate proxy)

Hey all

Trying to download settings onto one install of code after uploading from another install of code.
Uploads successfully, however when executing the download on the target it throws an error.

```
extensionHost.ts:255[Extension Host] SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at P:\Users\{username}\.vscode\extensions\Shan.code-settings-sync-2.3.7\out\src\pluginService.js:206:36
    at process._tickCallback (internal/process/next_tick.js:103:7)I.logExtensionHostMessage @ extensionHost.ts:255
messageService.ts:128Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:128
```

Tried searching on the already open issues but cannot find one that matches.
Any ideas?

**Comment by shanalikhan** [comment] 2016-11-08 10:01
Which extensions you have installed,
Can you make your GIST public and share with me so i can see data coming from the GIST in downloading and generate this issue.
U may write ID here or email me.

**Comment by kuzyas** [comment] 2016-11-08 10:56
Gist : 7ebfbe5c666737a972495954eacd4888

**Comment by shanalikhan** [comment] 2016-11-08 11:06
@kuzyas i have just tried downloading and it worked fine.

```
EXTENSIONS ADDED : 
 
Angular1 - Version :0.1.16 
Angular2 - Version :1.0.2 
```

are you sure u are getting exception by downloading the same GIST content or extension it has saved ?

**Comment by enigmab17** [comment] 2016-11-08 14:07
Hey Shanalikhan

Extensions installed are these:
auto-close-tag - Version :0.3.4 
beautify - Version :0.5.4 
code-settings-sync - Version :2.3.7 
csharp - Version :1.4.1 
debugger-for-chrome - Version :2.2.1 
githistory - Version :0.1.0 
html-css-class-completion - Version :1.0.3 
html-snippets - Version :0.0.18 
HTMLHint - Version :0.0.3 
JavaScriptSnippets - Version :1.2.0 
jquerysnippets - Version :0.0.1 
jshint - Version :0.10.15 
npm-intellisense - Version :0.1.4 
prettify-json - Version :0.0.3 
rest-client - Version :0.10.1 
stylelint - Version :0.18.1 
tslint - Version :0.5.40 
view-in-browser - Version :0.0.3 
vscode-color - Version :0.2.1 
vscode-generate-getter-setter - Version :0.4.1 
vscode-icons - Version :4.0.0 
vscode-npm - Version :3.3.0 
vscode-npm-script - Version :0.0.21 
xml - Version :1.6.0 

I've tried it a few times now, I can successfully upload the settings but using the rest doesn't work at all.

Gist: 0d3fb8f9454966344959e75318b9c64b
Should be public

Pretty sure that it's trying to download the same content it has saved.
If I upload and then download on the same VS Code instance it works fine, but if I upload on one and try to download from another it fails as above.

Will try again this morning and see if the same thing is happening.

Thanks :)

**Comment by enigmab17** [comment] 2016-11-08 14:41
Did some more testing on it.
Without any extensions installed it works fine (download works on target without error).

Source Extensions:
VS Code Sync
Beautify

Upload succeeds

Target Extensions:
VS Code Sync

Download fails with error.

**Comment by kuzyas** [comment] 2016-11-09 06:41
Same here.

Without proxy everything works fine.
Without extensions installed and with proxy enabled it works fine.
With proxy and extensions it syncs settings, but crashes on installing extensions part.

**Comment by shanalikhan** [comment] 2016-11-10 10:31
@kuzyas Thanks for testing in detail.
@enigmab17 can you try also with the same scenario above to confirm its the problem regarding to only proxy behind ?
As i tried to solve proxy support for users in https://github.com/shanalikhan/code-settings-sync/issues/60

**Comment by enigmab17** [comment] 2016-11-10 13:59
Don't have the ability to not do it through a Proxy at the moment but I guess that's what the issue will be.
Will try and see if I can retrieve it when I get home :)

**Comment by enigmab17** [comment] 2016-11-10 16:40
Confirmed.
Without proxy enabled it successfully downloads settings and sets up extensions.

**Comment by shanalikhan** [comment] 2016-11-12 07:06
I have released the version 2.3.8 to solve this issue.
Let me know :) by running your test cases @enigmab17 @kuzyas

**Comment by shanalikhan** [comment] 2016-11-14 13:58
Im closing this issue assuming its working for your case. let me know if error is still there.

@enigmab17 @kuzyas

**Comment by kuzyas** [comment] 2016-11-15 07:12
Still got same error when proxy enabled.

**Comment by enigmab17** [comment] 2016-11-15 13:43
Hey Shanalikhan

I've upgraded my source and target versions.
Cleared both, but still erroring out when the target downloads it.

`extensionHost.ts:255[Extension Host] SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at P:\Users\szt\.vscode\extensions\Shan.code-settings-sync-2.3.8\out\src\pluginService.js:206:36
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by shanalikhan** [comment] 2016-11-15 20:37
I am not able to reproduce this error at my end, by watching code i had made certain tweaks - I will keep an eye and see what can be done from my side.

Can you guys download the code and uninstall the extension and run directly from the code and send me a pull request to solve this issue, i will be more happy to do that.

Following are the simple steps and it will open the extension code in the editor
https://github.com/shanalikhan/code-settings-sync#how-to-contribute

@enigmab17 , @kuzyas

**Comment by shanalikhan** [comment] 2017-01-06 13:06
Please try again new version 2.4.2
https://github.com/shanalikhan/code-settings-sync/releases/tag/v2.4.2.

Let me know if there is some problem

**Closed by shanalikhan** 2017-01-06 13:06 UTC
Labels: bug, help-wanted
