### ISSUE TITLE
Unable to sync or download sync settings

### ISSUE THREAD

**Issue by nickytonline** [shanalikhan/code-settings-sync#96] opened 2016-09-09 01:07 UTC
First off amazing extension. Second, if you need more information, let me know.

**Visual Studio Code Version :** [1.5.1]
**Code Sync Settings Version :** [2.2.3 ]
**Operating System :** [ Ubuntu 16.04 ]

Please make sure to write the versions and console logged error picture or copied text.

From the looks of the error, it appears to be an encoding issue.

```
threadService.ts:217 [Extension Host] cannot open untitled:%5Chome%5Ctaco%5C.config%5CCode%5CUser%5Csummary.txt.
Detail: expected URI untitled:%5Chome%5Ctaco%5C.config%5CCode%5CUser%5Csummary.txt BUT GOT untitled:/home/taco/.config/Code/User/summary.txt
(anonymous function) @ threadService.ts:217
    emitTwo @ events.js:100
    emit @ events.js:185
    handleMessage @ internal/child_process.js:718
    channel.onread @ internal/child_process.js:444
```

**Comment by shanalikhan** [comment] 2016-09-16 10:54
Im unable to reproduce this error. 
Can you update to latest version 2.2.5 and let me know if its still reproducing.

**Comment by nickytonline** [comment] 2016-09-16 10:57
Thanks @shanalikhan, will do.

**Comment by shanalikhan** [comment] 2016-09-17 09:17
i have pushed an update 2.2.6.
If you still having problem then 


Can you paste the log on upload and download from the developer console.
For example i have log showing as 

` FILE URI For Summary Page : C:\Users\shana\AppData\Roaming\Code\User\summary.txt`

Whats your URI

**Comment by nickytonline** [comment] 2016-09-17 14:20
@shanalikhan with update 2.2.6 I get the following on Ubuntu 16.04 with VSCode 1.5.2
```
[Extension Host] Linux
threadService.ts:217 [Extension Host] FILE URI For Summary Page : \home\taco\.config\Code\User\summary.txt
threadService.ts:217 [Extension Host] cannot open untitled:%5Chome%5Ctaco%5C.config%5CCode%5CUser%5Csummary.txt. Detail: expected URI untitled:%5Chome%5Ctaco%5C.config%5CCode%5CUser%5Csummary.txt BUT GOT untitled:/home/taco/.config/Code/User/summary.txt
```

and if I download the sync settings I get:
```
[Extension Host] Linux                   threadService.ts:217
```

and it does not download my sync settings.

Also, everytime I try to exit VS Code after running Shift + Alt + U or sync upload via CTRL + Shift + P, it asks the following:

![screenshot from 2016-09-17 10-15-35](https://cloud.githubusercontent.com/assets/833231/18608744/b4d81d68-7cbf-11e6-8ef0-087304535fd1.png)


I will try to debug the extension on my computer and see if I can see what's going on.

**Comment by nickytonline** [comment] 2016-09-18 02:51
It's weird. I debugged the extension and it blows up here in common.ts

```
        var setting: vscode.Uri = vscode.Uri.parse("untitled:" + tempURI);

        vscode.workspace.openTextDocument(setting).then((a: vscode.TextDocument) => {
        ...

```

which appears to be the standard way to generate a temp file. I wonder if something broke in vscode for this between v. 1.4 and 1.5+ on Linux. Using the Yeoman generator, I created a new extension with just this to test it and I get the same error.

extension.ts from my sample hello world extension
```
'use strict';
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {

    // Use the console to output diagnostic information (console.log) and errors (console.error)
    // This line of code will only be executed once when your extension is activated
    console.log('Congratulations, your extension "hello" is now active!');

    // The command has been defined in the package.json file
    // Now provide the implementation of the command with  registerCommand
    // The commandId parameter must match the command field in package.json
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        // The code you place here will be executed every time your command is executed

        // Display a message box to the user
        vscode.window.showInformationMessage('Hello World!');
    });

    context.subscriptions.push(disposable);
        const tempURI = '/home/nickytonline/summary.txt';
        const setting: vscode.Uri = vscode.Uri.parse(`untitled: ${tempURI}`);

        vscode.workspace.openTextDocument(setting).then((a: vscode.TextDocument) => {
          console.log('opened temp doc for summary.');
        });
}

// this method is called when your extension is deactivated
export function deactivate() {
}
```

**Comment by nickytonline** [comment] 2016-09-18 03:05
@shanalikhan, found the issue. It's as I suspected. It's an open issue for VS Code for Ubuntu and OS X only, https://github.com/Microsoft/vscode/issues/12192 . So I think you can close this.

Thanks again for the awesome extension.

**Comment by shanalikhan** [comment] 2016-09-18 04:30
Yea right as i suspected, its a issue in vscode api.
I have posted an issue in vscode

**Comment by nickytonline** [comment] 2016-09-19 11:44
@shanalikhan, this apparently fixes it, https://github.com/Microsoft/vscode/issues/12192#issuecomment-247941429 . I can do a PR tonight for it if you want.

**Comment by shanalikhan** [comment] 2016-09-19 18:49
@nickytonline https://github.com/shanalikhan/code-settings-sync/pull/107 has just fixed the problem in master branch, can you please check out the code and test if its working in your side also so i can close the issue and push an update.

**Comment by nickytonline** [comment] 2016-09-19 19:16
@shanalikhan, upload works again with master. Tried download but nothing seems to happen. Could be just a debug issue on my part.

**Comment by shanalikhan** [comment] 2016-09-19 19:20
Downloading is working fine at my end. Hope u already have latest commit.
No problem i am still testing with auto upload feature will jump to 2.3 with auto upload soon with these fixes

**Comment by nickytonline** [comment] 2016-09-21 12:57
@shanalikhan, debugging to try downloading settings doesn't seem to work for me on Ubuntu, but I think it's just me when debugging. If you have it working, go ahead and push a new version.

**Comment by shanalikhan** [comment] 2016-09-21 21:01
@nickytonline i have pushed an update version 2.2.7
Let me know if it solved the issue.
its working at my side

**Comment by nickytonline** [comment] 2016-09-21 21:04
Cool,  thanks man. I'll check it out tonight.

**Comment by shanalikhan** [comment] 2016-09-22 16:52
I'm closing this issue assuming its fixed in Ubuntu.
Let me know if the error is still there.

**Closed by shanalikhan** 2016-09-22 16:52 UTC
Labels: bug, working on it

**Comment by nickytonline** [comment] 2016-09-25 01:54
Uploading settings on Ubuntu works again (Shift + ALT + U) and downloading them works too (Shift + ALT + D). Thanks for fixing this @shanalikhan.
