### ISSUE TITLE
Startup Extremely slow

### ISSUE THREAD

**Issue by u2berggeist** [shanalikhan/code-settings-sync#543] opened 2018-05-03 21:48 UTC
**Visual Studio Code Version :** 1.23.0
**Code Settings Sync Version :** 2.9.2
**Operating System :** Windows 8.1
**Occurs On:** VS Code startup
**Proxy Enabled:** No

Settings-sync takes a very long time to load and slows down the entire program starting. This is particularly surprising since I don't have it set to automatically do anything. According to the `Extension Activation Stats`, it takes over 20 seconds to load:
![Extension Activation Stats](https://user-images.githubusercontent.com/20801821/39604203-213e3fd4-4ef9-11e8-9b36-fe255521b069.png)

I've repeated this several times now. While 20 seconds is the highest I've seen, A) it's almost always above 10 seconds and B) is easily the longest extension to launch. That just seem ridiculous to me. Especially for something that doesn't do anything on start up. It doesn't do anything until I tell it to do something.

**Comment by shanalikhan** [comment] 2018-05-06 21:11
Duplicate of #472

**Comment by shanalikhan** [comment] 2018-05-06 21:11
Feel free to discuss there.

**Closed by shanalikhan** 2018-05-06 21:11 UTC
