### ISSUE TITLE
Sync not installing extensions

### ISSUE THREAD

**Issue by ZDTaylor** [shanalikhan/code-settings-sync#743] opened 2018-12-30 02:04 UTC
This extension fails to install my extension list when it is run. I have attached the error log below. It says bin/code does not exist. I am not sure what the working directory of the extension is, but /bin/code does exist on my system.

```sh
COMMAND LINE EXTENSION DOWNLOAD SUMMARY
--------------------
TOTAL EXTENSIONS : 21


"bin/code" --install-extension formulahendry.auto-close-tag
Error: Command failed: "bin/code" --install-extension formulahendry.auto-close-tag
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension formulahendry.auto-rename-tag
Error: Command failed: "bin/code" --install-extension formulahendry.auto-rename-tag
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension austin.code-gnu-global
Error: Command failed: "bin/code" --install-extension austin.code-gnu-global
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension formulahendry.code-runner
Error: Command failed: "bin/code" --install-extension formulahendry.code-runner
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension streetsidesoftware.code-spell-checker
Error: Command failed: "bin/code" --install-extension streetsidesoftware.code-spell-checker
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension naumovs.color-highlight
Error: Command failed: "bin/code" --install-extension naumovs.color-highlight
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension ms-vscode.cpptools
Error: Command failed: "bin/code" --install-extension ms-vscode.cpptools
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension GrapeCity.gc-excelviewer
Error: Command failed: "bin/code" --install-extension GrapeCity.gc-excelviewer
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension eamodio.gitlens
Error: Command failed: "bin/code" --install-extension eamodio.gitlens
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension Zignd.html-css-class-completion
Error: Command failed: "bin/code" --install-extension Zignd.html-css-class-completion
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension abusaidm.html-snippets
Error: Command failed: "bin/code" --install-extension abusaidm.html-snippets
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension James-Yu.latex-workshop
Error: Command failed: "bin/code" --install-extension James-Yu.latex-workshop
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension PKief.material-icon-theme
Error: Command failed: "bin/code" --install-extension PKief.material-icon-theme
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension zhuangtongfa.Material-theme
Error: Command failed: "bin/code" --install-extension zhuangtongfa.Material-theme
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension christian-kohler.path-intellisense
Error: Command failed: "bin/code" --install-extension christian-kohler.path-intellisense
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension ms-python.python
Error: Command failed: "bin/code" --install-extension ms-python.python
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension Ikuyadeu.r
Error: Command failed: "bin/code" --install-extension Ikuyadeu.r
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension REditorSupport.r-lsp
Error: Command failed: "bin/code" --install-extension REditorSupport.r-lsp
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension Ikuyadeu.r-pack
Error: Command failed: "bin/code" --install-extension Ikuyadeu.r-pack
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension pranaygp.vscode-css-peek
Error: Command failed: "bin/code" --install-extension pranaygp.vscode-css-peek
/bin/sh: bin/code: No such file or directory


"bin/code" --install-extension ecmel.vscode-html-css
Error: Command failed: "bin/code" --install-extension ecmel.vscode-html-css
/bin/sh: bin/code: No such file or directory
```

**Comment by shanalikhan** [comment] 2019-01-03 11:19
You have not filled the template for the issue.
Please provide those things.
Are you using code is OSS or Non OSS?

**Comment by ZDTaylor** [comment] 2019-01-03 16:21
Sorry about missing the template.
I am using Code OSS Standard v1.30.1. I am on Manjaro Linux.

**Comment by shanalikhan** [comment] 2019-01-03 16:41
Duplicate of #668

**Closed by shanalikhan** 2019-01-03 16:41 UTC

**Comment by shanalikhan** [comment] 2019-01-03 16:43
@dan-dr have sent a PR fixing this issue for OSS versions.
The only thing remaining is the testing the that PR for Non OSS versions so we are sure it doesnt break anything.
