### ISSUE TITLE
Sync skip installation of packages.

### ISSUE THREAD

**Issue by SkeLLLa** [shanalikhan/code-settings-sync#723] opened 2018-12-04 08:41 UTC
🐛 **Describe the bug**  
Sync for some reason skips installation of certain packages like: 
```
  {
    "metadata": {
      "id": "96c69be9-5b09-4a18-8c82-4d30ab145017",
      "publisherId": "formulahendry.docker-explorer",
      "publisherDisplayName": "formulahendry"
    },
    "name": "docker-explorer",
    "publisher": "formulahendry",
    "version": "0.1.6"
  },
```

Also force download also doesn't help.

After that it uploads broken settings to gist without missing extension, so it breaks settings in gist.

🌴 **Visual Studio Code Version :** 1.29.1
🌴 **Code Settings Sync Version :** 3.2.2
🌴 **Standard or Insiders :** standard
🌴 **OSS or Portable :** OSS
🌴 **Operating System :** Linux
🌴 **Occurs On:** Upload/Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 92314909a1eae219a3e2bf836eea2d9f

📰 **To Reproduce**
1. Open VSCode
2. Configure Sync to download settings from Gist
3. Wait till installation
4. Close VSCode, probably restart PC
5. Launch VSCode

💪 **Expected behavior**
All extensions present, force download applies all extensions present in gist, sync shouldn't upload incorrect extension list

📺 **Console Error Log** 
There are no errors related to sync extension.

**Comment by shanalikhan** [comment] 2018-12-05 15:46
> There are no errors related to sync extension. 

have you checked the developer console , are any errors logged in installing those extensions in your computer.

**Comment by SkeLLLa** [comment] 2018-12-05 18:17
@shanalikhan nope. On force download it just says that there are no extensions to install. And there's only this error #706, but it's related to force download and when it's disabled there are no other errors.

**Comment by shanalikhan** [comment] 2019-03-08 12:51
Try now on `v3.2.7` and let me know, in this version there is some improvements made on installing extensions.

If you are using OSS mode - there is already issue opened https://github.com/shanalikhan/code-settings-sync/issues/668

**Comment by apiep** [comment] 2019-03-11 07:20
I have faced the same issue, but on the output console there is an error
```
"bin/code" --install-extension Gruntfuggly.activitusbar
Error: Command failed: "bin/code" --install-extension Gruntfuggly.activitusbar
/bin/sh: bin/code: No such file or directory
```

**Comment by shanalikhan** [comment] 2019-04-01 14:17
Duplicate of #668

**Closed by shanalikhan** 2019-04-01 14:17 UTC
