### ISSUE TITLE
Not working on Manjaro Linux

### ISSUE THREAD

**Issue by Johnystar** [shanalikhan/code-settings-sync#866] opened 2019-04-30 20:38 UTC
Sync fails to install the extensions with the following error:
```
"bin/code" --install-extension ms-python.python
Error: Command failed: "bin/code" --install-extension ms-python.python
/bin/sh: bin/code: No such file or directory
```
This issue didn't occur to me on Windows or Debian-based distributions (namely Ubuntu and Elementary OS).

**Comment by ildoc** [comment] 2019-05-01 15:22
same on archlinux (not so surprising...)

imho the problem could be at https://github.com/shanalikhan/code-settings-sync/blob/master/src/service/pluginService.ts#L288 

```
else if (osType === OsType.Linux) {
      if (isInsiders) {
        codeLastFolder = "code-insiders";
        codeCliPath = "bin/code-insiders";
      } else {
        codeLastFolder = "code";
        codeCliPath = "bin/code";
      }
```

should be

```
else if (osType === OsType.Linux) {
      if (isInsiders) {
        codeLastFolder = "code-insiders";
        codeCliPath = "/bin/code-insiders";
      } else {
        codeLastFolder = "code";
        codeCliPath = "/bin/code";
      }
```

**Comment by shanalikhan** [comment] 2019-05-02 10:28
@ildoc can you send me a PR where you think it can be improved for Manjaro Linux, while keeping the support for ubuntu and other os.

**Comment by cristiangauma** [comment] 2019-05-03 20:06
A quick workaround while someone has time to create the PR:

`mkdir -p ~/bin
ln -s `which code` ~/bin/code`

I have just tested it and restored my configuration on Manjaro.

**Comment by sebtiz13** [comment] 2019-05-09 23:02
@cristiangauma your solution work fine with "code - oss" (open source version of vscode) on arch linux

**Comment by kestel** [comment] 2019-05-14 11:41
@cristiangauma also your solution help on VSCodium.

**Comment by alfinbi** [comment] 2019-05-19 13:09
same problem here using arch linux, the path should be /bin/code, not bin/code
solution provided by @ildoc should be applied...

**Comment by arnohovhannisyan** [comment] 2019-06-02 21:09
Duplicate of #668

**Comment by shanalikhan** [comment] 2019-06-25 11:00
Settings Sync v3.3.0 is released with the fix by @arnohovhannisyan 
Let me know if you guys find some problem.
I'm closing the issue.

**Closed by shanalikhan** 2019-06-25 11:00 UTC
Labels: bug 🐛
