### ISSUE TITLE
open settings gist to browser via command

### ISSUE THREAD

**Issue by k1nghat** [shanalikhan/code-settings-sync#749] opened 2019-01-14 01:37 UTC
💡 **Describe the solution you'd like**
a command added to code settings sync so you can view your settings gist in external default browser.

**Comment by shanalikhan** [comment] 2019-06-27 13:32
@arnohovhannisyan 

We can add the link in that PR, to allow user to open the the GIST.
The text and link should be available once the GIST and token is setup.
Enterprise github links should be supported

**Comment by shanalikhan** [comment] 2019-07-11 16:16
Duplicate of #506

**Closed by shanalikhan** 2019-07-11 16:16 UTC
Labels: feature-request  💡
