### ISSUE TITLE
Gist setup but can't get addon to use

### ISSUE THREAD

**Issue by ksnyde** [shanalikhan/code-settings-sync#86] opened 2016-09-03 12:11 UTC
**Visual Studio Code Version :** [ 1.4 ]
**Code Sync Settings Version :** [ 2.2.3 ]
**Operating System :** [ OSX Yosemite 10.11.6 ]

Please make sure to write the versions and console logged error picture or copied text.

![image](https://cloud.githubusercontent.com/assets/980757/18224737/b98ec6b0-71d7-11e6-8460-1b36b2a3f200.png)

**Comment by shanalikhan** [comment] 2016-09-04 19:02
Have you tried reset settings and try upload again?
Please update

**Comment by ksnyde** [comment] 2016-09-04 19:53
yes several times I'm afraid

**Comment by Seppone** [comment] 2016-09-05 12:44
**Visual Studio Code Version :** [ 1.4.0]
**Code Sync Settings Version :** [ 2.2.3]
**Operating System :** [ Win7 64-Bit]

same problem here

**Comment by shanalikhan** [comment] 2016-09-05 13:12
@Seppone yes there is one issue already opened [#60](https://github.com/shanalikhan/code-settings-sync/issues/60) there is still some works needs to be done to support for proxy. You need to test it out manually and send me a pull request 
@ksnyde are you also using proxy ?

**Comment by ksnyde** [comment] 2016-09-05 13:23
no proxy for me

**Comment by shanalikhan** [comment] 2016-09-17 09:37
@ksnyde can you update and paste the response from the console log 
Log JSON will shown after Response from Github IS

**Comment by ksnyde** [comment] 2016-09-17 11:34
Here's an image from the running the update (I'd cleared beforehand so this should exclusively related to trying update). I ran it the first time and it asked for my key, the second time it didn't ask but in both cases it produced results similar to this in the console:

![image](https://cloud.githubusercontent.com/assets/980757/18607915/9720b466-7cd2-11e6-82cb-65f2cf26cd45.png)

Does this help? I didn't find any JSON output in the console.

**Comment by shanalikhan** [comment] 2016-09-17 14:24
This is due to invalid token
Possible duplicate of (https://github.com/shanalikhan/code-settings-sync/issues/69)

**Closed by shanalikhan** 2016-09-17 14:24 UTC
Labels: bug, working on it

**Comment by ksnyde** [comment] 2016-09-17 20:05
so if I update should this now work?
