### ISSUE TITLE
Export to local file

### ISSUE THREAD

**Issue by mrpotatoes** [shanalikhan/code-settings-sync#663] opened 2018-10-02 01:57 UTC
💡 **Is your feature request related to a problem? Please describe.**
I work at a company where github is completely blocked and I cannot automatically create gists. Halting the use of this product entirely.

💡 **Describe the solution you'd like**
Allow the download and upload of files manually so that I can still perform all the same actions but the setup is by hand.

**Comment by shanalikhan** [comment] 2018-10-02 09:39
Duplicate of #256

**Closed by shanalikhan** 2018-10-02 09:39 UTC
