### ISSUE TITLE
it's take too long at startup

### ISSUE THREAD

**Issue by stupidinabox** [shanalikhan/code-settings-sync#488] opened 2018-01-27 07:46 UTC
- Extension Name: code-settings-sync
- Extension Version: 2.8.7
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.19.3

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 279,
		"activateCallTime": 5,
		"activateResolvedTime": 72,
		"activationEvent": "*"
	}
}
```

**Comment by shanalikhan** [comment] 2018-01-27 07:47
Duplicate of #472

**Closed by shanalikhan** 2018-01-27 07:47 UTC
