### ISSUE TITLE
Ability to sync global-snippets

### ISSUE THREAD

**Issue by trsdln** [shanalikhan/code-settings-sync#498] opened 2018-02-15 10:02 UTC
**Visual Studio Code Version :** [ 1.20.1 ]
**Code Settings Sync Version :** [ 2.8.7 ]

It would be great to be able to sync *.global-snippets introduced at VS Code v1.20.1.

**Comment by shanalikhan** [comment] 2018-02-15 16:14
Duplicate of #491

**Closed by shanalikhan** 2018-02-15 16:14 UTC
