### ISSUE TITLE
Extension ignores VS Code language

### ISSUE THREAD

**Issue by inliquid** [shanalikhan/code-settings-sync#1017] opened 2019-08-21 20:40 UTC
Extension ignores system language, for example, VS Code language set to english, but there is such a mess with Russian:
![изображение](https://user-images.githubusercontent.com/6797881/63466905-f0625900-c46c-11e9-94a2-d51a50624720.png)

**Comment by shanalikhan** [comment] 2019-08-22 06:49
Duplicate of #987

**Closed by shanalikhan** 2019-08-22 06:49 UTC
