### ISSUE TITLE
restore setting in fresh new machine, and command "python:xxxxx" not found

### ISSUE THREAD

**Issue by b10102016** [shanalikhan/code-settings-sync#560] opened 2018-06-03 12:35 UTC
**Describe the bug**
I have a fresh new machine and I want to use this extension to restore my setting from gist.
After I Downloaded my setting from gist, I can't use python extention.
Ctrl + shift + p and all python command can't work.
It always say command "python:xxxxx" not found

What I can do is only remove .vscode directory, and reinstall my extension manually

**Visual Studio Code Version :** [ Version 1.23.1 ]
**Code Settings Sync Version :** [ 2.9.2 ]
**Operating System :** [ Ubuntu 18.04 ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ No ]
**Gist Id:** [ ef123ed3be0a63b9b082160af4516027 ]

**To Reproduce**
1. Install fresh new vscode
2. Download setting
3. Ctrl + Shift + P > python: xxxxx
4. See error  command "python:xxxx" not found

**Expected behavior**
Work normal

**Console Error Log**
If applicable, add screenshots or paste the console log from developer console of VSCode.

**Additional context**
There are some people having same problem
Please take a look at this [issue](https://github.com/Microsoft/vscode-python/issues/781)
This man ,SiqingYu, had the same problem. Thanks

**Comment by shanalikhan** [comment] 2018-06-08 10:14
Ok Thanks, let me figure it out.

**Comment by shanalikhan** [comment] 2018-06-19 19:49
Duplicate of #566

**Comment by shanalikhan** [comment] 2018-06-19 19:50
Lets track it there. =)

**Closed by shanalikhan** 2018-06-19 19:49 UTC

**Comment by b10102016** [comment] 2018-06-20 08:52
Ok thanks for helping
