### ISSUE TITLE
customize which extensions are saved to the gist ?

### ISSUE THREAD

**Issue by vesper8** [shanalikhan/code-settings-sync#504] opened 2018-03-03 00:51 UTC
I have a special use case. I have my installation which has about 50 extensions, some of them are front-end related and some are back-end related

now I want to make it easy for me to share a partial list of my extensions with freelancers so they can easily start working, but if I share it with a front-end freelancer then he/she doesn't need all the back-end extensions

Now I could edit the gist manually.. but this is not ideal. In a perfect world there would be a way to view the list of extensions and select which ones should be uploaded to the gist.. with checkboxes if that's possible?

Something else that would work is if there was some kind of extension filter. For example for one gist I would filter out anything that includes the keywords "php" and "laravel"

Well maybe this is too much work but if you can think of a simple way to do it, it would be useful. For now I will just edit the gist manually

**Comment by shanalikhan** [comment] 2018-03-03 22:18
Added in backlog.
Will work on it once other issues are done. 
PR is welcome till then if anyone can do that.

**Comment by shanalikhan** [comment] 2018-03-04 15:42
Duplicate of #421

**Closed by shanalikhan** 2018-03-04 15:42 UTC
Labels: feature-request
