### ISSUE TITLE
support syncLocalSettings.json or github private repository

### ISSUE THREAD

**Issue by lizhuangs** [shanalikhan/code-settings-sync#916] opened 2019-06-19 13:39 UTC
💡 **support save config in syncLocalSettings.json or sync with github private repository**
the gist can be seen by anyone who get the gist url.
It is unsafe.
hope for support to save some secret configs  like `oauth token`,`password` in syncLocalSettings.json or sync with github private repository.may be syncLocalSettings.json is simple to implement,but the private  repository is better experience.

**Comment by shanalikhan** [comment] 2019-06-19 16:57
Duplicate of #413

**Closed by shanalikhan** 2019-06-19 16:57 UTC
