### ISSUE TITLE
Cannot sync Snippet

### ISSUE THREAD

**Issue by nguyendviet** [shanalikhan/code-settings-sync#951] opened 2019-07-09 14:45 UTC
🐛 **Describe the bug**  
After uploading the gist, there's no Snippet folder. Related to #612 but it's CLOSED.

🌴 **Visual Studio Code Version :** [ Version 1.36.0 ] 
🌴 **Code Settings Sync Version :** [ 3.3.1 ] 
🌴 **Operating System :** [ MacOS Version 10.14.5 ] 
🌴 **Occurs On:** [Upload ]
🌴 **Proxy Enabled:** [ No ]

📰 **To Reproduce**
1. Follow the manual [here](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)
2. Don't see the Snippet folder. Only:
- cloudSettings
- extensions.json
- keybindings.json
- keybindingsMac.json
- settings.json

💪 **Expected behavior**
Gist should have Snippet folder.

📺 **Console Error Log** 
No error
```bash
--------------------
Files Uploaded:
  extensions.json > extensions.json
  keybindings.json > keybindingsMac.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.
```

```bash
$ cat syncLocalSettings.json 
{
    "ignoreUploadFiles": [
        "state.*",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock",
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 331,
    "token": MY_TOKEN,
    "downloadPublicGist": false,
    "supportedFileExtensions": [
        "json",
        "code-snippets"
    ],
    "openTokenLink": true,
    "disableUpdateMessage": false,
    "lastUpload": "2019-07-09T14:21:23.679Z",
    "lastDownload": null,
    "githubEnterpriseUrl": null,
    "askGistName": false,
    "customFiles": {},
    "hostName": null,
    "universalKeybindings": false
}
```

**Comment by shanalikhan** [comment] 2019-07-09 16:28
Duplicate of #927

**Comment by shanalikhan** [comment] 2019-07-09 16:28
It will be fixed in next update. Thanks

**Closed by shanalikhan** 2019-07-09 16:28 UTC
