### ISSUE TITLE
Auto upload not working

### ISSUE THREAD

**Issue by arnohovhannisyan** [shanalikhan/code-settings-sync#804] opened 2019-03-23 22:22 UTC
🐛 **Describe the bug**  
Auto upload is not initiated when changing settings or installing/removing extensions. To be clear, I have turned on autoUpload in the settings, restarted, and it still didn't work. I have also tried this on another machine to make sure that it wasn't just my computer acting up and the issue did not go away on that one either.

🌴 **Visual Studio Code Version :** [ 1.32.3 ] 
🌴 **Code Settings Sync Version :** [ 3.2.7 ] 
🌴 **Standard or Insiders :** [ Standard ]
🌴 **Operating System :** [ Windows 10 x64 1809 ] 
🌴 **Occurs On:** [ Upload ]
🌴 **Proxy Enabled:** [ No ]

📰 **To Reproduce**
1. Go to 'settings.json'
2. Turn on auto upload and restart vs code
2. Change any setting
3. Watch as nothing happens
4. Check the gist to see that it hasn't been updated

💪 **Expected behavior**
Settings will be automatically uploaded when changes are made.

📺  **Additional context**
Found this in the code, and I think it might be the cause of the issue:
![image](https://user-images.githubusercontent.com/25834068/54872301-29dc4e80-4d7f-11e9-97a6-8ddf4208f643.png)

**Comment by shanalikhan** [comment] 2019-03-24 15:01
Thanks, i will look into it.

**Comment by shanalikhan** [comment] 2019-03-24 18:26
Duplicate of #801

**Closed by shanalikhan** 2019-03-24 18:26 UTC
