### ISSUE TITLE
Settings sync doesn't install any extension.

### ISSUE THREAD

**Issue by gquittet** [shanalikhan/code-settings-sync#649] opened 2018-09-19 07:11 UTC
🐛 **Describe the bug**  
Settings sync doesn't install any extension when it download my settings.

🌴 **Visual Studio Code Version :** 1.27.2 (VSCode OSS)
🌴 **Code Settings Sync Version :** 3.1.2
🌴 **Operating System :** ArchLinux
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
1. Install as a clean install of VSCode
2. Enter token
3. Enter Gist ID
4. Settings Sync download all the files but doesn't install any extensions.

💪 **Expected behavior**

📺 **Console Error Log** 
[Extension Host] Sync : /usr/lib/electron/electron

```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.1.2
--------------------
GitHub Token: 
GitHub Gist: 
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  settings.json > settings.json
  vsicons.settings.json > vsicons.settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```

**Comment by shanalikhan** [comment] 2018-09-19 08:31
> Gist Id: [ ID_HERE ]

Share your gist ID

**Comment by shanalikhan** [comment] 2018-09-20 10:09
I need the GIST ID to check.
Also post the developer console logs

**Comment by leoryu** [comment] 2018-09-23 08:33
> 
> 
> I need the GIST ID to check.
> Also post the developer console logs
I have the same problem. This is my gist ID:
gist: d71aa3d4f75329d3b760da1e7ba17c98

**Comment by leoryu** [comment] 2018-09-23 08:33
I have the same problem.
My GIST ID is:
d71aa3d4f75329d3b760da1e7ba17c98
@shanalikhan

**Comment by Brozgar** [comment] 2018-09-23 16:42
Same issues here on Linux Mint 32bit. No errors, it says "done" after the download, but no extensions are installed even after a restart. Also it doesn't apply settings. Can't share the gist, because some settings might contain sensitive info.

**Comment by qubidt** [comment] 2018-09-23 20:05
Possibly related to #331? VSCode OSS uses different directory names

**Comment by Brozgar** [comment] 2018-09-24 01:37
> Possibly related to #331? VSCode OSS uses different directory names



> Possibly related to #331? VSCode OSS uses different directory names

It looks like. I would suggest expanding advanced options so that people could set their paths manually there. Not the best solution, but should be enough for a start. This issue seems to be very old.

**Comment by shanalikhan** [comment] 2018-09-24 08:37
Duplicate of #331

**Closed by shanalikhan** 2018-09-24 08:37 UTC

**Comment by Alexcastr** [comment] 2022-10-30 18:42
i have same issue, what could be the solution ?

**Comment by pankaj485** [comment] 2022-12-30 12:24
Hey just came across the same issue. I can't get the extensions but in the sync history it's history. Tried between widows10 and ubuntu20.04

**Comment by 95lux** [comment] 2023-11-01 16:16
any updates on this?

**Comment by cabiamdos** [comment] 2024-04-20 23:21
yes, here is my output: 

```
--------------------
Done.CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.4.3
--------------------
GitHub Token: gho_**********
GitHub Gist: eff9d50ce1575e6982272851693bbe1f
GitHub Gist Type: Public

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  History\-1009c057\entries.json > History\-1009c057\entries.json
  History\-1011f0c7\entries.json > History\-1011f0c7\entries.json
  History\-10183b56\entries.json > History\-10183b56\entries.json
  History\-10ad0c64\entries.json > History\-10ad0c64\entries.json
  History\-1105e8a0\entries.json > History\-1105e8a0\entries.json
  History\-1139db3a\entries.json > History\-1139db3a\entries.json
  History\-11555437\entries.json > History\-11555437\entries.json
  History\-1155c5a\entries.json > History\-1155c5a\entries.json
  History\-11e123f6\entries.json > History\-11e123f6\entries.json
  History\-125460ca\entries.json > History\-125460ca\entries.json
  History\-1257b4a5\entries.json > History\-1257b4a5\entries.json
  History\-1261c1cc\entries.json > History\-1261c1cc\entries.json
  History\-12f0b3d4\entries.json > History\-12f0b3d4\entries.json
  History\-132db9e8\entries.json > History\-132db9e8\entries.json
  History\-132db9e8\zChB.json > History\-132db9e8\zChB.json
  History\-1333653c\entries.json > History\-1333653c\entries.json
  History\-13e70259\entries.json > History\-13e70259\entries.json
  History\-13f1362\entries.json > History\-13f1362\entries.json
  History\-1429995e\entries.json > History\-1429995e\entries.json
  History\-1453e330\entries.json > History\-1453e330\entries.json
  History\-14c989dd\entries.json > History\-14c989dd\entries.json
  History\-1511c851\entries.json > History\-1511c851\entries.json
  History\-1529a264\entries.json > History\-1529a264\entries.json
  History\-1552dc68\entries.json > History\-1552dc68\entries.json
  History\-15a41e13\entries.json > History\-15a41e13\entries.json
  History\-163b2755\entries.json > History\-163b2755\entries.json
  History\-16597ed9\entries.json > History\-16597ed9\entries.json
  History\-16c979bb\entries.json > History\-16c979bb\entries.json
  History\-170e2bce\entries.json > History\-170e2bce\entries.json
  History\-1710c796\entries.json > History\-1710c796\entries.json
  History\-17133afb\entries.json > History\-17133afb\entries.json
  History\-175a9909\entries.json > History\-175a9909\entries.json
  History\-175b0d68\entries.json > History\-175b0d68\entries.json
  History\-175b81c7\entries.json > History\-175b81c7\entries.json
  History\-175c6a85\entries.json > History\-175c6a85\entries.json
  History\-175cdee4\entries.json > History\-175cdee4\entries.json
  History\-176ca5a3\entries.json > History\-176ca5a3\entries.json
  History\-1772b7fe\entries.json > History\-1772b7fe\entries.json
  History\-17b23458\entries.json > History\-17b23458\entries.json
  History\-17e7729b\entries.json > History\-17e7729b\entries.json
  History\-180662b7\2BPV.json > History\-180662b7\2BPV.json
  History\-180662b7\GWMt.json > History\-180662b7\GWMt.json
  History\-180662b7\HFTh.json > History\-180662b7\HFTh.json
  History\-180662b7\JkR9.json > History\-180662b7\JkR9.json
  History\-180662b7\P2Uw.json > History\-180662b7\P2Uw.json
  History\-180662b7\Y5w3.json > History\-180662b7\Y5w3.json
  History\-180662b7\entries.json > History\-180662b7\entries.json
  History\-180662b7\l9Y9.json > History\-180662b7\l9Y9.json
  History\-180662b7\ymmL.json > History\-180662b7\ymmL.json
  History\-188e6d55\entries.json > History\-188e6d55\entries.json
  History\-18a1ce7a\entries.json > History\-18a1ce7a\entries.json
  History\-18a37ecd\entries.json > History\-18a37ecd\entries.json
  History\-18efb2ff\entries.json > History\-18efb2ff\entries.json
  History\-19029f50\entries.json > History\-19029f50\entries.json
  History\-190e1958\entries.json > History\-190e1958\entries.json
  History\-1915b540\entries.json > History\-1915b540\entries.json
  History\-193734f\Agae.json > History\-193734f\Agae.json
  History\-193734f\AvY1.json > History\-193734f\AvY1.json
  History\-193734f\entries.json > History\-193734f\entries.json
  History\-1941ea51\entries.json > History\-1941ea51\entries.json
  History\-1941eb11\entries.json > History\-1941eb11\entries.json
  History\-19531e9b\entries.json > History\-19531e9b\entries.json
  History\-1996e08c\entries.json > History\-1996e08c\entries.json
  History\-19aa179f\entries.json > History\-19aa179f\entries.json
  History\-19ce16c5\entries.json > History\-19ce16c5\entries.json
  History\-19f447c6\entries.json > History\-19f447c6\entries.json
  History\-1a55e565\entries.json > History\-1a55e565\entries.json
  History\-1a87b0bc\entries.json > History\-1a87b0bc\entries.json
  History\-1a9fa265\entries.json > History\-1a9fa265\entries.json
  History\-1ac987d0\entries.json > History\-1ac987d0\entries.json
  History\-1b0d8ebb\entries.json > History\-1b0d8ebb\entries.json
  History\-1b61d658\entries.json > History\-1b61d658\entries.json
  History\-1b863751\entries.json > History\-1b863751\entries.json
  History\-1b9412f4\entries.json > History\-1b9412f4\entries.json
  History\-1babab99\entries.json > History\-1babab99\entries.json
  History\-1bb978e3\entries.json > History\-1bb978e3\entries.json
  History\-1beb944b\entries.json > History\-1beb944b\entries.json
  History\-1bfe64c0\entries.json > History\-1bfe64c0\entries.json
  History\-1c37bb59\entries.json > History\-1c37bb59\entries.json
  History\-1cbfc455\entries.json > History\-1cbfc455\entries.json
  History\-1d309aae\entries.json > History\-1d309aae\entries.json
  History\-1d5c99ec\entries.json > History\-1d5c99ec\entries.json
  History\-1d6d6bae\entries.json > History\-1d6d6bae\entries.json
  History\-1d97cf50\entries.json > History\-1d97cf50\entries.json
  History\-1dc08ff2\entries.json > History\-1dc08ff2\entries.json
  History\-1dd04769\entries.json > History\-1dd04769\entries.json
  History\-1dd316b1\entries.json > History\-1dd316b1\entries.json
  History\-1e2d28ce\3U2H.json > History\-1e2d28ce\3U2H.json
  History\-1e2d28ce\Hlsy.json > History\-1e2d28ce\Hlsy.json
  History\-1e2d28ce\Wgee.json > History\-1e2d28ce\Wgee.json
  History\-1e2d28ce\entries.json > History\-1e2d28ce\entries.json
  History\-1e3320b\entries.json > History\-1e3320b\entries.json
  History\-1e44325f\entries.json > History\-1e44325f\entries.json
  History\-1e8e17fa\entries.json > History\-1e8e17fa\entries.json
  History\-1e919270\entries.json > History\-1e919270\entries.json
  History\-1ec83997\entries.json > History\-1ec83997\entries.json
  History\-1f0e0cca\entries.json > History\-1f0e0cca\entries.json
  History\-1f1bbd39\entries.json > History\-1f1bbd39\entries.json
  History\-1f98d886\entries.json > History\-1f98d886\entries.json
  History\-1fb0ce95\entries.json > History\-1fb0ce95\entries.json
  History\-1fcd8c4f\entries.json > History\-1fcd8c4f\entries.json
  History\-20031f16\entries.json > History\-20031f16\entries.json
  History\-2012e6a4\entries.json > History\-2012e6a4\entries.json
  History\-202255c6\entries.json > History\-202255c6\entries.json
  History\-206086a6\entries.json > History\-206086a6\entries.json
  History\-2063f090\entries.json > History\-2063f090\entries.json
  History\-20724f1c\entries.json > History\-20724f1c\entries.json
  History\-212a6e73\entries.json > History\-212a6e73\entries.json
  History\-213a7020\8oxI.json > History\-213a7020\8oxI.json
  History\-213a7020\PnDY.json > History\-213a7020\PnDY.json
  History\-213a7020\entries.json > History\-213a7020\entries.json
  History\-213a7020\j5Bi.json > History\-213a7020\j5Bi.json
  History\-213a7020\ok2d.json > History\-213a7020\ok2d.json
  History\-213a7020\wOfj.json > History\-213a7020\wOfj.json
  History\-215e2b51\entries.json > History\-215e2b51\entries.json
  History\-21609bc7\entries.json > History\-21609bc7\entries.json
  History\-2218d62d\entries.json > History\-2218d62d\entries.json
  History\-22390eea\entries.json > History\-22390eea\entries.json
  History\-2262cd4f\entries.json > History\-2262cd4f\entries.json
  History\-228ddd23\entries.json > History\-228ddd23\entries.json
  History\-2296f041\entries.json > History\-2296f041\entries.json
  History\-22d0bf1\entries.json > History\-22d0bf1\entries.json
  History\-2303ea30\entries.json > History\-2303ea30\entries.json
  History\-23594326\entries.json > History\-23594326\entries.json
  History\-23a727b6\entries.json > History\-23a727b6\entries.json
  History\-23b2aa52\entries.json > History\-23b2aa52\entries.json
  History\-23dd59f7\entries.json > History\-23dd59f7\entries.json
  History\-23e75a0c\entries.json > History\-23e75a0c\entries.json
  History\-24335068\entries.json > History\-24335068\entries.json
  History\-24454010\entries.json > History\-24454010\entries.json
  History\-24554fef\entries.json > History\-24554fef\entries.json
  History\-24a76055\entries.json > History\-24a76055\entries.json
  History\-24f02f88\entries.json > History\-24f02f88\entries.json
  History\-250f5a83\entries.json > History\-250f5a83\entries.json
  History\-2512c84c\entries.json > History\-2512c84c\entries.json
  History\-2572dc6c\entries.json > History\-2572dc6c\entries.json
  History\-2598be31\entries.json > History\-2598be31\entries.json
  History\-25a07902\entries.json > History\-25a07902\entries.json
  History\-25bb1a1e\entries.json > History\-25bb1a1e\entries.json
  History\-25d75a87\entries.json > History\-25d75a87\entries.json
  History\-25d7cee6\entries.json > History\-25d7cee6\entries.json
  History\-2611a7ff\entries.json > History\-2611a7ff\entries.json
  History\-26321aa7\entries.json > History\-26321aa7\entries.json
  History\-267f7569\entries.json > History\-267f7569\entries.json
  History\-26d400ad\entries.json > History\-26d400ad\entries.json
  History\-26e2cf8d\entries.json > History\-26e2cf8d\entries.json
  History\-271e163e\entries.json > History\-271e163e\entries.json
  History\-272a2083\entries.json > History\-272a2083\entries.json
  History\-273f3a51\entries.json > History\-273f3a51\entries.json
  History\-27849694\entries.json > History\-27849694\entries.json
  History\-278744fc\BkiA.json > History\-278744fc\BkiA.json
  History\-278744fc\QiIT.json > History\-278744fc\QiIT.json
  History\-278744fc\entries.json > History\-278744fc\entries.json
  History\-279b6357\entries.json > History\-279b6357\entries.json
  History\-27bb69cb\entries.json > History\-27bb69cb\entries.json
  History\-27e6eeb4\entries.json > History\-27e6eeb4\entries.json
  History\-28040c9c\entries.json > History\-28040c9c\entries.json
  History\-2820dff0\entries.json > History\-2820dff0\entries.json
  History\-2870780a\entries.json > History\-2870780a\entries.json
  History\-28987bb\entries.json > History\-28987bb\entries.json
  History\-289c00c5\entries.json > History\-289c00c5\entries.json
  History\-29336272\entries.json > History\-29336272\entries.json
  History\-29419941\entries.json > History\-29419941\entries.json
  History\-29574e03\entries.json > History\-29574e03\entries.json
  History\-295d190a\entries.json > History\-295d190a\entries.json
  History\-299054cf\entries.json > History\-299054cf\entries.json
  History\-29dd1554\entries.json > History\-29dd1554\entries.json
  History\-2a216e2a\entries.json > History\-2a216e2a\entries.json
  History\-2a775623\entries.json > History\-2a775623\entries.json
  History\-2a92f678\entries.json > History\-2a92f678\entries.json
  History\-2aa8914a\entries.json > History\-2aa8914a\entries.json
  History\-2acad5d6\7V5X.json > History\-2acad5d6\7V5X.json
  History\-2acad5d6\entries.json > History\-2acad5d6\entries.json
  History\-2b38883c\entries.json > History\-2b38883c\entries.json
  History\-2b4b2146\entries.json > History\-2b4b2146\entries.json
  History\-2b4b95a5\entries.json > History\-2b4b95a5\entries.json
  History\-2b4c0a04\entries.json > History\-2b4c0a04\entries.json
  History\-2b4c7e63\entries.json > History\-2b4c7e63\entries.json
  History\-2b6d8b3a\entries.json > History\-2b6d8b3a\entries.json
  History\-2b7b1450\entries.json > History\-2b7b1450\entries.json
  History\-2bd3d53f\entries.json > History\-2bd3d53f\entries.json
  History\-2be627a7\entries.json > History\-2be627a7\entries.json
  History\-2c00643\entries.json > History\-2c00643\entries.json
  History\-2c1788bb\entries.json > History\-2c1788bb\entries.json
  History\-2c1af451\entries.json > History\-2c1af451\entries.json
  History\-2c726ae2\entries.json > History\-2c726ae2\entries.json
  History\-2c7c4b9f\entries.json > History\-2c7c4b9f\entries.json
  History\-2c7eb0b5\entries.json > History\-2c7eb0b5\entries.json
  History\-2c7f2514\entries.json > History\-2c7f2514\entries.json
  History\-2c7f9973\entries.json > History\-2c7f9973\entries.json
  History\-2cc4ae24\entries.json > History\-2cc4ae24\entries.json
  History\-2cc5a0ac\entries.json > History\-2cc5a0ac\entries.json
  History\-2cc5bf6c\entries.json > History\-2cc5bf6c\entries.json
  History\-2ccffd71\entries.json > History\-2ccffd71\entries.json
  History\-2cd2f377\entries.json > History\-2cd2f377\entries.json
  History\-2cebd866\entries.json > History\-2cebd866\entries.json
  History\-2d4a95a6\entries.json > History\-2d4a95a6\entries.json
  History\-2d6c832f\entries.json > History\-2d6c832f\entries.json
  History\-2d6dd050\entries.json > History\-2d6dd050\entries.json
  History\-2da984d2\6QXX.json > History\-2da984d2\6QXX.json
  History\-2da984d2\entries.json > History\-2da984d2\entries.json
  History\-2ddec60b\entries.json > History\-2ddec60b\entries.json
  History\-2de65146\entries.json > History\-2de65146\entries.json
  History\-2debe86c\entries.json > History\-2debe86c\entries.json
  History\-2e18f00f\entries.json > History\-2e18f00f\entries.json
  History\-2ed7b665\entries.json > History\-2ed7b665\entries.json
  History\-2f15c861\entries.json > History\-2f15c861\entries.json
  History\-2f174609\entries.json > History\-2f174609\entries.json
  History\-2f8c5276\entries.json > History\-2f8c5276\entries.json
  History\-2fac3bb9\entries.json > History\-2fac3bb9\entries.json
  History\-2fb413eb\entries.json > History\-2fb413eb\entries.json
  History\-305e047e\entries.json > History\-305e047e\entries.json
  History\-305eed3c\entries.json > History\-305eed3c\entries.json
  History\-30a5ce31\entries.json > History\-30a5ce31\entries.json
  History\-30afdc28\0AHM.json > History\-30afdc28\0AHM.json
  History\-30afdc28\3kDI.json > History\-30afdc28\3kDI.json
  History\-30afdc28\6gsx.json > History\-30afdc28\6gsx.json
  History\-30afdc28\AnAu.json > History\-30afdc28\AnAu.json
  History\-30afdc28\Eijs.json > History\-30afdc28\Eijs.json
  History\-30afdc28\IdMC.json > History\-30afdc28\IdMC.json
  History\-30afdc28\Iq52.json > History\-30afdc28\Iq52.json
  History\-30afdc28\dNqU.json > History\-30afdc28\dNqU.json
  History\-30afdc28\dXx9.json > History\-30afdc28\dXx9.json
  History\-30afdc28\dwQV.json > History\-30afdc28\dwQV.json
  History\-30afdc28\entries.json > History\-30afdc28\entries.json
  History\-30afdc28\fN5e.json > History\-30afdc28\fN5e.json
  History\-30afdc28\hQZI.json > History\-30afdc28\hQZI.json
  History\-30afdc28\mxgE.json > History\-30afdc28\mxgE.json
  History\-30afdc28\qNvH.json > History\-30afdc28\qNvH.json
  History\-30afdc28\seoU.json > History\-30afdc28\seoU.json
  History\-30afdc28\yMDI.json > History\-30afdc28\yMDI.json
  History\-30afdc28\zOz2.json > History\-30afdc28\zOz2.json
  History\-31009d1f\entries.json > History\-31009d1f\entries.json
  History\-310cf5f9\entries.json > History\-310cf5f9\entries.json
  History\-31666f91\entries.json > History\-31666f91\entries.json
  History\-316fac9e\entries.json > History\-316fac9e\entries.json
  History\-31be5251\entries.json > History\-31be5251\entries.json
  History\-31d8f61f\entries.json > History\-31d8f61f\entries.json
  History\-31f03686\entries.json > History\-31f03686\entries.json
  History\-328cd64a\entries.json > History\-328cd64a\entries.json
  History\-32f590bd\entries.json > History\-32f590bd\entries.json
  History\-330dc963\entries.json > History\-330dc963\entries.json
  History\-334c6895\entries.json > History\-334c6895\entries.json
  History\-33cf974d\entries.json > History\-33cf974d\entries.json
  History\-33e4c605\entries.json > History\-33e4c605\entries.json
  History\-3493553b\entries.json > History\-3493553b\entries.json
  History\-349b0b5c\entries.json > History\-349b0b5c\entries.json
  History\-34ccc08b\entries.json > History\-34ccc08b\entries.json
  History\-3521ffd\entries.json > History\-3521ffd\entries.json
  History\-3535e9c4\entries.json > History\-3535e9c4\entries.json
  History\-3598bcba\entries.json > History\-3598bcba\entries.json
  History\-3599ea23\entries.json > History\-3599ea23\entries.json
  History\-35f35742\entries.json > History\-35f35742\entries.json
  History\-35fb35bc\entries.json > History\-35fb35bc\entries.json
  History\-360e43c8\entries.json > History\-360e43c8\entries.json
  History\-363e3f10\entries.json > History\-363e3f10\entries.json
  History\-366ea3df\entries.json > History\-366ea3df\entries.json
  History\-36dcdd39\entries.json > History\-36dcdd39\entries.json
  History\-3710f375\entries.json > History\-3710f375\entries.json
  History\-37469046\entries.json > History\-37469046\entries.json
  History\-374ddd00\entries.json > History\-374ddd00\entries.json
  History\-37556e1d\entries.json > History\-37556e1d\entries.json
  History\-3777a61f\entries.json > History\-3777a61f\entries.json
  History\-37828d79\entries.json > History\-37828d79\entries.json
  History\-37a21fcb\entries.json > History\-37a21fcb\entries.json
  History\-37b3b7d9\entries.json > History\-37b3b7d9\entries.json
  History\-37feb78b\entries.json > History\-37feb78b\entries.json
  History\-383c5b7b\entries.json > History\-383c5b7b\entries.json
  History\-383f5412\entries.json > History\-383f5412\entries.json
  History\-3869ad66\entries.json > History\-3869ad66\entries.json
  History\-38b2047b\entries.json > History\-38b2047b\entries.json
  History\-3a00ba11\entries.json > History\-3a00ba11\entries.json
  History\-3a18703a\entries.json > History\-3a18703a\entries.json
  History\-3a229040\entries.json > History\-3a229040\entries.json
  History\-3a8e5d76\entries.json > History\-3a8e5d76\entries.json
  History\-3a939050\entries.json > History\-3a939050\entries.json
  History\-3a9404af\entries.json > History\-3a9404af\entries.json
  History\-3aab5ebd\entries.json > History\-3aab5ebd\entries.json
  History\-3aca23b3\entries.json > History\-3aca23b3\entries.json
  History\-3adc67ff\entries.json > History\-3adc67ff\entries.json
  History\-3b52bc35\entries.json > History\-3b52bc35\entries.json
  History\-3b5541ff\entries.json > History\-3b5541ff\entries.json
  History\-3b8a587c\entries.json > History\-3b8a587c\entries.json
  History\-3c3bdb87\entries.json > History\-3c3bdb87\entries.json
  History\-3c3c0cdb\entries.json > History\-3c3c0cdb\entries.json
  History\-3c525b7b\entries.json > History\-3c525b7b\entries.json
  History\-3c830296\entries.json > History\-3c830296\entries.json
  History\-3c8b0fbb\entries.json > History\-3c8b0fbb\entries.json
  History\-3c9b7689\entries.json > History\-3c9b7689\entries.json
  History\-3ca68c09\entries.json > History\-3ca68c09\entries.json
  History\-3d31781f\entries.json > History\-3d31781f\entries.json
  History\-3d68b8b2\6Enb.json > History\-3d68b8b2\6Enb.json
  History\-3d68b8b2\RN6Z.json > History\-3d68b8b2\RN6Z.json
  History\-3d68b8b2\entries.json > History\-3d68b8b2\entries.json
  History\-3d8baade\entries.json > History\-3d8baade\entries.json
  History\-3dba4801\entries.json > History\-3dba4801\entries.json
  History\-3dec6cbf\entries.json > History\-3dec6cbf\entries.json
  History\-3ded9dba\entries.json > History\-3ded9dba\entries.json
  History\-3e4b22cc\entries.json > History\-3e4b22cc\entries.json
  History\-3e7100d1\entries.json > History\-3e7100d1\entries.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
```

As you can see "no extensions installed"

**Comment by mraveux** [comment] 2024-05-10 11:08
Same issue, same output as above.
Didn't find anything online and my gist is working on my mac but not on windows.
Any updates?

**Comment by mraveux** [comment] 2024-05-10 11:10
Same output as above.
Work on mac but not on windows, nothing sync.
Could not find anything online about this.
Any updates?

**Comment by bombseb** [comment] 2024-06-14 12:05
Hi there,

Same for me...
Unable to sync my config
