### ISSUE TITLE
Doesn't work (even show) on VSCodium 1.46.1

### ISSUE THREAD

**Issue by fabiocosta0305** [shanalikhan/code-settings-sync#1222] opened 2020-06-26 23:44 UTC
Can't even see it on Markplace at VSCodium 1.46.1

**Comment by heimdall0815** [comment] 2020-06-28 14:24
The reason for this is that VSCodium has changed from the VS-Code Marketplace to open-vsx.org with Version 1.46 (https://github.com/VSCodium/vscodium#extensions-and-the-marketplace, https://github.com/VSCodium/vscodium/issues/418).

In my opinion Settings Sync should also be published on open-vsx.org in the future (#1217).
But then there is still the problem that only extensions on the respective marketplace can be synchronized. 

For now, my recommendation is to change the marketplace from VSCodium back to marketplace.visualstudio.com. How to do this is described here: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace.

**Comment by shanalikhan** [comment] 2020-09-28 12:42
Duplicate of #1217

**Closed as completed by shanalikhan** 2020-09-28 12:42 UTC
