### ISSUE TITLE
Doesnt seem to download anything using VSCode Insiders 1.27-insider

### ISSUE THREAD

**Issue by thienedits** [shanalikhan/code-settings-sync#623] opened 2018-08-29 06:38 UTC
🐛 **Describe the bug**  
Am running both vscode and vscode insiders and want to load extensions into vscode insiders but they do not download

🌴 **Visual Studio Code Version :** [ 1.27-insider ] 
🌴 **Code Settings Sync Version :** [ 3.1.0] 
🌴 **Operating System :** [ Windows 10 ] 
🌴 **Occurs On:** [Download]
🌴 **Proxy Enabled:** [No ]
🌴 **Gist Id:** [ d489ebcc967f386153df9897660d2cd5 ]

📰 **To Reproduce**

💪 **Expected behavior**
Extensions to be downloaded

📺 **Console Error Log** 
![settings-notdownloaded](https://user-images.githubusercontent.com/2762906/44769976-4d0d8b00-ab1b-11e8-951e-5db8d59cb07a.PNG)

📺  **Additional context**

**Comment by shanalikhan** [comment] 2018-08-29 10:14
Duplicate of #618

**Closed** 2018-08-29 11:54 UTC
