### ISSUE TITLE
After downloading the settings.json, Some blank lines are added in settings.json

### ISSUE THREAD

**Issue by ladyrick** [shanalikhan/code-settings-sync#849] opened 2019-04-18 10:34 UTC
🐛 **Describe the bug**  
After downloading the settings.json, Some blank lines are added in settings.json.
But the settings.json in gist doesn't have these blank lines.
<img width="555" alt="屏幕快照 2019-04-18 18 25 27" src="https://user-images.githubusercontent.com/10379994/56355024-d9360500-6207-11e9-938d-718928d939be.png">
<img width="427" alt="屏幕快照 2019-04-18 18 28 52" src="https://user-images.githubusercontent.com/10379994/56355026-daffc880-6207-11e9-818d-1ce6513aa5c3.png">

gist here: https://gist.github.com/ladyrick/7fd8e8640f97f3143d505341d0ca228e

🌴 **Visual Studio Code Version :** 1.33.1
🌴 **Code Settings Sync Version :** 3.2.8
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** 
🌴 **Operating System :** macos mojave
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 7fd8e8640f97f3143d505341d0ca228e

📰 **To Reproduce**
1. add config `"sync.forceDownload": true`
2. cmd+shift+p, download the settings.
3. open settings.json
4. see the blank lines.

💪 **Expected behavior**

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab). 

📺  **Additional context**

**Comment by shanalikhan** [comment] 2019-04-18 10:44
Duplicate of #819

**Closed by shanalikhan** 2019-04-18 10:44 UTC
