### ISSUE TITLE
Open Show "Share ID" Message when new Public Gist is created

### ISSUE THREAD

**Issue by inwardmovement** [shanalikhan/code-settings-sync#977] opened 2019-07-22 09:29 UTC
Every time I open VSCode I have this notification:

> Sync: Share the Id with other extension users to share the settings.

How can I get rid of it permanently?

---------

🌴 **Visual Studio Code Version :** 1.36.1
🌴 **Code Settings Sync Version :** 3.4.1
🌴 **Standard or Insiders :** Standard
🌴 **Portable or Installed :** Installed
🌴 **OSS or Official Build :** Official Build
🌴 **Operating System :** Windows 10
🌴 **Occurs On:** "Sync uploaded successfully" (each sync)
🌴 **Proxy Enabled:** yes (I guess it's default VSC value, I didn't change anything)
🌴 **Gist Id:** 1b8b7717469c2648bacb57a1498dd84e

📰 **To Reproduce**
Modify a setting and upload settings

💪 **Expected behavior**
No notification at each sync

📺 **Console Error Log** 

![image](https://user-images.githubusercontent.com/9438102/61733374-f850af80-ad7f-11e9-8725-51736fa9e3fa.png)

📺  **Additional context**
[gist](https://gist.github.com/inwardmovement/1b8b7717469c2648bacb57a1498dd84e)

**Comment by shanalikhan** [comment] 2019-07-22 09:32
Can you post your Settings Sync global settings.

https://github.com/shanalikhan/code-settings-sync#global-settings

**Comment by inwardmovement** [comment] 2019-07-22 09:39
Here they are:

```
{
    "ignoreUploadFiles": [
        "state.vscdb",
        "state.vscdb.backup",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock",
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json",
        "state.*"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 340,
    "token": "[anonymized GitHub token]",
    "downloadPublicGist": false,
    "supportedFileExtensions": [
        "json",
        "code-snippets"
    ],
    "openTokenLink": true,
    "disableUpdateMessage": false,
    "lastUpload": "2019-06-27T09:13:31.267Z",
    "lastDownload": "2019-07-22T08:50:55.815Z",
    "githubEnterpriseUrl": null,
    "askGistName": false,
    "customFiles": {
        "projects.json": "C:\\Users\\arkay\\AppData\\Roaming\\Code\\User\\globalStorage\\alefragnani.project-manager\\projects.json",
        ".gitconfig": "C:\\Users\\arkay\\.gitconfig",
        "Greenshot.ini": "C:\\Users\\arkay\\AppData\\Roaming\\Greenshot\\Greenshot.ini",
        "default.svg": "C:\\Users\\arkay\\AppData\\Roaming\\Inkscape\\templates\\default.svg",
        ".editorconfig": "C:\\Users\\arkay\\Documents\\config\\.editorconfig",
        "autoload.bat": "C:\\Users\\arkay\\Documents\\config\\autoload.bat",
        "info.txt": "C:\\Users\\arkay\\Documents\\config\\info.txt",
        "remove-safely-icon.bat": "C:\\Users\\arkay\\Documents\\config\\remove-safely-icon.bat",
        "macros.ahk": "C:\\Users\\arkay\\Documents\\config\\macros.ahk",
        "run.ahk": "C:\\Users\\arkay\\Documents\\config\\run.ahk",
        "text.ahk": "C:\\Users\\arkay\\Documents\\config\\text.ahk"
    },
    "hostName": null,
    "universalKeybindings": false,
    "autoUploadDelay": 20
}
```

**Comment by inwardmovement** [comment] 2019-07-23 08:13
Fixed in `3.4.1`, thanks!

**Comment by inwardmovement** [comment] 2019-07-23 08:16
The notification showed again, sorry.

**Comment by shanalikhan** [comment] 2019-07-23 14:06
alright, pls post the gist ID

**Comment by inwardmovement** [comment] 2019-07-23 14:07
`1b8b7717469c2648bacb57a1498dd84e`

**Comment by shanalikhan** [comment] 2019-07-23 14:09
Can you post the details with the proper issue template so I can see the reproducing steps , happeing on upload / download etc. I have updated your main post so you can fill it up.

**Comment by inwardmovement** [comment] 2019-07-23 17:30
Ok thanks, done

**Comment by inwardmovement** [comment] 2019-08-09 08:05
Any news on this?
I think we should have a "Do not show again" option in the "gear" icon menu of the notification, like other notifications in VSCode.

**Comment by shanalikhan** [comment] 2019-08-09 10:25
I didn't find time to fix this issue. Hopefully, it will be fixed in upcoming releases. :)

**Comment by shanalikhan** [comment] 2019-08-21 12:10
It is fixed and released in new version.

**Closed by shanalikhan** 2019-08-21 12:10 UTC
Labels: fixed, improvement  ✨

**Comment by pcdevil** [comment] 2019-08-23 12:22
Hello,

Since the new release I see this message (but previously I wasn't). I see the checks on this changed in the last release:

Previously the condition looked at the `localConfig.publicGist` variable (see [L407](https://github.com/shanalikhan/code-settings-sync/commit/7c15602a36e11e5404457b36cf0d81029f18f18c#diff-488eefd69f8445c1b2e0259cad8f40ebR407)) but now just for optArgument.
But the way as the `optArgument` becomes _true_ is different (in terms of this check): if the incoming variable is _trueish_, the message will be showned, meanwhile previously it not just checked for _emptiness_, it checked for it's value too (see [L87-88](https://github.com/shanalikhan/code-settings-sync/commit/7c15602a36e11e5404457b36cf0d81029f18f18c#diff-488eefd69f8445c1b2e0259cad8f40ebR87-R88)).

Since I don't see the calling signature is changed (as of the [extension.ts L19-21](https://github.com/shanalikhan/code-settings-sync/commit/7c15602a36e11e5404457b36cf0d81029f18f18c#diff-45327f86d4438556066de133327f4ca2R19)) I would assume this is not how it should work?

I think reverting the modification in the sync.ts L407 would solve the issue, or a direct check on `optArgument`:
```diff
-          if (optArgument) {
+          if (optArgument === "publicGIST") {
```

What is your thoughts on this @shanalikhan?

**Comment by shanalikhan** [comment] 2019-08-23 12:31
yes are you right. I will place the check on `optArgument` value too. 

`localConfig.publicGist` can remain to `true` forever and user were seeing this message on every update. Now notification needs to be only appear when user creates new public gist. ( not on every upload on public gist, afterwards)

**Comment by pcdevil** [comment] 2019-08-23 12:38
Ohh I see! I missed that part of the code, sorry :)
