### ISSUE TITLE
Sync to simple file

### ISSUE THREAD

**Issue by EpeR1** [shanalikhan/code-settings-sync#1206] opened 2020-05-19 20:45 UTC
It would be a nice feature if we can choose a simple file to sync destination+source without/instead of Github.
This file can be easily shared with GoogleDirve, Dropbox, Nextcloud, FTP, or via e-mail.

Best Regards,
Eper

**Comment by rajeshpal007** [comment] 2020-07-01 03:43
This can be really good feature!

**Comment by shanalikhan** [comment] 2020-09-30 15:17
Duplicate of #256

**Closed as completed by shanalikhan** 2020-09-30 15:17 UTC
