### ISSUE TITLE
an option to exclude the extension enabled/disabled from the sync

### ISSUE THREAD

**Issue by WiliTest** [shanalikhan/code-settings-sync#1066] opened 2019-10-11 09:21 UTC
Because of CPU issue, I daily need to enable/disable some extension. I don't want it to be sync.

It would be great to be able to exclude this action from the sync.

it's not a duplicate of [Exclude Settings/Extensions from Sync](https://github.com/shanalikhan/code-settings-sync/issues/982) (it should work for any extension)

**Comment by shanalikhan** [comment] 2019-10-11 10:37
Duplicate of #143

**Comment by shanalikhan** [comment] 2019-10-11 10:42
There are two things
1. Disable extensions sync and allow Settings Sync not to upload extension data using the configurations
2. Customize the Extensions which you want to sync or exclude from there (https://github.com/shanalikhan/code-settings-sync/issues/982) 

If you want to configure Settings Sync for disabled extensions. It doesnt support at the moment.

**Closed as completed** 2019-10-14 09:12 UTC
