### ISSUE TITLE
Refactor sync.ts to support multiple storages

### ISSUE THREAD

**Issue by ccinelli** [shanalikhan/code-settings-sync#975] opened 2019-07-19 23:56 UTC
#256 and #413 would be easier to achieve if `sync.ts` used and abstract `storage` class that can be implemented to store and restore from GIST, GIT REPOS, LOCAL FILES, GOOGLE DRIVE etc.

Can you also please increasing coverage with the tests otherwise the risk of regressions is very high.

**Comment by shanalikhan** [comment] 2019-07-20 19:52
Duplicate of #935

**Closed by shanalikhan** 2019-07-20 19:52 UTC
