### ISSUE TITLE
Error when trying to sync from public gist. 

### ISSUE THREAD

**Issue by inorganik** [shanalikhan/code-settings-sync#816] opened 2019-04-01 16:23 UTC
🐛 **Describe the bug**  
1. Install Settings Sync extension
1. in cmd palette, type "sync: advanced options"
1. choose "download settings from public gist"
1. press alt + shift + D, it prompts you for gist ID
1. enter 9d2e13cc88ffb44230e13e4603d70679

I get the error: 

> TypeError: Cannot read property 'gists' of null
>     at module.exports.t.GitHubService.<anonymous>

🌴 **Visual Studio Code Version :** [ 1.32 ] 
🌴 **Code Settings Sync Version :** [ 3.2.6 ] 
🌴 **Standard or Insiders :** [ standard ] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ CentOS ] 
🌴 **Occurs On:** [Upload / Download / Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [ 9d2e13cc88ffb44230e13e4603d70679 ]

These steps 

📰 **To Reproduce**
Noted above

💪 **Expected behavior**
It should sync... 

📺 **Console Error Log** 
> TypeError: Cannot read property 'gists' of null
>     at module.exports.t.GitHubService.<anonymous>

📺  **Additional context**

**Comment by Fruxh** [comment] 2019-04-02 16:38
Same problem here...

**Comment by inorganik** [comment] 2019-04-02 16:41
Current workaround is to provide a github token. First you need to go to the command palette and type `sync: reset extension settings`.

**Comment by arnohovhannisyan** [comment] 2019-04-06 23:26
What is your token set to in syncLocalSettings.json?

**Comment by cerino-ligutom** [comment] 2019-04-09 18:52
> Current workaround is to provide a github token. First you need to go to the command palette and type `sync: reset extension settings`.

Just encountered this issue from a complete uninstall (deleting corresponding files as well from %appdata% and %userprofile%) then doing a fresh install due to VS Code being terribly slow for some reason and can confirm this works.

**Comment by shanalikhan** [comment] 2019-04-10 09:52
Can you guys, test on this build and let me know so i can release new version.

https://www.dropbox.com/s/beudbw0uqwt8ua2/code-settings-sync-3.2.8.vsix?dl=0

**Comment by FC-Jason** [comment] 2019-04-12 16:06
> Can you guys, test on this build and let me know so i can release new version.
> 
> https://www.dropbox.com/s/beudbw0uqwt8ua2/code-settings-sync-3.2.8.vsix?dl=0

The new one fixed the problem for me on MacOS Mojave 10.14.4. Thanks!

**Comment by inorganik** [comment] 2019-04-15 20:43
Worked for me on CentOS!

**Comment by cerino-ligutom** [comment] 2019-04-16 16:31
> Can you guys, test on this build and let me know so i can release new version.
> 
> https://www.dropbox.com/s/beudbw0uqwt8ua2/code-settings-sync-3.2.8.vsix?dl=0

Seems to be working fine on Windows 10 Pro 64 bit. Thanks!

**Comment by Gywem** [comment] 2019-04-17 05:14
I'm no longer having such error on my Ubuntu 18.10!

**Comment by shanalikhan** [comment] 2019-04-18 11:29
its fixed in `v3.2.9`

**Closed by shanalikhan** 2019-04-18 11:29 UTC
Labels: bug 🐛, fixed

**Comment by breitembach** [comment] 2019-04-19 01:21
Still Not Working Ubuntu 18.04 haha!

**Comment by Gywem** [comment] 2019-05-02 06:11
Now that I pay attention more on the issue, I'm no longer seeing the error mentioned on this issue, though strangely my extensions are not being installed on the editor. I just see them to be "fetched" and "installed" so quick, but at the end, these are not installed in vscode. If I use my token it goes fine. Could this be still related on fetching from public GIST?

**Comment by shanalikhan** [comment] 2019-05-02 10:36
@Gywem
Please create new issue with complete reproducing steps so i can reproduce and fix in upcoming version ( if there is a bug )
