### ISSUE TITLE
sync remove only uninstalled, not disabled, extensions?

### ISSUE THREAD

**Issue by rakkarage** [shanalikhan/code-settings-sync#534] opened 2018-04-14 22:59 UTC
**Visual Studio Code Version :** 1.23.0-insider
**Code Settings Sync Version :** 2.9.0
**Operating System :** Win10
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** b265edcb9ef1100fcf49b9caf7874953

Would it be possible to add a setting for syncing / not removing DISABLED addons?

"sync.removeExtensions": true,

This removes disabled and uninstalled extensions?

Seems like would be best if it saved disabled addons and saved the disabled state?

Else maybe another setting? sync.RemoveDisabledExtensions?

Please and thanks.

**Comment by shanalikhan** [comment] 2018-04-15 21:58
Great!
But low priority for me.
PR is welcome :) - I can help you if you want to work on it and release new version.

**Comment by alanaasmaa** [comment] 2018-05-04 16:48
I would love it also ! Just noticed i'm missing a lot of extensions.

It depends a lot on what i work on. And i prefer to only enable core extensions. All the other would be workspace specific.

**Comment by shanalikhan** [comment] 2018-05-06 21:13
Duplicate of #143

**Comment by shanalikhan** [comment] 2018-05-06 21:14
API limitation from Code side for now.
Feel free to discuss there.

**Closed by shanalikhan** 2018-05-06 21:13 UTC

**Comment by NatoBoram** [comment] 2019-12-09 20:06
There should be a big fat warning on the <kbd>Remove Extensions</kbd> setting that it'd uninstall extensions from absolutely everywhere if they're disabled inside even a single workspace.

Also, destructive actions shouldn't be allowed to be automated - a message should be displayed asking if removing this extension from this installation is okay, or if it should be added to ignored extensions.

I disabled some extensions in an Angular workspace and some others in a C# workspace - the result is I have no extensions installed for both workspaces.
