### ISSUE TITLE
Enhancement: option for alternate github location

### ISSUE THREAD

**Issue by rothskeller** [shanalikhan/code-settings-sync#150] opened 2016-11-28 12:42 UTC
Enhancement request:  please add an option to provide a different URL for GitHub, so that one may use a corporate installation of GitHub Enterprise rather than the default github.com.

**Comment by shanalikhan** [comment] 2016-11-28 17:44
Duplicate of https://github.com/shanalikhan/code-settings-sync/issues/67
I will work on it later on once i add other important features :), Feel Free to comment there

**Closed by shanalikhan** 2016-11-28 17:44 UTC
Labels: duplicate

**Comment by rothskeller** [comment] 2016-11-28 17:56
Sorry I missed the dup.
