### ISSUE TITLE
possible solution to resolve --user-data-dir and --extensions-dir (#869, #411, #331, and etc) 

### ISSUE THREAD

**Issue by jjangga0214** [shanalikhan/code-settings-sync#905] opened 2019-06-10 10:16 UTC
Hi, while using vscode as root on Kali linux with `--user-data-dir` (e.g. `code --user-data-dir /root/.config/vscode`), I faced an issue that code-settings-sync does not install extensions. 

It seems the problem is caused from the fact that there's no vscode API for an extenstion to detect `--user-data-dir` and `--extensions-dir`. I could also found issues like #869 and #411.

And if so, we don't know whether and when the API are to be provided. Therefore, I suggests a (possibly temporary) workaround. 

The idea is user provides environment variables like `$CODE_USER_DATA_DIR` or `$CODE_EXTENSIONS_DIR`. For instance, I could run `CODE_USER_DATA_DIR=/root/.config/vscode code --user-data-dir /root/.config/vscode`. 

To achieve that, we might abandon using `vscode.commands.executeCommand`, and replace it with cli.

#### v3.3.0 (line 221)
```ts
const name = ext.publisher + "." + ext.name; //extension identifier
await vscode.commands.executeCommand(
            "workbench.extensions.installExtension", name);
```

#### Suggestion (concept code) based on master (line 301)
```ts
const name = missExt.publisher + "." + missExt.name;
const extensionCli = `${myExt} 
${process.env.CODE_USER_DATA_DIR ? 
"--user-data-dir " + process.env.CODE_USER_DATA_DIR : "" } 
${process.env.CODE_EXTENSIONS_DIR ? 
"--extensions-dir " + process.env.CODE_EXTENSIONS_DIR : "" } 
--install-extension ${name}`;
exec(extensionCli, (err, stdout, stderr) => {
...
})
```

How do you think of the idea?

**Comment by arnohovhannisyan** [comment] 2019-06-10 10:24
@jjangga0214 The changes in v3.3.0 were necessary to support all versions of VSCode. Also, using the API to install extensions should completely fix this issue. Have you tried installing a build of v3.3.0 and trying that out?

**Comment by jjangga0214** [comment] 2019-06-10 10:53
@arnohovhannisyan Thanks for letting me know!
I currently use v3.2.9, and due to strange bug ( photo below ), couldn't run it locally.
![Screenshot from 2019-06-10 19-49-52](https://user-images.githubusercontent.com/28584151/59190950-0e802300-8bb9-11e9-85eb-4d79bb6e3057.png)
It'd be great anyway if I really can use it on my Kali when v3.3.0 becomes official.

**Comment by arnohovhannisyan** [comment] 2019-06-10 11:12
@jjangga0214 Try installing this VSIX: https://cdn.discordapp.com/attachments/549007146868539408/587599453708353566/code-settings-sync-3.2.9.vsix

If you don't know how: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by jjangga0214** [comment] 2019-06-10 14:39
@arnohovhannisyan Happy to see it works even on today! 
So, I guess #411 can be closed (if it's tested on windows 10).
Thank you :)

**Comment by shanalikhan** [comment] 2019-06-19 09:14
Duplicate of #411

**Closed by shanalikhan** 2019-06-19 09:14 UTC
