### ISSUE TITLE
Sync to the filesystem not a gist

### ISSUE THREAD

**Issue by frankhommers** [shanalikhan/code-settings-sync#573] opened 2018-06-14 21:39 UTC
I'd like to keep my settings where I like, not GitHub per se.

If I can sync to a folder on the file system, I can then in turn put it on my personal webdav (or google drive, one drive, dropbox etc).

Instead of setting up a Gist, just configure a folder.

**Comment by shanalikhan** [comment] 2018-06-15 06:54
Duplicate of #256

**Closed by shanalikhan** 2018-06-15 06:54 UTC
