### ISSUE TITLE
Older settings getting uploaded over newer

### ISSUE THREAD

**Issue by kbd** [shanalikhan/code-settings-sync#562] opened 2018-06-06 01:36 UTC
Older settings are getting automatically uploaded over newer settings.

I'm literally walking over to one computer (which I've recently installed a new extension on) and manually typing shift+cmd+p -> "Sync: Update / Upload Settings". By the time I can walk to the other computer, it's already uploaded *its* older settings over the newer ones and is not installing the new extension.

Check the gist revisions to watch them fighting over it within seconds.

**Visual Studio Code Version :** 1.23.1
**Code Settings Sync Version :** 2.9.2
**Operating System :** macOS 10.13.4
**Occurs On:** Upload
**Proxy Enabled:** No
**Gist Id:** https://gist.github.com/kbd/9c099110598e09bf6ecb597d7b27f4bd/revisions

**Comment by shanalikhan** [comment] 2018-06-06 07:05
is the auto upload / download turned on in any of your computer

**Comment by kbd** [comment] 2018-06-06 16:45
Yes both have auto upload/download set.

**Comment by shanalikhan** [comment] 2018-06-07 05:54
Duplicate of #396

**Comment by shanalikhan** [comment] 2018-06-07 05:54
Currently there is problem for auto download / upload.

**Closed by shanalikhan** 2018-06-07 05:54 UTC

**Comment by daften** [comment] 2018-10-23 21:37
@shanalikhan 

I don't think this is a real duplicate. In the other issue, it seems like a merge conflict for files. Here it seems like the newly downloaded settings from auto-download aren't actually uploaded. I have the same thing and basically my pc's are now playing ping-pong between two extensions. When I open it up, it uninstalls extension A and installs extension B. But I guess since extension B isn't installed by the time the upload starts, it still passes through extension A is installed and B isn't. So the next time I open the editor here or on another PC, it will install extension A and uninstall extension B. And it goes back and forth.
