### ISSUE TITLE
CPU usage and settings overwrite problems when auto upload is enabled.

### ISSUE THREAD

**Issue by serkanyersen** [shanalikhan/code-settings-sync#660] opened 2018-09-25 22:12 UTC
🐛 **Describe the bug**  
When auto upload is enabled, if you enable and disable `Touchbar` setting few times without restarting, whole thing goes crazy. CPU usage spikes and I even lost all settings once.

🌴 **Visual Studio Code Version :** 1.27.2 
🌴 **Code Settings Sync Version :** 1.6.9
🌴 **Operating System :** macos 10.12.6 sierra
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** Private

📰 **To Reproduce**
1) Enable Auto upload
2) Open settings, New GUI, not the JSON
3) Search for "touchbar"
4) click the checkbox, enable disable doesn't matter
5) It will ask to restart, click cancel.
6) Repeat 4. and 5. few times, you'll see all hell breaks loose.

💪 **Expected behavior**
CPU shouldn't spike, It probably shouldn't try to upload the setting, unless I click restart. and it tries to overwrite the settings somehow and lost everything once. IT shouldn't do that either.

📺 **Console Error Log** 
N/A

📺  **Additional context**
I bit more context here
https://github.com/Microsoft/vscode/issues/58671

**Comment by shanalikhan** [comment] 2018-09-26 09:07
Duplicate of #538

**Comment by shanalikhan** [comment] 2018-09-26 09:07
#396

**Closed by shanalikhan** 2018-09-26 09:07 UTC
