### ISSUE TITLE
Upload summary contains all extensions in "Extensions added"

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#637] opened 2018-09-07 08:10 UTC
Even if I don't add any extension during the current upload, I see this:

```
CODE SETTINGS SYNC UPLOAD SUMMARY
Version: 3.1.2
--------------------
GitHub Token: ...
GitHub Gist: ...
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Uploaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  launch.json > launch.json
  locale.json > locale.json
  settings.json > settings.json
  html.json > snippets|html.json
  typescript.json > snippets|typescript.json
  spellchecker.json > spellchecker.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  auto-rename-tag v0.0.15
  code-settings-sync v3.1.2
  crane v0.3.8
  dotenv v1.0.1
  EditorConfig v0.12.4
  ...
--------------------
Done.
```

The "Extensions Added" section is confusing, IMO, as I didn't really add any extension to the list. In this specific example, I've only changed one value in `settings.json`.

**Comment by shanalikhan** [comment] 2018-09-07 09:20
> The "Extensions Added" section is confusing. I've only changed one value in settings.json

Well, the scope would not be limited to extensions.

It should rather compare the remoate and local settings and show summary like ( for your case )
```
Files Updated:
settings.json > settings.json

Files Added:
None

Extensions Added:
None
```

**Comment by shanalikhan** [comment] 2018-09-07 09:20
Duplicate of #508

**Closed by shanalikhan** 2018-09-07 09:20 UTC
