### ISSUE TITLE
Snippet sync : different file path between Windows and OSX

### ISSUE THREAD

**Issue by thibka** [shanalikhan/code-settings-sync#1011] opened 2019-08-18 11:50 UTC
🐛 **Describe the bug**  
Can't sync snippets between Windows and macOS beceause they have different path name in the gist depending on the OS used to upload them.
For instance : 
When uploaded from a Windows machine : "snippets\javascript.json"
When uploaded from a Mac : "snippets|javascript.json"

🌴 **Visual Studio Code Version :** 1.37.1 
🌴 **Code Settings Sync Version :** 3.4.1
🌴 **Operating System :** Windows 10 - macOS 10.14.6
🌴 **Occurs On:** Upload / Download
🌴 **Gist Id:** 1fcd6674b290b3b624a0d4b6a0438103

📰 **To Reproduce**
1. Upload a snippet to the gist from a Windows machine
2. Upload a snippet to the gist from a Mac
3. Look at the gist content
4. See that they are two different snippets instead of one

💪 **Expected behavior**
Snippet sync working between Windows and Mac.

**Comment by shanalikhan** [comment] 2019-08-21 12:07
Duplicate of #993

**Closed by shanalikhan** 2019-08-21 12:07 UTC
