### ISSUE TITLE
Can't find correct data folders when using with VS Codium

### ISSUE THREAD

**Issue by dragonwocky** [shanalikhan/code-settings-sync#840] opened 2019-04-11 04:07 UTC
🐛 **Describe the bug**  
When attempting to install downloaded data the extension cannot find the correct data folder to put extensions/settings/keybindings in, runs into an error and gives up.

🌴 **Visual Studio Code Version :** 1.33.0
🌴 **Code Settings Sync Version :** 3.2.8
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** [VS Codium](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo) (OSS)
🌴 **Operating System :** Ubuntu 18.10
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** n/a

📰 **To Reproduce**
Steps to reproduce the behaviour:
1. Install VS Codium.
2. Install `shan.code-settings-sync`.
3. Press `CTRL + SHIFT + D`.
4. Input GitHub Personal Access Token & Gist ID.
5. See console for error message.

💪 **Expected behaviour**
The extension should successfully download and install the extensions/settings/keybindings I uploaded from my previous installation of VS Code, and if it cannot find the correct data folders then it should ask the user to configure the correct locations manually.

📺 **Console Error Log** 
![image](https://user-images.githubusercontent.com/16874139/55929598-cb5d0e80-5c60-11e9-93e6-1346eaee9d86.png)

📺  **Additional context**
The actual data folder locations are `~/.vscode-oss/extensions` and `~/.config/VSCodium`.

**Comment by dragonwocky** [comment] 2019-04-11 04:42
Deleted all the data folders and relaunched VS Codium to regenerate them, then reinstalled the extension and re-ran `CTRL + SHIFT + D`. This time, it downloaded the settings file successfully, but did not install any extensions (I'm still getting the same error).
![image](https://user-images.githubusercontent.com/16874139/55931130-b0da6380-5c67-11e9-8c24-e65d75ccdda5.png)

Although note that I believe I had been copy/pasting a copy of the Gist ID with a typo in it for the initial attempts, which is probably what caused the `HttpError` and meant the settings file did not download the first time.

**Comment by shanalikhan** [comment] 2019-04-11 10:55
Duplicate of #668

**Comment by dragonwocky** [comment] 2019-04-11 12:47
You sure? It's definitely similar, but according to the OP of #668 there were no errors in the console. Here there were. Maybe I'm missing something, but...

**Closed** 2019-04-14 23:07 UTC
