### ISSUE TITLE
TypeError: Cannot read property 'ignoreUploadFolders' of undefined

### ISSUE THREAD

**Issue by kkorus** [shanalikhan/code-settings-sync#874] opened 2019-05-04 13:35 UTC
🐛 
Hey, I'm getting this error in console when I'm trying to download my gist.

🌴 **Visual Studio Code Version :** [ 1.33.1 ] 
🌴 **Code Settings Sync Version :** [ 3.2.9 ] 
🌴 **Standard or Insiders :** [ Standard] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official Build] 
🌴 **Operating System :** [ Windows 10] 
🌴 **Occurs On:** [ Download  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ vscode-settings-sync]

📰 **To Reproduce**
1. press shift + alt + d
2. Put gist id
3. Open developer console and see error

![image](https://user-images.githubusercontent.com/2054009/57179809-e09d1580-6e79-11e9-8916-b4ed96636f83.png)

**Comment by PulsGarney** [comment] 2019-05-17 08:29
any idea on how to fix this? 😐

**Comment by shanalikhan** [comment] 2019-05-17 09:07
@arnohovhannisyan can you look into it?

**Comment by shanalikhan** [comment] 2019-05-17 09:11
@kkorus
Can you post your configurations in `User\syncLocalSettings.json` other than `token`

**Comment by DanTulovsky** [comment] 2019-05-17 13:55
I don't see this file anywhere. The docs say:

Linux, ~/.config/Code/User/syncLocalSettings.json.

coder@code-server-68858c5f7-bp9kv:~$ whoami
coder
coder@code-server-68858c5f7-bp9kv:~$ cd .config
coder@code-server-68858c5f7-bp9kv:~/.config$ ls -al
total 16
drwxrwsr-x  4 coder 412 4096 May 10 18:59 .
drwxrwsr-x 10   999 412 4096 May 14 18:52 ..
drwxrwS---  2 coder 412 4096 May 10 18:59 dlv
drwxrwsr-x  4 coder 412 4096 May 10 16:58 gcloud

Or anywhere else for that matter.  Placing a file copied from another
machine does not fix the problem.  The error is the same.

**Comment by DanTulovsky** [comment] 2019-05-17 14:14
Getting closer. Looking at the javascript errors, I had to create:

~ = /home/coder/

~/.config/Code
~/.config/User/
~/.config/User/Code/

Reinstalling the extension, I now have two syncLocalSettings.json.

1) /home/coder/.config/Code/User/syncLocalSettings.json
2) /home/coder/.config/User/syncLocalSettings.json

Configuring tokens, the one that's actually being used is (1).
(/home/coder/.config/Code/User/syncLocalSettings.json)

Running a Download Settings gives me a bunch of errors like:

"/usr/local/bin/bin/code" --install-extension akamud.vscode-theme-onedark
Error: Command failed: "/usr/local/bin/bin/code" --install-extension
akamud.vscode-theme-onedark
/bin/sh: 1: /usr/local/bin/bin/code: not found

(notice the extra "bin")

Javascript console is displaying:

 Error: ENOENT: no such file or directory, open
'/home/coder/.config/Code/User/settings.json'

My settings.json seems to be in:
/home/coder/.local/share/code-server/User/settings.json

**Comment by DanTulovsky** [comment] 2019-05-17 14:17
full js error if that helps more:

ide.main.2e7075.js:60 [Extension Host] Error: ENOENT: no such file or
directory, open '/home/coder/.config/Code/User/settings.json' (at
Function.<anonymous>
(/home/coder/.local/share/code-server/extensions/shan.code-settings-sync-3.2.9/out/extension.js:88:9527))

**Comment by DanTulovsky** [comment] 2019-05-17 14:27
I don't seem to have a 'code' executable on my system either.  But, using:

code-server  --install-extension hbenl.vscode-test-explorer

seems to work...

**Comment by DanTulovsky** [comment] 2019-05-17 14:30
Just to see, I made a symlink from /usr/local/bin/bin/code to
/usr/local/bin/code-server and then ran Sync Download, which now gives:

"/usr/local/bin/bin/code" --install-extension
littlefoxteam.vscode-python-test-adapter
Error: Command failed: "/usr/local/bin/bin/code" --install-extension
littlefoxteam.vscode-python-test-adapter
/usr/local/bin/bin/code: bad option: --install-extension

Which is odd, because it works if I run it manually:

coder@code-server-68858c5f7-bp9kv:/usr/local/bin/bin$
/usr/local/bin/bin/code --install-extension
littlefoxteam.vscode-python-test-adapter
(node:87095) [DEP0005] DeprecationWarning: Buffer() is deprecated due to
security and usability issues. Please use the Buffer.alloc(),
Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server development
ERROR (node:87106) [DEP0005] DeprecationWarning: Buffer() is deprecated due
to security and usability issues. Please use the Buffer.alloc(),
Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR
INFO  Extension 'littlefoxteam.vscode-python-test-adapter' is already
installed.
INFO
coder@code-server-68858c5f7-bp9kv:/usr/local/bin/bin$

**Comment by DanTulovsky** [comment] 2019-05-17 14:52
Looks like you need to augment this section:

     282     } else if (osType === OsType.Linux) {
     283       if (isInsiders) {
     284         codeLastFolder = "code-insiders";
     285         codeCliPath = "bin/code-insiders";
     286       } else {
     287         codeLastFolder = "code";
     288         codeCliPath = "bin/code";
     289       }

in src/service/pluginService.ts

to include /usr/local/bin/code-server as well.

**Comment by arnohovhannisyan** [comment] 2019-05-17 14:55
@DanTulovsky try this: https://github.com/shanalikhan/code-settings-sync/issues/668#issuecomment-491119313

**Comment by DanTulovsky** [comment] 2019-05-17 15:05
That worked, thank you.

**Comment by PulsGarney** [comment] 2019-05-20 06:59
any idea on how to fix this? 😐

> @kkorus , @PulsGarney
> Can you post your configurations in `User\syncLocalSettings.json` other than `token`

Is that file supposed in home directory? I don't find any file named `syncLocalSettings.json` in my Home directory.

**Comment by shanalikhan** [comment] 2019-05-20 13:25
Duplicate of #668

**Comment by shanalikhan** [comment] 2019-05-20 13:26
> Is that file supposed in home directory? 

What is the path of your `Users` directory for code.

**Comment by PulsGarney** [comment] 2019-05-21 02:02
> > Is that file supposed in home directory?
> 
> What is the path of your `Users` directory for code.

```bash

coder@9312a80c456a:~/project$ find ~ -iname "*s.json"
/home/coder/.local/share/code-server/languagepacks.json
/home/coder/.local/share/code-server/Backups/workspaces.json
/home/coder/.local/share/code-server/extensions/Equinusocio.vsc-material-theme-3/defaults.json
/home/coder/.local/share/code-server/extensions/Shan.code-settings-sync-3/package.nls.json
/home/coder/.local/share/code-server/extensions/ms-python.python-3/package.nls.json
/home/coder/.local/share/code-server/extensions/ms-python.python-3/languages/pip-requirements.json
/home/coder/.local/share/code-server/extensions/ms-python.python-3/package.nls.es.json
/home/coder/.local/share/code-server/User/settings.json
/home/coder/project/.vscode/settings.json

coder@9312a80c456a:~$ tree -a -L 4
.
├── .bash_history
├── .bash_logout
├── .bashrc
├── .cache
│   ├── code-server
│   │   └── logs
│   │       ├── 20190516085523506
│   │       ├── 20190517135924802
│   │       └── 20190520030620692
│   ├── pip
│   │   ├── http
│   │   │   ├── 3
│   │   │   ├── a
│   │   │   └── f
│   │   └── selfcheck.json
│   └── VSCodeVim
│       └── .cmdline_history
├── install-extensions.sh
├── .local
│   ├── bin
│   │   └── pep8
│   ├── lib
│   │   └── python3.7
│   │       └── site-packages
│   └── share
│       └── code-server
│           ├── Backups
│           ├── CachedExtensions
│           ├── extensions
│           ├── globalStorage
│           ├── languagepacks.json
│           ├── machineid
│           ├── rapid_render.json
│           ├── self-signed.cert
│           ├── self-signed.key
│           └── User
├── .profile
├── project
│   ├── index.html
│   ├── memo
│   ├── test.py
│   └── .vscode
│       └── settings.json
└── .rnd

# Are we talking about this `User`?

coder@9312a80c456a:~$ ll .local/share/code-server/User/
total 24
drwxr-xr-x 5 coder coder 4096 May 17 03:44 ./
drwxr-xr-x 7 coder coder 4096 May 17 03:26 ../
drwxr-xr-x 2 coder coder 4096 May 16 08:55 globalStorage/
-rw-r--r-- 1 coder coder 1533 May 17 08:28 settings.json
drwxr-xr-x 2 coder coder 4096 May 17 03:31 snippets/
drwxr-xr-x 3 coder coder 4096 May 17 03:26 workspaceStorage/

```

Directories goes like that, I am not quite sure about what exactly I am looking for..

**Comment by arnohovhannisyan** [comment] 2019-05-21 02:09
@PulsGarney have you tried https://github.com/shanalikhan/code-settings-sync/issues/668#issuecomment-491119313?

**Comment by PulsGarney** [comment] 2019-05-21 02:48
@arnohovhannisyan  yeah that one worked! Thank you!!

**Closed** 2019-05-21 08:20 UTC
