### ISSUE TITLE
Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.

### ISSUE THREAD

**Issue by SPurno** [shanalikhan/code-settings-sync#703] opened 2018-11-08 18:56 UTC
🐛 **Describe the bug**  
When I am trying to upload the token into vscode, an error message is shown in right bottom of the vscode that "Sync: Invalid / Expired Github Token...

🌴 **Visual Studio Code Version :** [ 1.28.2 ] 
🌴 **Code Settings Sync Version :** [ 3.2.2] 
🌴 **Standard or Insiders :** [  ] 
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [ Windows 10 ] 
🌴 **Occurs On:** [Upload & Download]
🌴 **Proxy Enabled:** [ No]
🌴 **Gist Id:** [ 50f37fc18c74e4b8c77c53295d815766567c78c2 ]

📰 **To Reproduce**

💪 **Expected behavior**
Able to upload gist token & sync settings via token.

📺 **Console Error Log** 
Nothing

📺  **Additional context**
Hope it will be fixed soon for your extension better user experience. Thanks.

**Comment by shanalikhan** [comment] 2018-11-09 09:43
Duplicate of #689

**Closed by shanalikhan** 2018-11-09 09:43 UTC
