### ISSUE TITLE
Enable it to work on Azure Data Studio

### ISSUE THREAD

**Issue by Peluko** [shanalikhan/code-settings-sync#892] opened 2019-05-20 09:13 UTC
💡 **Is your feature request related to a problem? Please describe.**
Azure Data Studio is *VSCode* for SQL Server (and now for postgresql also), so I'm using it more and more when I have to work with DBs.

💡 **Describe the solution you'd like**
I will like to be able to sync settings between computers as easily as I do with VSCode.

💡 **Additional context**
I've installed the .vsix for this extension on Azure Data Studio, since it's not listed on extensions marketplace (I've done this with other extensions without problem, p.e. VSCodeVim). When I do 'Update/Upload settings' I got an error 'Sync: Error Logged in Console', but I don't understand the errors. Also I've noticed that if I do 'Advanced Options -> Edit Extensions Local Settings', the settings file opened is the one under '/Code/User', when it should be '/azuredatastudio/User'.

**Comment by shanalikhan** [comment] 2019-05-20 13:26
PR is welcome for it.

**Comment by arnohovhannisyan** [comment] 2019-05-24 21:51
@Peluko this might be an issue with finding the User folder properly. Can you try this? https://github.com/shanalikhan/code-settings-sync/issues/668#issuecomment-491119313

**Comment by shanalikhan** [comment] 2019-05-30 15:34
Duplicate of #668

**Comment by shanalikhan** [comment] 2019-06-24 19:12
I have released new version of Settings Sync v3.3.0 fixing this issue. Im closing this ticket let me know if u guys run into some problem.

**Closed by shanalikhan** 2019-06-24 19:12 UTC
Labels: duplicate, fixed

**Comment by tillig** [comment] 2019-06-24 19:46
Based on [the publishing doc](https://docs.microsoft.com/en-us/sql/azure-data-studio/extension-authoring?view=sql-server-2017) it appears you need to add the extension to [this JSON file](https://github.com/Microsoft/azuredatastudio/blob/release/extensions/extensionsGallery.json) to allow it to be seen by the Azure Data Studio extension list.
