### ISSUE TITLE
Each VSCode window writes config upon opening

### ISSUE THREAD

**Issue by kbd** [shanalikhan/code-settings-sync#565] opened 2018-06-11 17:05 UTC
This morning I opened VSCode and it uploaded my settings (where there were no changes to my config!) 11 times (if I counted correctly... see the gist). I'd say it was once per VSCode window but I only have 8 VSCode windows open. It's frustrating because, besides being incorrect behavior, this upload sync process that happens repeatedly can take minutes to complete, with the bottom panel constantly updating/refreshing before I can focus on work.

**Visual Studio Code Version :** 1.24.0
**Code Settings Sync Version :** 2.9.2
**Operating System :** macOS 10.13.4
**Occurs On:** upload
**Proxy Enabled:** No
**Gist Id:** https://gist.github.com/kbd/9c099110598e09bf6ecb597d7b27f4bd/revisions

**Comment by shanalikhan** [comment] 2018-06-19 20:01
Do you have auto upload / download enabled ?

**Comment by kbd** [comment] 2018-06-19 20:03
Yes.

**Comment by shanalikhan** [comment] 2018-06-19 20:04
Duplicate of #396

**Closed by shanalikhan** 2018-06-19 20:04 UTC
