### ISSUE TITLE
Error during initial sync

### ISSUE THREAD

**Issue by gpearson100** [shanalikhan/code-settings-sync#71] opened 2016-08-25 16:45 UTC
**Visual Studio Code Version :** 1.4.0
**Code Sync Settings Version :** 1.6.3
**Operating System :** Win 7

says Link not found: https://developer.github.com/v3 but its a valid link

![2016-08-25 11_43_09-program manager](https://cloud.githubusercontent.com/assets/248626/17977934/3e8c9516-6ab9-11e6-9326-b000db9f62c3.png)

**Comment by shanalikhan** [comment] 2016-08-25 16:48
Duplicate of [#59](https://github.com/shanalikhan/code-settings-sync/issues/59).

Try again with the solution in the link and let me know if error still there

**Closed by shanalikhan** 2016-08-25 16:48 UTC
Labels: duplicate, question
