### ISSUE TITLE
command 'extension.updateSettings' not found in portable mode!

### ISSUE THREAD

**Issue by amal-khailtash** [shanalikhan/code-settings-sync#601] opened 2018-07-21 15:02 UTC
**Describe the bug**

**Visual Studio Code Version :** 1.25.1
**Code Settings Sync Version :** 3.0.0
**Operating System :** Windows 10
**Occurs On:** Upload and Download
**Proxy Enabled:** No
**Gist Id:** e9caf9472e88b56ef37bcdc408b771d5

**To Reproduce**
1. Moved data/extensions as described in https://code.visualstudio.com/docs/editor/portable
2. Tried Sync Upload/Download

**Expected behavior**
Sync should have happened

**Console Error Log**
No messages

**Additional context**
None

I tried uninstalling/removing extension directory and install again, same problem.

Doing "Advanced Options", shows "command 'extension.otherOptions' not found"
Doing "Reset Sync Settings", shows "command 'extension.resetSettings' not found"

**Comment by shanalikhan** [comment] 2018-07-22 08:15
Duplicate of #591

**Closed by shanalikhan** 2018-07-22 08:15 UTC
