### ISSUE TITLE
Why is NODE_TLS_REJECT_UNAUTHORIZED set to 0?

### ISSUE THREAD

**Issue by MattMorgis** [shanalikhan/code-settings-sync#776] opened 2019-02-19 16:36 UTC
🐛 **Describe the bug**  
When running my app with Node.js 11 within VS Code, I get the following message when making an `https` request:

> (node:28306) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

When I run my app with Node.js 11 **without** VS Code, I do not get this message.

I narrowed it down to this extension setting the variable to `0`: https://github.com/shanalikhan/code-settings-sync/blob/e80b2ceca227490e5e12f33d419659343e2a705c/src/environmentPath.ts#L84

Why is this being set and does it have to be? 
  
  

🌴 **Visual Studio Code Version :** [ `1.31.1` ] 
🌴 **Code Settings Sync Version :** [ `3.2.5` ] 
🌴 **Standard or Insiders :** [ `standard` ] 
🌴 **Operating System :** [ `macOS` ]

**Comment by shanalikhan** [comment] 2019-02-20 14:18
This is done , several users reported earlier that they are facing problems in certificates while connecting to github. 

Is there any problem you are facing with this configuration ?

**Comment by MattMorgis** [comment] 2019-02-20 14:28
Yes, this is highly insecure. You are disabling TLS validation for any process running within VS Code. Now *my app* does not validate SSL certificates when run with VS Code

**Comment by marcellourbani** [comment] 2019-02-21 09:05
@shanalikhan I agree

Just had the same issue: users complained my extension didn't validate certificates and all looked fine for me as you disabled the checks. 
Much better if you add an option to install the right root CA

**Comment by shanalikhan** [comment] 2019-02-21 17:18
>  Much better if you add an option to install the right root CA

I am open for PR if it solves the problem in both ways, installing CA and not using validation.

**Comment by nikolalukovic** [comment] 2019-02-22 08:04
> This is done , several users reported earlier that they are facing problems in certificates while connecting to github.

The solution should *never* be a complete disable of such a low level security feature which is paramount for secure systems. Especially if it side effects into the whole process. 
The problem is with those users' machines/networks and a library should  *never* try and fix a problem that does not even come remotely close to its primary function.

**Comment by kron4eg** [comment] 2019-02-22 10:16
>The solution should _never_ be a complete disable of such a low level security feature which is paramount for secure systems.

Indeed. I had to uninstall the plugin for now to restore normal behaviour.

**Comment by marcellourbani** [comment] 2019-02-22 11:01
Me too.

**Comment by MattMorgis** [comment] 2019-02-22 14:44
>The problem is with those users' machines/networks and a library should _never_ try and fix a problem that does not even come remotely close to its primary function.

If users report SSL trust issues, they should be sent here: https://code.visualstudio.com/docs/setup/network#_ssl-certificates

I sent PR #779 which removes the disabling of TLS certificate validation, which would make this safe to use again.

**Comment by shanalikhan** [comment] 2019-03-05 12:07
Released with v3.2.6

**Closed by shanalikhan** 2019-03-05 12:07 UTC
Labels: PR-Welcome  ✨, fixed

**Comment by bernardop** [comment] 2019-03-07 17:26
@MattMorgis after the 3.2.6 update I haven't been able to use this extension. Whenever I try to update/upload I get an error (Sync: Internet not connected or unable to connect to GitHub. Exception logged in Console). When I look at the console there's a couple of "unable to verify the first certificate" errors. I have tried setting my `http.proxyStrictSSL` to false and launching vs code with the `--ignore-certificate-errors` flag without any luck.

What do you think of having a setting that would set `NODE_TLS_REJECT_UNAUTHORIZED` to 0 right before a network request and set it back to 1 right after? Or is that still insecure?

**Comment by ggirard07** [comment] 2020-01-09 21:39
@MattMorgis How did you manage to narrow it down to this extension from this single error message?  
I am currently having the same kind of issue (same error message while trying to run my app in debug), but obviously not from this extension as I don't have it...

**Comment by mattmorgis** [comment] 2020-01-09 22:12
I believe I grepped my VS Code extensions folder for that environment variable key and then found the line (and therefore the extension) where it was being set.

**Comment by ggirard07** [comment] 2020-01-09 22:48
@MattMorgis thanks, I found my culprit "Azure Repos" extension from Microsoft :/

**Comment by icemagno** [comment] 2024-04-17 16:11
Why ZERO? Why not FALSE/TRUE ?

**Comment by jinhua115** [comment] 2024-04-17 16:12
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
