### ISSUE TITLE
Pragma removes '//' from value when uncommenting

### ISSUE THREAD

**Issue by chodyo** [shanalikhan/code-settings-sync#863] opened 2019-04-25 16:56 UTC
🐛 **Describe the bug**  
If an uncommented pragma value contains the text `//`, the `//` is removed from the value.

For example, if a URL with protocol has a value of `http://example.com`, it will be uploaded to the remote gist with a value of `http:example.com`. 

🌴 **Visual Studio Code Version :** [ 1.33.1 ] 
🌴 **Code Settings Sync Version :** [ 3.2.9 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official ] 
🌴 **Operating System :** [ Windows 10 ] 
🌴 **Occurs On:** [ Upload ]
🌴 **Proxy Enabled:** [ Yes ]
🌴 **Gist Id:** [ n/a ]

📰 **To Reproduce**
1. Create a pragma that in use by the current machine pragma settings. It should be uncommented and contain `//` somewhere in the json's value.
2. Upload settings
3. Check uploaded value (view on web or force download). `//` is now missing from the key.

💪 **Expected behavior**
Keys should never be modified on upload or download.

📺 **Console Error Log** 
n/a

📺  **Additional context**
``` jsonp
// local settings
{
    // @sync host=home-desktop-pc
//    "http.proxy": "",
    // @sync host=work-laptop
    "http.proxy": "http://127.0.0.1:8888"
}
// remote upload
{
    // @sync host=home-desktop-pc
    "http.proxy": "",
    // @sync host=work-laptop
    "http.proxy": "http:127.0.0.1:8888"
}
```

**Comment by shanalikhan** [comment] 2019-05-02 14:04
Duplicate of #865

**Closed by shanalikhan** 2019-05-02 14:04 UTC
