### ISSUE TITLE
Settings Sync does not work

### ISSUE THREAD

**Issue by anatol06** [shanalikhan/code-settings-sync#678] opened 2018-10-14 15:25 UTC
Issue Type: <b>Bug</b>

I installed on Linux Solo VS Code > installed Settings Sync extension and tried to download my settings from Github as I do on Windows version but it does not work. 

Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

It does not even ask for Token.... 
I tried to go to settings and insert there the Token but same issue. 
On Windows it works.

Extension version: 3.1.2
VS Code version: Code - OSS 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-12T19:57:46+03:00)
OS version: Linux x64 4.18.5-90.current

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 1758)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.55GB (13.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by shanalikhan** [comment] 2018-10-14 17:30
Duplicate of #668

**Closed by shanalikhan** 2018-10-14 17:30 UTC
