### ISSUE TITLE
Can't sync settings with error "Invalid / Expired GitHub Token"

### ISSUE THREAD

**Issue by levblanc** [shanalikhan/code-settings-sync#690] opened 2018-10-22 06:25 UTC
I checked every related issue, but couldn't solve my problem.

I tried to regenerate my token several times, coupled with my gist id to download, got the error.

Also tried to generate new tokens several times, and then upload (or create a new gist), got the error. 

Really frustrated and don't know what to do.... I really need my settings.

Please please please help. 

---

MacOS: 10.11.6 (EI Capitan)
VS Code : 1.28.2 (freshly reinstall today)
Settings Sync: 3.2.0

VS Code keep telling me today that it can't update, so I decided to reinstall it. 

Before reinstalling, I upload my settings to:

[https://gist.github.com/levblanc/ec97529308d0ecf93ffc253f721bcad5](https://gist.github.com/levblanc/ec97529308d0ecf93ffc253f721bcad5)
(secret gist, named as cloudSettings, no problems in sync before)

After reinstall, I regenerate my token: 

![image](https://user-images.githubusercontent.com/4057887/47277197-28e89a80-d5f0-11e8-8173-f13c967333ab.png)

my token setting:

![image](https://user-images.githubusercontent.com/4057887/47277212-56354880-d5f0-11e8-9e42-152732e78465.png)

my gist id setting: 
![image](https://user-images.githubusercontent.com/4057887/47277218-6e0ccc80-d5f0-11e8-84a1-3535131f0267.png)

got the error and there is nothing logged in the debug console:
![image](https://user-images.githubusercontent.com/4057887/47277221-841a8d00-d5f0-11e8-8456-e0a871eff3b5.png)

**Comment by shanalikhan** [comment] 2018-10-22 15:28
Duplicate of #689

**Closed by shanalikhan** 2018-10-22 15:28 UTC
