### ISSUE TITLE
how can sync also my spellright.dict file ?

### ISSUE THREAD

**Issue by pelos6** [shanalikhan/code-settings-sync#495] opened 2018-02-12 22:18 UTC
**Visual Studio Code Version :** 
Versión: 1.20.0
Confirmación: c63189deaa8e620f650cc28792b8f5f3363f2c5b
Fecha: 2018-02-07T17:09:39.780Z
Shell: 1.7.9
Representador: 58.0.3029.110
Nodo 7.9.0
Arquitectura x64
**Code Settings Sync Version :** 2.8.7
**Operating System :** [ Windows 10 ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:**  3906937897f091da7cd671603dbf8aaf

how can sync also my spellright.dict file ?

Thanks !

**Comment by shanalikhan** [comment] 2018-02-13 23:50
what is the complete path of this file ?

**Comment by pelos6** [comment] 2018-02-14 05:45
Hi shanalikhan.
the full path is C: \ Users \% USERNAME% \ AppData \ Roaming \ Code \ User \ spellright.dict
I am using this file with this plugin https://marketplace.visualstudio.com/items?itemName=ban.spellright

thanks for your quick response.

Javier

**Comment by shanalikhan** [comment] 2018-02-16 09:43
Duplicate of #340

**Comment by shanalikhan** [comment] 2018-02-16 09:43
Will work on it.

**Closed by shanalikhan** 2018-02-16 09:43 UTC

**Comment by ahmadawais** [comment] 2019-07-29 10:37
@shanalikhan I also wanted to request this same thing. File-path is `/Users/ahmadawais/Library/Application Support/Code/User/spellright.dict` and it's currently sitting there without a backup/sync. Is there a way to define this file to be synced as well?

**Comment by shanalikhan** [comment] 2019-07-31 07:19
@ahmadawais 

Yes, check the Global Settings of Settings Sync.

https://github.com/shanalikhan/code-settings-sync#global-settings

You need to add your file extension inside `supportedFileExtensions` to allow Settings Sync to include this file.

**Comment by ahmadawais** [comment] 2019-07-31 10:20
Ah, I got it working through the custom file path option. Thank you!!
