### ISSUE TITLE
upload error 

### ISSUE THREAD

**Issue by lybest** [shanalikhan/code-settings-sync#620] opened 2018-08-27 06:47 UTC
🐛 **Describe the bug**  

🌴 **Visual Studio Code Version :** [ 1.26.1 ] 
🌴 **Code Settings Sync Version :** [ 3.1.0 ] 
🌴 **Operating System :** [ win 10 ] 
🌴 **Occurs On:** [Upload ]
🌴 **Proxy Enabled:** [  No ]

💪 **Expected behavior**
today sync updated to 3.1.0, then I fount when sync upload, I got an error, but download worked well.

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.
![image](https://user-images.githubusercontent.com/9312109/44644749-c6b45480-aa07-11e8-826a-7a1a109c9b99.png)

📺  **Additional context**

**Comment by shanalikhan** [comment] 2018-08-28 09:03
Duplicate of  #622

**Closed by shanalikhan** 2018-08-28 09:03 UTC
