### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by zettlrobert** [shanalikhan/code-settings-sync#1219] opened 2020-06-21 12:02 UTC
💡 **Is your feature request related to a problem? Please describe.**
Wanted to clean my VsCodium installation and get a few unnecessary extensions out.
As they have there own extension regsitry now, your extension is unfortunately not available anymore.
It is really easy to publish though. (https://www.gitpod.io/blog/open-vsx/)

💡 **Describe the solution you'd like**
You either puplish it yourself or i will look into creating a PR to automatically integrate it in there store

Feel free to message me

**Comment by TBBle** [comment] 2020-06-22 07:31
Dupe of #1217?

**Comment by zettlrobert** [comment] 2020-06-23 05:16
@TBBle yes, seems like it. :)

**Comment by shanalikhan** [comment] 2020-09-30 15:16
Duplicate of #1217

Open for PR.

**Closed as completed by shanalikhan** 2020-09-30 15:16 UTC
