### ISSUE TITLE
No error but settings not downloading

### ISSUE THREAD

**Issue by sirgru** [shanalikhan/code-settings-sync#609] opened 2018-08-10 11:39 UTC
Installed on PC 1 (Windows 7) and pushed the settings. On PC 2 (Windows 8.1) pulled the settings. Changed settings on PC 2, and pushed.

Pulling on PC 1 doesn't give any errors, but the synching doesn't happen. Developer console reveals this is the step it stops on:
Installing from Url :https://ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/csharp/1.15.2/1526415359369/Microsoft.VisualStudio.Services.VSIXPackage?install=true

Turns out on PC 1 the C# extension was present but disabled. Enabling the extension fixed the issue for me. However, I still wanted to report the bug. 

**Visual Studio Code Version :** 1.25.1
**Operating System :** Windows 7

**Comment by shanalikhan** [comment] 2018-08-10 12:06
> Turns out on PC 1 the C# extension was present but disabled

Settings Sync will install extensions but you need to restart the Code to enable those extensions

**Comment by shanalikhan** [comment] 2018-08-13 20:55
Duplicate of #143

**Comment by shanalikhan** [comment] 2018-08-13 20:56
Yes disabled installation not support by Settings Sync at the moment.

**Closed by shanalikhan** 2018-08-13 20:55 UTC
