### ISSUE TITLE
vsCode Portable Sync Location

### ISSUE THREAD

**Issue by mpearon** [shanalikhan/code-settings-sync#615] opened 2018-08-17 17:54 UTC
🐛 **Describe the bug**  
vsCode Portable Sync Location

🌴 **Visual Studio Code Version :** 1.26.1
🌴 **Code Settings Sync Version :** 3.0.0
🌴 **Operating System :** Windows 10 v1803
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** N/A

📰 **To Reproduce**
1. Download Settings

💪 **Expected behavior**
In the portable version of vsCode (which they are pushing pretty hard), you have the ability to nest the extensions and user-data directories in the application folder: [see here].
...but it appears that SettingsSync placed the downloaded data in the default location (ie: C:\Users\userName\.vscode)

I would expect this to detect the proper location based on the installation type.

[see here]: https://code.visualstudio.com/docs/editor/portable#_windows-linux

**Comment by shanalikhan** [comment] 2018-08-17 21:42
Duplicate of #331

**Closed by shanalikhan** 2018-08-17 21:42 UTC
