### ISSUE TITLE
Syncing of extensions not working in portable mode

### ISSUE THREAD

**Issue by drb-germany** [shanalikhan/code-settings-sync#756] opened 2019-01-25 10:26 UTC
🐛 When installing VS Code in portable mode with local data directory, extensions are not (fully) synced

VS Code can be installed in portable mode (download ZIP file and extract in some random directory). If you create a folder with the name "data" in the main directory, VS Code will save all settings and extensions into this subdirectory (see https://code.visualstudio.com/docs/editor/portable).

With this mode, Sync is ignoring most of the extensions. Out of five installed extensions, only one was synced to the file extensions.json in GIST. Even code-settings-sync itself is not synced as extension. As a result, downloading the settings on another installation only installs the one synced extension.

Doing the same setup with a regular installation works.

🌴 **Visual Studio Code Version :** 1.30.2
🌴 **Code Settings Sync Version :** 3.2.4
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** Portable
🌴 **Operating System :** Win 10
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** No

📰 **To Reproduce**
1. Install VS Code Portable
2. Create 'data' directory in VS Code folder
3. Start VS Code, download code-settings-sync
4. Install some extensions (e.g. prettier, vetur, they did not work for me)
5. Upload settings
6. Check gist (extensions.json) or download settings on another machines: extensions will be missing

💪 **Expected behavior**
All extensions uploaded

**Comment by shanalikhan** [comment] 2019-02-15 14:53
can you show an image of the following:

1. data folder
2. Image of the console log from the vscode, to see any exception being logged over there.

**Comment by LuisUrrutia** [comment] 2019-02-25 19:04
Same problem here:
The only "Error" in the console was:
<img width="1302" alt="captura de pantalla 2019-02-25 a la s 16 02 41" src="https://user-images.githubusercontent.com/3771248/53361612-eb39ac80-3916-11e9-90cb-f16df9552c84.png">

And the portable folder has:
<img width="624" alt="captura de pantalla 2019-02-25 a la s 16 04 23" src="https://user-images.githubusercontent.com/3771248/53361669-0e645c00-3917-11e9-9ce2-5eb70fe7e8c8.png">

**Comment by shanalikhan** [comment] 2019-03-05 12:08
Its fixed with new version v3.2.6

let me know in case of issue.

**Comment by KolyaKorruptis** [comment] 2019-03-05 15:01
I just got updated to Version: 3.2.6. of Settings Sync on my portable vscode instance.
I uploaded my settings and now the extensions array is completely empty. Meanwhile I have about 30 extensions installed.
Before the 3.2.6 update extensions were only noted partly, as described by OP.

**Comment by shanalikhan** [comment] 2019-03-05 15:37
@LuisUrrutia can you look into this. 
Feel free to send PR, i will release in new version ( if there is still something missing )

**Comment by LuisUrrutia** [comment] 2019-03-05 16:14
@KolyaKorruptis can you open the developer tools of VSCode
<img width="374" alt="screen shot 2019-03-05 at 1 13 30 pm" src="https://user-images.githubusercontent.com/3771248/53819333-813d8a80-3f48-11e9-9451-51e18e45592e.png">

Try to upload again and share the console log?

**Comment by LuisUrrutia** [comment] 2019-03-05 16:23
@KolyaKorruptis cool! Now I know what the problem is. Are you sure that this extension worked before in the same VSCode portable and in the same OS?

**Comment by KolyaKorruptis** [comment] 2019-03-05 16:23
Yes, I'm sure. It worked partially, as OP describes in the first post.

**Comment by LuisUrrutia** [comment] 2019-03-05 16:25
@shanalikhan can u re-open this issue and assign it to me?

**Comment by shanalikhan** [comment] 2019-03-05 16:32
It's reopened 
U can send PR

**Comment by gsabater** [comment] 2019-03-05 20:53
I have the same issue as @KolyaKorruptis
My extensions now are an empty array and autodownloading the settings from other computer removed all extensions

**Comment by LuisUrrutia** [comment] 2019-03-05 21:07
@gsabater windows, right?

**Comment by gsabater** [comment] 2019-03-05 21:21
@LuisUrrutia yes, on both machines

**Comment by HJerem** [comment] 2019-03-05 21:22
Same problem here, everything working fine except extensions.json file always empty.
I'm on Windows 10, Visual Studio Code 1.31.1
It was working fine some weeks ago.

**Comment by zcmk123** [comment] 2019-03-06 02:06
same problem with the empty extensions.json ....

**Comment by hihahihahoho** [comment] 2019-03-06 03:19
Same problem here

**Comment by Gigacee** [comment] 2019-03-06 07:28
Same issue on my PC.

environment:
Windows 10 Pro 64bit
Settings Sync v3.2.6
Visual Studio Code v1.31.1 (User Installer)

settings:
```
	"sync.autoDownload": true,
	"sync.autoUpload": true,
	"sync.gist": "xxx",
	"sync.quietSync": true,
```

**Comment by shanalikhan** [comment] 2019-03-06 12:50
It should be fixed in new version `v3.2.7`.

Let me know if there is any problem.

**Comment by KolyaKorruptis** [comment] 2019-03-06 13:03
@shanalikhan Looking good.

All active extensions were uploaded. One inactivated extension wasn't. I guess that's expected behaviour.

**Closed** 2019-03-06 13:09 UTC
Labels: bug 🐛

**Comment by Gigacee** [comment] 2019-03-07 00:07
It looks like no problem. Thanks!

**Comment by Kuzmich100kM** [comment] 2020-01-22 10:16
All active extensions were uploaded good. When loading it writes "Sync: You already have the latest version of saved settings." , but nothing loads.
![sync download](https://user-images.githubusercontent.com/46998842/72885756-35870180-3d11-11ea-8a6f-cd181ab1937a.png)

**Comment by KolyaKorruptis** [comment] 2020-01-22 22:33
@Kuzmich100kM This issue was about a specific problem that was solved back then and now it's been closed for a while. Please open a new issue for your problem.
