### ISSUE TITLE
Is there an offline support?

### ISSUE THREAD

**Issue by Schizo** [shanalikhan/code-settings-sync#890] opened 2019-05-17 01:39 UTC
We are working in an environment where the internet is strictly detached from our LAN, but we can Collect and Download files. Is there a way of `packaging` all extensions/settings and copying it to a device that has no access to the internet and install it?

**Comment by shanalikhan** [comment] 2019-05-17 09:07
Nice point. 
Added to backlog

**Comment by shanalikhan** [comment] 2019-07-01 17:22
Duplicate of #256

**Closed by shanalikhan** 2019-07-01 17:22 UTC
Labels: feature-request  💡
