### ISSUE TITLE
Can't installed extensions as root on Kali Linux, how solve it (the latest version)?

### ISSUE THREAD

**Issue by Marlous** [shanalikhan/code-settings-sync#869] opened 2019-05-02 19:49 UTC
Can't installed extensions as root on Kali Linux, how solve it (the latest version)?
Can‘t use `-user-data-dir=` parameter in settings-sync.

**Comment by shanalikhan** [comment] 2019-05-03 16:44
Duplicate of #411

**Closed by shanalikhan** 2019-05-03 16:44 UTC
