### ISSUE TITLE
Can't load Sync

### ISSUE THREAD

**Issue by valentinocossar** [shanalikhan/code-settings-sync#568] opened 2018-06-12 13:36 UTC
**Describe the bug**
Hi, I've noticed that the extension no longer updates the gist, so I've tried to identify where the issue could be. Forcing upload via command (both alt + shift + U and upload command) or resetting settings result in these errors: `command extension.updateSettings not found`, `command extension.resetSettings not found` (and the same happens with every other Sync command). So I've tried to uninstall and reinstall the extension, but the problem occurs every time I install the extension. Seems that VS Code can't load Sync at all.

**Visual Studio Code Version :** Stable 1.24.0
**Code Settings Sync Version :** 2.9.2
**Operating System :** macOS 10.13.5
**Occurs On:** Every task
**Proxy Enabled:** No
**Gist Id:** 43d820ff565644f1bb1b75b03454d9ed

**To Reproduce**
Running every command or trying to do something with the extension.

**Expected behavior**
I'm expecting the extension to work, but it doesn't.

**Console Error Log**
![schermata 2018-06-12 alle 15 27 11](https://user-images.githubusercontent.com/4087384/41325044-76a88e28-6eb8-11e8-9581-c2b07e22c06d.png)
![schermata 2018-06-12 alle 15 27 33](https://user-images.githubusercontent.com/4087384/41325045-76cb364e-6eb8-11e8-8896-4aa1bcac8cba.png)
Translating debug console screenshots from Italian to English:
Italian: `L'attivazione dell'estensione 'Shan.code-settings-sync' non è riuscita: ENOENT: no such file or directory, open '/Users/home_folder/Library/Application Support/User/sync.lock'.`
English: `Activating extension 'Shan.code-settings-sync' failed:  ENOENT: no such file or directory, open '/Users/home_folder/Library/Application Support/User/sync.lock'`.

The User folder doesn't exist within Application Support.

**Comment by shanalikhan** [comment] 2018-06-19 19:59
Duplicate of #549

**Comment by shanalikhan** [comment] 2018-06-19 19:59
Yes you are right, it will be fixed in next version

**Closed** 2018-06-19 20:00 UTC
