### ISSUE TITLE
sync not working in vscode 1.37.0

### ISSUE THREAD

**Issue by limejuly** [shanalikhan/code-settings-sync#1002] opened 2019-08-13 11:37 UTC
**Visual Studio Code Version : 1.37.0
**Code Settings Sync Version : 3.2.9 and all later versions
**Operating System : MacOS 10.13.6
**Occurs On: Upload, Download
**Proxy Enabled: No

The extension had been working perfectly, but today as VSCode automatically updates, I find it fails to sync. 

By choosing "upload", the status bar says " Sync: Reading Settings and Extensions. ", and then nothing happens, no message in output. 
Also, by triggering "download", the status bar says " Sync: Reading Settings Online." without any following. 

I'm hoping it spit out any error message at least, so I can know which part goes wrong.

**Comment by yubaoquan** [comment] 2019-08-14 04:17
There is no errors in devTool either.

**Comment by shanalikhan** [comment] 2019-08-16 13:16
> The extension had been working perfectly, but today as VSCode automatically updates, I find it fails to sync.

I have tried on linux and its working.

@yubaoquan are you also using MacOS ?

**Comment by Vorror** [comment] 2019-08-17 07:48
Also happening to me. No message or feedback. I only workaround is to turn on forceUpload.

**Comment by yubaoquan** [comment] 2019-08-19 01:25
> > The extension had been working perfectly, but today as VSCode automatically updates, I find it fails to sync.
> 
> I have tried on linux and its working.
> 
> @yubaoquan are you also using MacOS ?

I use windows 10.

**Comment by shanalikhan** [comment] 2019-08-21 12:12
New version is released. let me know if its working at your end.
I have test on Windows and Ubuntu

**Comment by yubaoquan** [comment] 2019-08-22 05:24
version: 3.4.2
1. Turn off the `force upload`
2. Modify a snippet file
3. Execute Sync: Update/Upload Settings

Expect: 
snippet upload to gist

Actual:
1. A message show in bottom bar something like "Sync is reading extensions and config"
2. Nothing happens, no output 


By the way, how to set setting sync show English text? I don't want it showing me the local language.

**Comment by shanalikhan** [comment] 2019-08-22 06:51
> By the way, how to set setting sync show English text? I don't want it showing me the local language.

Yes, There is already issue opened for this: #987

**Comment by limejuly** [comment] 2019-08-22 13:24
tried the new version 3.4.2, the problem remains.

**Comment by austincummings** [comment] 2019-08-26 03:56
@shanalikhan I believe this has to do with the `IsGistNewer` call in `github.service.ts` always returning true. In my case the `localLastUpload` and `gistLastUpload` dates are always equal.

When it's being called here... (sync.ts:259)
```ts
            const gistNewer = await github.IsGistNewer(
              syncSetting.gist,
              new Date(customSettings.lastUpload)
            );
```

The `customSettings.lastUpload` is the same date as the gist last upload date. And while that is probably what it is supposed to be, I don't know why this check is being done.

Locally I change the `>=` in `IsGistNewer` to just be `>` and it works, but I don't know what I'm breaking by doing that.

**Comment by tommulkins** [comment] 2019-08-29 20:36
> @shanalikhan I believe this has to do with the `IsGistNewer` call in `github.service.ts` always returning true. In my case the `localLastUpload` and `gistLastUpload` dates are always equal.
> 
> When it's being called here... (sync.ts:259)
> 
> ```ts
>             const gistNewer = await github.IsGistNewer(
>               syncSetting.gist,
>               new Date(customSettings.lastUpload)
>             );
> ```
> 
> The `customSettings.lastUpload` is the same date as the gist last upload date. And while that is probably what it is supposed to be, I don't know why this check is being done.
> 
> Locally I change the `>=` in `IsGistNewer` to just be `>` and it works, but I don't know what I'm breaking by doing that.
> 
> Hope this helps.

I think this is it.  Since updating when I attempt to upload my settings it complains "Gist has a newer or identical version of your settings" though I know my local version is more up to date.

I have to select Yes to enable forceUpload.

**Comment by freMea** [comment] 2019-08-30 22:13
> I think this is it. Since updating when I attempt to upload my settings it complains "Gist has a newer or identical version of your settings" though I know my local version is more up to date.
> 
> I have to select Yes to enable forceUpload.

VS Code version | OS | Extension version
------------------ | ---- | ----
1.37.1 | Win 10 x64 pro (french) 18362 | 3.4.2

I confirm the same non-sense message: _**Gist has newer or identical version of your settings…**_

>Locally I change the >= in IsGistNewer to just be > and it works, but I don't know what I'm breaking by doing that.
>
>Hope this helps.

Basically, this edit does the same as force upload. It’s not a fix.

**Comment by shanalikhan** [comment] 2019-09-02 15:59
Duplicate of #1016

**Closed by shanalikhan** 2019-09-02 15:59 UTC

**Comment by shanalikhan** [comment] 2019-09-02 16:00
@limejuly I suggest you to open new issue if you are not asking about the Force Upload Bug.

> sync not working in vscode 1.37.0

There must be any console log.
