### ISSUE TITLE
Auto upload should trigger when extensions.json updates

### ISSUE THREAD

**Issue by whimzee** [shanalikhan/code-settings-sync#632] opened 2018-08-31 09:42 UTC
When you make an update to your extensions this does not trigger an automatic upload if `sync.autoUpload` is set to true. This is frustrating because you have to run the command yourself if you want to sync your list of extensions after a change.

I propose that an automatic upload should be initiated when extensions.json is updated. This feature should respect the `sync.autoUpload` option.

**Comment by shanalikhan** [comment] 2018-08-31 19:40
Duplicate of #123

**Closed by shanalikhan** 2018-08-31 19:40 UTC
