### ISSUE TITLE
How to configure Settings Sync via command line?

### ISSUE THREAD

**Issue by janpio** [shanalikhan/code-settings-sync#465] opened 2017-12-06 23:08 UTC
https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions shows how to install an extension via command line. For this extension, this means `code --install-extension Shan.code-settings-sync`, which works perfectly.

But now I still have to manually edit the gist id. Is there a way to do this step via command line as well?

PS: This question is now also at StackOverflow: https://stackoverflow.com/questions/47685100/how-to-configure-visual-studio-code-extensions-from-command-line

**Comment by shanalikhan** [comment] 2017-12-07 08:56
Duplicate of https://github.com/shanalikhan/code-settings-sync/issues/403

Currently its Limitation from Code, editor doesnt allow extension to perform actions from CLI

**Comment by shanalikhan** [comment] 2017-12-07 08:57
Currently its Limitation from Code, editor doesnt allow extension to perform actions from CLI

**Closed by shanalikhan** 2017-12-07 08:56 UTC
