### ISSUE TITLE
Can't force download & Can't download extensions

### ISSUE THREAD

**Issue by andrefecto** [shanalikhan/code-settings-sync#758] opened 2019-01-29 18:47 UTC
🐛 **Describe the bug**  
I free install VSCode after deleting all related Code, Microsoft Visual Studio Code, etc. Then install the Settings Sync extension. I provide my secret token, then my gist ID. It shows that it detected the extensions.json and settings.josn, asks if I want to reload VSCode to apply the changes. I reload, and nothing happens. My extensions and settings do not show up.

After more testing, this seems to be a problem syncing between Mac and Windows. My home laptop is a MacBook Pro and my work laptop is Windows. If I try to use the same gist for both, it gives me these errors. If I do a fresh upload of my settings and compare the files uploaded from my Mac and files uploaded from Windows, they don't look different but seem to not be compatible.

Here is a link to the "Windows" upload: https://gist.github.com/andrefecto/69d4988fd14b798aef17dfb18b3e2a72

Here is a link to the Mac upload:
https://gist.github.com/andrefecto/56790752d18d9b62cbbe8e0ca00e4da6

I've also tried this on two different Windows computers. One computer had never been used with VSCode and still produced all these errors.

🌴 **Visual Studio Code Version :** [ 1.30.2 ] 
🌴 **Code Settings Sync Version :** [ 3.2.4 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **OSS or Portable :** [ OSS ] 
🌴 **Operating System :** [ Windows 10 1809 ] 
🌴 **Occurs On:** [Download & Configuration Change (Force download)]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ 6ba98cc67f24ecc5632c9c993b938e18 ]

📰 **To Reproduce**
Fresh install VSCode after removing all AppData folders relating to VSCode. Fresh install Settings Sync plugin. Enter token and gist. Reload VSCode. No plugins install.
💪 **Expected behavior**
My plugins to install and my settings to take effect (after reload).

📺 **Console Error Log** 
Error after I try to enable force download:
![image](https://user-images.githubusercontent.com/899058/51932395-1b9c3280-23cd-11e9-8337-8158879d69a7.png)

Error when I try and do a normal download: (The console does output all my extensions but it gives those errors first and then gives me the popup to check the error log.)
![image](https://user-images.githubusercontent.com/899058/51932497-471f1d00-23cd-11e9-8338-f7113f633b2e.png)

📺  **Additional context**
Any help would be greatly appreciated.

**Comment by fentas** [comment] 2019-02-01 16:55
same here.

```
$ code --version
1.30.2
61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
x64
$ uname -a
Linux fentas 4.19.16-1-MANJARO #1 SMP PREEMPT Fri Jan 18 17:03:05 UTC 2019 x86_64 GNU/Linux
```

Defeats the purpose of this extension. :crying_cat_face: 
After some debugging i located the error 
```

**Comment by metadiv** [comment] 2019-02-02 11:17
Same issue here on my home computer.

after `Sync : Download Settings`

```
console.ts:134 [Extension Host] HttpError: Not Found
	at module.exports.e.exports.i.fetch.then.n.text.then.n (/Users/Mike/.vscode/extensions/shan.code-settings-sync-3.2.4/out/extension.js:137:45419)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:453
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
````
```
  | t.onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | e.fire | @ | event.ts:228
  | t.notify | @ | notifications.ts:113
  | t.notify | @ | notificationService.ts:52
  | e._showMessage | @ | mainThreadMessageService.ts:83
  | e._showMessage | @ | mainThreadMessageService.ts:44
  | e.$showMessage | @ | mainThreadMessageService.ts:38
  | t._doInvokeHandler | @ | rpcProtocol.ts:461
  | t._invokeHandler | @ | rpcProtocol.ts:446
  | t._receiveRequest | @ | rpcProtocol.ts:366
  | t._receiveOneMessage | @ | rpcProtocol.ts:296
  | (anonymous) | @ | rpcProtocol.ts:171
  | e.fire | @ | event.ts:228
  | a | @ | ipc.net.ts:103
  | n._socketDataListener | @ | ipc.net.ts:132
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js:263
  | readableAddChunk | @ | _stream_readable.js:250
  | Readable.push | @ | _stream_readable.js:208
  | onread | @ | net.js:594
```
```
[Extension Host] Sync : Connected with user : 'metadiv'
```

**Comment by metadiv** [comment] 2019-02-02 17:15
Resolved by adding:
`"sync.gist": "27244cfb3a1902201292eb0e40f8cc5a",` to my settings, where the gist id is taken from the addressbar url when viewing the gist on github

**Comment by shanalikhan** [comment] 2019-02-17 13:49
Currently its facing problems in OSS versions.

**Comment by shanalikhan** [comment] 2019-02-17 13:50
Duplicate of #668

**Closed by shanalikhan** 2019-02-17 13:50 UTC
