### ISSUE TITLE
Create SYNC/GIST on local folder instead of uploading

### ISSUE THREAD

**Issue by dyennam** [shanalikhan/code-settings-sync#525] opened 2018-03-26 19:05 UTC
**Visual Studio Code Version :** [ 1.21.1 ]
**Code Settings Sync Version :** [ 2.9.0 ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [No ]
**GIst Id:** [N/A]

Hello, 
I want to save the created gist / setting outputted file locally. 
I don't have access to push to outside networks (Github), and proxy are disallowed.
Is there a way I can just save the sync settings in my local workspace folder.
I tried all functionalities, and all of them want to upload data to GIST.

Below is the error i get when i try the normal SYNC >> UPLOAD functionality

![image](https://user-images.githubusercontent.com/4074631/37926946-8ac49284-30ed-11e8-9124-4f73a368e17d.png)

**Comment by shanalikhan** [comment] 2018-03-26 21:30
>  Is there a way I can just save the sync settings in my local workspace folder.

Yes it uploads all using github, I have a plan for adding file support in future.

**Comment by shanalikhan** [comment] 2018-03-26 21:30
Duplicate of #256

**Closed by shanalikhan** 2018-03-26 21:30 UTC
