### ISSUE TITLE
Ignore extension if its not existing in the store

### ISSUE THREAD

**Issue by andrey6498** [shanalikhan/code-settings-sync#1241] opened 2020-07-31 21:42 UTC
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :** 1.47.3
🌴 **Code Settings Sync Version :** 3.4.3
🌴 **Standard or Insiders :** Standard
🌴 **Portable or Installed :** Installed
🌴 **OSS or Official Build :** [ _here_ ] 
🌴 **Operating System :** Win7
🌴 **Occurs On:**  Download
🌴 **Proxy Enabled:** No 
🌴 **Gist Id:** a1ddc9fdf7ad3c98929fe8dd1a2b4e77

📰 **To Reproduce**
1.Try to download settings with an invalid entry in json(not existing extension for example)
4. Congratz you're stuck.(or its just in my case)

💪 **Expected behavior**
Download > Ignore entry if invalid
Upload > Remove all invalid entries

📺 **Console Error Log** 
ERR Extension 'PeterJausovec.vscode-docker' not found.: Error: Extension 'PeterJausovec.vscode-docker' not found.
    at handler (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6902:547)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Error: Error: Error: Extension 'PeterJausovec.vscode-docker' not found.    at c:\Users\User\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293    at c:\Users\User\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11611    at Object.throw (c:\Users\User\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11716)    at s (c:\Users\User\.vscode\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:10513)    at processTicksAndRejections (internal/process/task_queues.js:85:5)
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:266

**Comment by andrey6498** [comment] 2020-07-31 21:53
I can surely fix gist manually, but such behaviour is kinda bad anyways. And for multiple entries this thing can possibly become a nightmare.

**Comment by aselhid** [comment] 2020-08-04 08:33
+1 for this. It's cumbersome to manually edit the gist by yourself.

Unrelated point TIL vscode has console error log because of this error 😂

**Comment by tagore-cai** [comment] 2020-08-13 03:19
+1 for this

**Comment by aselhid** [comment] 2020-08-14 05:04
This should be fixed with #1228

**Comment by mediter** [comment] 2020-09-18 01:56
doesn't seem to be fixed yet. the latest version in official vscode marketplace is 3.4.3

waiting for the mentioned fixed version 3.4.4

**Comment by shanalikhan** [comment] 2020-09-24 13:20
Duplicate of #1228

**Closed as completed by shanalikhan** 2020-09-24 13:20 UTC
