### ISSUE TITLE
syncing with my work PC issue

### ISSUE THREAD

**Issue by KwakesProject** [shanalikhan/code-settings-sync#138] opened 2016-11-10 11:35 UTC
**Visual Studio Code Version :** 1.7.1
**Code Sync Settings Version :** 2.3.7
**Operating System :** Window 10
**Occurs On:**  Both Upload / Download
**Proxy Enabled:** Yes 

Hi

I have a MacBook Pro at home and have manged to get the sync working but on my windows work PC i keep getting the error:-

![image](https://cloud.githubusercontent.com/assets/7156996/20175086/00523a1e-a739-11e6-9f8d-5fe79d186bff.png)

![image](https://cloud.githubusercontent.com/assets/7156996/20175110/0e5e63bc-a739-11e6-8d0f-f750e11cfef2.png)

I have reset the settings and even uninstall the extension, removed all the data and reinstalled it but still not working.

can you help me please

**Comment by shanalikhan** [comment] 2016-11-10 15:44
Possible Duplicate Of https://github.com/shanalikhan/code-settings-sync/issues/59.
Please check the solution there and let me know if the error presists. 
Make sure both computer has same token and GIST.

**Comment by KwakesProject** [comment] 2016-11-10 22:15
i followed the solution and the computer has the same token and gist yet still getting the same issue

**Comment by shanalikhan** [comment] 2016-11-14 14:03
are you able to sync the settings at home ? but on work PC its causing problem

So you copy the file *SyncSettings.json* from user folder of working computer PC and paste in user folder in work PC. 
let me know

**Closed** 2016-11-17 19:09 UTC
