### ISSUE TITLE
Add Support for Settings Object and Arrays in Customizable Sync

### ISSUE THREAD

**Issue by rfgamaral** [shanalikhan/code-settings-sync#292] opened 2017-04-11 10:12 UTC
I've read the documentation but I can't seem to understand how to do this...

There's this setting that I need to have the following settings:

**Home:** 

```json
"vscode_custom_css.imports": [
    "file:///C:/Users/HomeUsername/.vscode/ui-theme.css"
]
```

**Work:**

```json
"vscode_custom_css.imports": [
    "file:///C:/Users/WorkUsername/.vscode/ui-theme.css"
]
```

Is this possible with the current version (2.6.2) of this extension?

**Comment by shanalikhan** [comment] 2017-04-11 17:12
For now it only supports the text values of settings file, i will add support for arrays and object.
http://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html

**Comment by rfgamaral** [comment] 2017-04-12 07:55
Still, even if it was just a text value, how can I have 2 different values for each computer? From the docs, I can't understand the configuration needed to make that work.

**Comment by shanalikhan** [comment] 2017-04-12 10:53
In this `syncLocalSettings.json`
in One computer setting set as
```
"replaceCodeSettings": 
    {
        "http.proxy" :"ABC",
     }
``` 

in second computer setting set as
```
"replaceCodeSettings": 
    {
        "http.proxy" :"DEF",
     }
``` 

When you download the setting, the respective value will be replaced in that setting.

**Comment by rfgamaral** [comment] 2017-04-12 10:58
Great. Now I just have to wait for object/array support :)

**Comment by Jasius** [comment] 2017-11-07 14:02
> "replaceCodeSettings":

Couldn't get it to work on my machines.

**Comment by shanalikhan** [comment] 2018-09-04 21:34
This feature will be removed in the future updates.
Settings Sync will have new way for customizing #555  configurations.

**Comment by shanalikhan** [comment] 2018-09-04 21:34
Duplicate of #555

**Closed by shanalikhan** 2018-09-04 21:34 UTC
Labels: feature-request
