### ISSUE TITLE
 Extension Fails on Insiders and Mac

### ISSUE THREAD

**Issue by listenlin** [shanalikhan/code-settings-sync#618] opened 2018-08-27 03:49 UTC
🐛 **Describe the bug**  
When sync download, all extensions sync failed, other config sync success.

🌴 **Visual Studio Code Version : 1.26.1
🌴 **Code Settings Sync Version :3.1.0
🌴 **Operating System : Mac 10.13.6
🌴 **Occurs On: Download 
🌴 **Proxy Enabled:  No
🌴 **Gist Id: 318aa8a0e3558149e9e90f153b44ee21

📰 **To Reproduce**
1. open vscode
2. press Shift + Alt + D

💪 **Expected behavior**
All extensions sync success.

📺 **Console Error Log** 
```

CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.1.0
--------------------
GitHub Token: ******
GitHub Gist: 318aa8a0e3558149e9e90f153b44ee21
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindingsMac.json
  material-icon-theme.json > material-icon-theme.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.

```

📺  **Additional context**
extension-output.log

```
CODE SETTINGS SYNC - COMMAND LINE EXTENSION DOWNLOAD SUMMARY
Version: 3.1.0
--------------------
TOTAL EXTENSIONS : 24


"bin//code" --install-extension debian001.app-migrator
Error: Command failed: "bin//code" --install-extension debian001.app-migrator
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension HookyQR.beautify
Error: Command failed: "bin//code" --install-extension HookyQR.beautify
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension EditorConfig.EditorConfig
Error: Command failed: "bin//code" --install-extension EditorConfig.EditorConfig
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension donjayamanne.githistory
Error: Command failed: "bin//code" --install-extension donjayamanne.githistory
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension cesium.gltf-vscode
Error: Command failed: "bin//code" --install-extension cesium.gltf-vscode
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension SirTori.indenticator
Error: Command failed: "bin//code" --install-extension SirTori.indenticator
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension dollyn.line-counter
Error: Command failed: "bin//code" --install-extension dollyn.line-counter
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension PKief.material-icon-theme
Error: Command failed: "bin//code" --install-extension PKief.material-icon-theme
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension ionutvmi.path-autocomplete
Error: Command failed: "bin//code" --install-extension ionutvmi.path-autocomplete
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension felixfbecker.php-debug
Error: Command failed: "bin//code" --install-extension felixfbecker.php-debug
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension neilbrayfield.php-docblocker
Error: Command failed: "bin//code" --install-extension neilbrayfield.php-docblocker
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension felixfbecker.php-intellisense
Error: Command failed: "bin//code" --install-extension felixfbecker.php-intellisense
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension ikappas.phpcs
Error: Command failed: "bin//code" --install-extension ikappas.phpcs
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension pnp.polacode
Error: Command failed: "bin//code" --install-extension pnp.polacode
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension mohsen1.prettify-json
Error: Command failed: "bin//code" --install-extension mohsen1.prettify-json
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension sidmishraw.topper
Error: Command failed: "bin//code" --install-extension sidmishraw.topper
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension dushaobindoudou.translation
Error: Command failed: "bin//code" --install-extension dushaobindoudou.translation
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension octref.vetur
Error: Command failed: "bin//code" --install-extension octref.vetur
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension PeterJausovec.vscode-docker
Error: Command failed: "bin//code" --install-extension PeterJausovec.vscode-docker
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension dbaeumer.vscode-eslint
Error: Command failed: "bin//code" --install-extension dbaeumer.vscode-eslint
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension wix.vscode-import-cost
Error: Command failed: "bin//code" --install-extension wix.vscode-import-cost
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension DavidAnson.vscode-markdownlint
Error: Command failed: "bin//code" --install-extension DavidAnson.vscode-markdownlint
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension cssho.vscode-svgviewer
Error: Command failed: "bin//code" --install-extension cssho.vscode-svgviewer
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension minhthai.vscode-todo-parser
Error: Command failed: "bin//code" --install-extension minhthai.vscode-todo-parser
/bin/sh: bin//code: No such file or directory


```

**Comment by shanalikhan** [comment] 2018-08-27 06:49
Please share the developer console image after download summay appears

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by borekb** [comment] 2018-08-28 04:51
I also observe this on Windows – extensions are not installed despite having a list of 6 extensions in `extensions.json` and only three extensions installed locally.

```
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```

**Comment by shanalikhan** [comment] 2018-08-28 08:56
@borekb can you share your gist ID with console logs.

**Comment by shanalikhan** [comment] 2018-08-28 08:57
**for Mac Users**
I know there will be a problem as i cant test extension there, what i need from you guys to provide me developer console log so i can evaluate and release new build in this week to fix this major bug

**Comment by borekb** [comment] 2018-08-28 09:08
Which logs are you interested in? Those from **Help** > **Toggle Developer Tools**?

It's this in my case (the only log message there related to your extension seems to be the last line):

```
INFO no standard startup: not a new window
console.ts:136 [Extension Host] Git extension API method 'getGitPath' is deprecated. (at c.r.value (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:594547))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:411
(anonymous) @ extensionHost.ts:223
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] rejected promise not handled within 1 second (at Timeout._onTimeout (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:847:591))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:411
(anonymous) @ extensionHost.ts:223
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
mainThreadExtensionService.ts:43 [TomasHubelbauer.vscode-markdown-link-suggestions]URI malformed
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
mainThreadExtensionService.ts:44 URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Function.e.parse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46:821)
	at getFileLinks (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:388:38)
	at getFileLinks.next (<anonymous>)
	at LinkDiagnosticProvider.provideDiagnostics_1 (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:103:24)
	at provideDiagnostics_1.next (<anonymous>)
	at resume (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:16:44)
	at /Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:15:121
	at new Promise (<anonymous>)
	at Object.i.(anonymous function) [as next] (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:15:63)
	at /Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:416:106
	at Generator.next (<anonymous>)
	at /Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:3:12)
	at drainAsyncIterator (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:413:12)
	at LinkDiagnosticProvider.<anonymous> (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:96:58)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/borekb/.vscode-insiders/extensions/tomashubelbauer.vscode-markdown-link-suggestions-11.0.0/out/extension.js:4:58)
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
console.ts:136 [Extension Host] Sync : Connected with user : 'borekb' (at GitHubService.github.users.get.then.res (/Users/borekb/.vscode-insiders/extensions/shan.code-settings-sync-3.1.0/out/src/service/githubService.js:76:25))
```

This is VSCode insiders on a Mac:

Version: 1.27.0-insider
Commit: 43676d0cb7db94e2fa771f1d10bff10eaa01b453
Date: 2018-08-28T05:12:24.162Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by borekb** [comment] 2018-08-28 09:11
Actually, no, sorry, there is one more message at the end of the log. It ends like this:

```
[Extension Host] Sync : Connected with user : 'borekb' (at GitHubService.github.users.get.then.res (/Users/borekb/.vscode-insiders/extensions/shan.code-settings-sync-3.1.0/out/src/service/githubService.js:76:25))
console.ts:136 [Extension Host] /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper (at Function.<anonymous> (/Users/borekb/.vscode-insiders/extensions/shan.code-settings-sync-3.1.0/out/src/service/pluginService.js:214:21))
```

**Comment by borekb** [comment] 2018-08-28 09:12
Gist: https://gist.github.com/borekb/a721a8afc32b82128e71c712a8dfb357

**Comment by shanalikhan** [comment] 2018-08-28 09:32
![screenshot from 2018-08-28 14-28-51](https://user-images.githubusercontent.com/8774556/44714438-c3d06700-aace-11e8-9735-37408c631a56.png)

These are the logs in Linux.
You can see upon downloading, besides showing the connection with github. It shows the **code location** - In my case its `usr/share/code/code`

It need to know this on Mac. I think its missing over there in your side.

**Comment by borekb** [comment] 2018-08-28 11:33
Correct, I don't see any "COMMAND LINE EXTENSION DOWNLOAD SUMMARY". This is what I see:

![image](https://user-images.githubusercontent.com/101152/44720074-df833f80-aac5-11e8-9bcc-b95d4a510c75.png)

I also _don't_ see similar line to your first line in the Dev Tools.

This is in my user `settings.json`:

```
    "sync.gist": "a721a8afc32b82128e71c712a8dfb357",
    "sync.quietSync": false,
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.forceDownload": true,
```

And this is in my "global" sync settings (`/Users/borekb/Library/Application Support/Code - Insiders/User/syncLocalSettings.json`):

```
{
    "ignoreUploadFiles": [
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "replaceCodeSettings": {},
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 310,
    "token": "...",
    "downloadPublicGist": false,
    "supportedFileExtensions": [
        "json",
        "code-snippets"
    ],
    "openTokenLink": true,
    "useCliBaseInstallation": true,
    "lastUpload": "2018-08-28T09:13:13.287Z",
    "lastDownload": "2018-08-28T09:13:13.287Z",
    "githubEnterpriseUrl": null,
    "askGistName": false
}
```

**Comment by borekb** [comment] 2018-08-28 13:17
I don't see it at all, not even for split second.

The original post also mentions file called `extension-output.log`, I've searched by entire hard drive but didn't find anything like that.

Is there a persistent location where I could find the "COMMAND LINE EXTENSION DOWNLOAD SUMMARY"?

**Comment by borekb** [comment] 2018-08-28 13:17
By the way, I observed the same on Windows. I'm not at my Windows computer at the moment but I don't think this issue is Mac-only.

**Comment by shanalikhan** [comment] 2018-08-28 13:33
> I also observe this on Windows – extensions are not installed despite having a list of 6 extensions in extensions.json and only three extensions installed locally.

Alright, thats why there might be some problem you are facing in Windows also.

> The original post also mentions file called extension-output.log, I've searched by entire hard drive but didn't find anything like that.

No, actually it keeps writing until the all the extension downloads completes, upon installation completion this output summary is replace by the download summary.

I will look into it that why its not appearing in windows, as currently i have linux in my office and it shows the download summary.

**Comment by borekb** [comment] 2018-08-28 13:42
Just so that there is no misunderstanding, I observe the same behavior on both MacOS (10.13.6) and Windows 10 Pro (April 2018 Update).

Thanks for looking into it!

**Comment by kbd** [comment] 2018-08-28 18:36
Since the current version of the extension is broken, could you re-publish the prior version? Is there any way to install the old version? Trying to set up a new work computer and this is very frustrating.

**Comment by borekb** [comment] 2018-08-28 20:30
On Windows, the dev tools console looks slightly different:

![image](https://user-images.githubusercontent.com/101152/44749083-d1f3a700-ab11-11e8-8bb8-0a0f2100f771.png)

Other than that, the result is the same (same output in the Output panel as in https://github.com/shanalikhan/code-settings-sync/issues/618#issuecomment-416551334 and no extensions installed).

**Comment by listenlin** [comment] 2018-08-29 03:16
My developer console output is:
```

[Extension Host] Sync : Connected with user : 'listenlin'
console.ts:136 [Extension Host] /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
```

@borekb  that the 'extension-outout.log' file is located at /Users/username/Library/Application Support/Code/logs/20180829T105700/output_1_20180829T110129/extension-output-#3.log

**Comment by dkblay** [comment] 2018-08-29 07:52
I am currently facing the same issue on MacOS (10.13.6). All extensions aren't installed

**Comment by shanalikhan** [comment] 2018-08-29 09:05
alright, can you guys tell me what is the path for 'code' environment variable in Mac?

**Comment by shanalikhan** [comment] 2018-08-29 10:02
I have fixed for Insiders for Windows and Linux.
I couldnt test for mac last time due to unavailability, and thats why i mentioned on release notes that i need to add mac users.

For this i need 
1. mac code executable app absolute path.
2. mac code environment absolute path.

For both standard and insiders.

**Comment by MirkoLenz** [comment] 2018-08-29 10:05
Below is the output of `which code` on my mac:

```
/usr/local/bin/code
```

As far as I know, `code-insiders` is in the same directory.
However, as I do not have the Insiders version installed, I cannot test it.

What do you mean with the second point: Mac code environment absolute path?

**Comment by listenlin** [comment] 2018-08-29 12:14
Mac code executable app absolute path:

/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

**Comment by shanalikhan** [comment] 2018-08-29 12:38
Actually for Linux the code executable and environement path are following:
Executable : `/usr/share/code/code'

shell script - enrironment path - '/usr/share/code/bin/code`

In short, there is difference of bin folder
Similarly its the pattern for Windows also.

> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

This might be the script path for code, when you just run "code" on command it will run this script that opens up the application.
@listenlin can you share the screen shot of 

/Applications/Visual Studio Code.app/Contents/Resources/app/
and 
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/


@MirkoLenz whats in your 
/usr/local/bin/
and 
/usr/local/

**Comment by MirkoLenz** [comment] 2018-08-29 12:44
`/usr/local/` only contains folders:

```
Caskroom
Cellar
Frameworks
Homebrew
bin
etc
include
lib
opt
sbin
share
texlive
var
```

`/usr/local/bin/` is used by Homebrew and other 3rd parties to install apps. On my system, all CLI apps that are not supplied by Apple are in this folder. Because of that, I think it is not necessary to include the contents of this folder here.

Nevertheless, the `code` command is in my PATH which means that it can also be run without using the absolute path.

**Comment by BennyHarv3** [comment] 2018-08-29 16:27
If anybody needs a workaround for a new machine, I used this one-liner Bash command to read the `extensions.json` file and install everything. It requires the following:

1.  VS Code's `code` available on your `$PATH`,
1.  The [JMESPath](http://jmespath.org/) [`jp` tool](https://github.com/jmespath/jp) installed, which is a JSON parser (feel free to replace with your favorite tool), and
1.  The `extensions.json` file somewhere on your machine available to read.

`for (( c=0; c<$(jp -f extensions.json "length([])"); c++)); do code --install-extension $(jp -f extensions.json -u "join('.', [$c].[publisher, name])"); done`

This doesn't fix the extension in any way, but if you need to setup a new machine and move on, it'll do the job.

**Comment by BennyHarv3** [comment] 2018-08-29 16:27
P.S. Thanks for this extension! I've been using it for at least a year to keep various machines in sync, and it's been a real life saver.

**Comment by shanalikhan** [comment] 2018-08-29 21:59
v3.1.1 released.

Please report.

**Comment by beeblebrox3** [comment] 2018-08-30 00:05
For me is not working. Linux with vscode insiders.

``` 
Error: ENOENT: no such file or directory, mkdir '/tmp/tmp/118729-32091-wk6aia.pq8y118729-32091-1mn18uk.p0nq' (at actionList.push.PluginService.InstallExtension.then (/home/luis/.vscode-insiders/extensions/shan.code-settings-sync-3.1.1/out/src/service/pluginService.js:295:29))
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180

```
Based on this message, I create the "tmp" directory inside "/tmp". Worked fine after that

**Comment by felipeauol** [comment] 2018-08-30 01:42
Worked for me on vscode macos

**Comment by borekb** [comment] 2018-08-30 05:59
Didn't work on Windows & VSCode Insiders. The only output I get is:

```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.1.1
--------------------
GitHub Token: 82bf371bcbad64b60566d2c425e01325535d2467
GitHub Gist: a721a8afc32b82128e71c712a8dfb357
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```

**Comment by borekb** [comment] 2018-08-30 06:01
Oh wait it actually worked this time! I'll try to restart VSCode Insiders a couple of times to see if I can repeat that.

**Comment by borekb** [comment] 2018-08-30 06:10
Ok, so:

## VSCode stable version on Windows

This seems to work entirely correctly. I was missing one extension, I could briefly see that some command-line command is being issued, installing the missing extension, and the eventual summary mentioned that 1 extension has been installed. Good.

Two suggestions here:

1. In the output, keep the initial output of the CLI command. It would be easier to report any issue with that.
2. I needed to manually reload the window to see the newly installed extension. There should be a notification or something like that, prompting for reload.

## VSCode Insiders (1.27) on Windows

Same testing scenario, i.e., one extension missing.

I could see the temporary output with CLI command just fine and the extension is technically installed, however, the final summary still says:

```
Extensions Added:
  No extensions installed.
```

Other than that, it behaves the same as VSCode stable.

Thanks for your fix!

**Comment by MirkoLenz** [comment] 2018-08-30 06:39
On my setup (macOS and the regular VSCode releases) everything works as expected with the new version. Thank you!

**Comment by kieronlanning** [comment] 2018-08-30 07:44
I get nothing synchronised on Windows v1.26.1.

```Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.```

**Comment by shanalikhan** [comment] 2018-08-30 09:06
Alright, Let me explain in single post:

MacOS : VS Code - ✅
MacOS : VS Code Insiders - ✅

Windows : VS Code - ✅
Windows : VS Code Insiders - ❎ 

Linux : VS Code - ✅
Linux :  VS Code Insiders - ❎ 

@borekb and @beeblebrox3  can you please create new issue with the suggestions and unexpected behavior. 
I will release v3.1.2 later this week fixing them.

I'm going to close this issue.

**Closed** 2018-08-30 09:07 UTC
Labels: bug

**Comment by borekb** [comment] 2018-08-30 12:00
@shanalikhan Thanks, done that in #628 and #629.

**Comment by borekb** [comment] 2018-08-30 12:31
By the way, I'm on macOS with VSCode Insiders and unfortunately, the issue is not gone. I have 6 extensions installed locally, 7 extensions in the downloaded `extensions.json` and the seventh one is not installed. I see no error or anything.

**Comment by shanalikhan** [comment] 2018-08-30 12:57
hmm, alright can you paste the 7 extensions downloading summary text?
I need to see what command line display on the 7th extension unlike installing 6 other extensions correctly.

**Comment by borekb** [comment] 2018-08-30 13:03
I already had those 6 installed locally before invoking sync. The sync was supposed to install the seventh one but didn't do anything instead, it just printed

```
...
Extensions Added:
  No extensions installed.
```

I also didn't see [this](https://github.com/shanalikhan/code-settings-sync/issues/628) even for a short while.

**Comment by StevenChin** [comment] 2018-08-30 18:09
Still not able to install extensions. I'm using VSCode on macOS 10.13.6. Before updating to 3.1.1, these were the extension output logs:

```
CODE SETTINGS SYNC - COMMAND LINE EXTENSION DOWNLOAD SUMMARY
Version: 3.1.0
--------------------
TOTAL EXTENSIONS : 23


"bin//code" --install-extension formulahendry.auto-close-tag
Error: Command failed: "bin//code" --install-extension formulahendry.auto-close-tag
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension formulahendry.auto-rename-tag
Error: Command failed: "bin//code" --install-extension formulahendry.auto-rename-tag
/bin/sh: bin//code: No such file or directory


"bin//code" --install-extension formulahendry.code-runner
Error: Command failed: "bin//code" --install-extension formulahendry.code-runner
/bin/sh: bin//code: No such file or directory
...
```

```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.1.0
--------------------
GitHub Token: 7587efae0c1888fae941f9c5619ea5542c7553d0
GitHub Gist: 738c5bee405bb4df429466e7d9bbddf8
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindingsMac.json
  settings.json > settings.json
  vsicons.settings.json > vsicons.settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```

After updating to 3.1.1, here are the logs:

```
CODE SETTINGS SYNC - COMMAND LINE EXTENSION DOWNLOAD SUMMARY
Version: 3.1.1
--------------------
```

```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 3.1.1
--------------------
GitHub Token: 7587efae0c1888fae941f9c5619ea5542c7553d0
GitHub Gist: 738c5bee405bb4df429466e7d9bbddf8
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindingsMac.json
  settings.json > settings.json
  vsicons.settings.json > vsicons.settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```

**Comment by shanalikhan** [comment] 2018-08-30 21:48
@StevenChin are you using insiders version or standard version in mac os?
It's working for Standard Code versions for Mac as by @felipeauol and @MirkoLenz 

P.S: Never post your GitHub token, I have removed your token but it still can be seen, also you should remove this token from your GitHub profile.

**Comment by StevenChin** [comment] 2018-08-30 22:51
@shanalikhan I really appreciate the heads up, hadn't noticed the token was in the output 😓. I've also removed the token from my profile.

> are you using insiders version or standard version in mac os? It's working for Standard Code versions for Mac as by @felipeauol and @MirkoLenz

I'm using the standard VS Code, version `1.26.1`. I was hoping the issue would have been resolved based on those reports, however, it still doesn't work for me.

**Comment by shanalikhan** [comment] 2018-08-30 23:17
Okay, guys, I need PR from Mac users to fix it.
Can't test Mac extension problems due to unavailability of an environment. 
I can only test in Windows and Ubuntu, next version will be released in day or two fixing windows and Linux problems.

I can assist if someone is willing to help and identify the bugs in Mac.

**Comment by StevenChin** [comment] 2018-08-31 01:01
@shanalikhan I could take a stab at it. Lemme know where to start.

**Comment by StevenChin** [comment] 2018-09-04 03:15
@shanalikhan sorry for the late reply on this, but I look a deeper look into the issue today and it turns out that I got my gist messed up. The version of the gist I was downloading didn't have my extensions. I was able to recover my original settings and re-synced everything. Really appreciate the fast turnaround time on this, you're a lifesaver! ❤️
