### ISSUE TITLE
Uninstalls installed Extensions

### ISSUE THREAD

**Issue by ibrokemypie** [shanalikhan/code-settings-sync#761] opened 2019-02-06 06:29 UTC
🐛 **Describe the bug**  
When installed, after you install new extensions and reload, all the extensions then get uninstalled.

🌴 **Visual Studio Code Version :**  1.30.2
🌴 **Code Settings Sync Version :** 3.2.3
🌴 **Standard or Insiders :** Standart
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** macOs
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** no
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
1. Set up extensions
2. Enable auto download and upload
3. Install some other extensions
4. Reload

💪 **Expected behavior**
New extensions persist

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.

📺  **Additional context**

**Comment by shanalikhan** [comment] 2019-02-17 13:47
Duplicate of #396

**Closed by shanalikhan** 2019-02-17 13:47 UTC
