### ISSUE TITLE
not work with vscode-portable

### ISSUE THREAD

**Issue by CyrilTaylor** [shanalikhan/code-settings-sync#658] opened 2018-09-24 13:06 UTC
🐛 **Describe the bug**  
not work with [vscode-portable](https://github.com/myfreeer/vscode-portable)

🌴 **Visual Studio Code Version :** All 
🌴 **Code Settings Sync Version :** All
🌴 **Operating System :** Win10
🌴 **Occurs On:** [Upload / Download  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:**

**Comment by shanalikhan** [comment] 2018-09-24 13:07
Duplicate of #331

**Closed by shanalikhan** 2018-09-24 13:07 UTC
