### ISSUE TITLE
High Startup Activation Time

### ISSUE THREAD

**Issue by johannes-z** [shanalikhan/code-settings-sync#497] opened 2018-02-14 12:40 UTC
**Visual Studio Code Version :** 1:20.0
**Code Settings Sync Version :** 2.8.7
**Operating System :** Windwos 10
**Occurs On:** Startup
**Proxy Enabled:** No
**GIst Id:** Not relevant

I recently took a look at the running extensions page of vs code and noticed, that settings sync by far exceed every other extension's startup activation time. I have every setting of `settings sync` that would automatically do *anything* on `false`, so it's not downloading, uploading or checking if there is a new configuration (or at least it shouldn't). See image:

![image](https://user-images.githubusercontent.com/9069888/36204635-504cddda-118c-11e8-9854-7978b9827611.png)

**Comment by shanalikhan** [comment] 2018-02-16 09:44
Duplicate of #472

**Comment by shanalikhan** [comment] 2018-02-16 09:44
Feel free to discuss it there.

**Closed by shanalikhan** 2018-02-16 09:44 UTC
