### ISSUE TITLE
Custom Extension

### ISSUE THREAD

**Issue by Moraledalx** [shanalikhan/code-settings-sync#1086] opened 2019-11-20 06:46 UTC
Hello,

I wrote a couple of very simple extension which are then located in the user folder of vscode. The upload/download indeed list the extention but does not seem to actually upload the files.
I suppose it's because it's not an actual marketplace extension so it cannot be downloaded from there ?

I saw the possibility to specify custom sync file, however i am wondering if it can be used across multiple machines (including multiple OS) since the absolute path of those files are likely to differ.
Could this usecase be done ?

Tx for the help.

**Comment by shanalikhan** [comment] 2019-11-21 10:18
>  I suppose it's because it's not an actual marketplace extension so it cannot be downloaded from there.

Yes, you are right. There is already issues opened to support custom extension offline.

**Comment by shanalikhan** [comment] 2019-11-21 10:19
Duplicate of #778

**Closed as completed by shanalikhan** 2019-11-21 10:19 UTC

**Comment by Moraledalx** [comment] 2019-11-21 10:23
Thank you for your reply.
