### ISSUE TITLE
visual studio Code download error

### ISSUE THREAD

**Issue by wahahaJack** [shanalikhan/code-settings-sync#142] opened 2016-11-14 13:30 UTC
**Visual Studio Code Version :latest
**Code Sync Settings Version :v2.3.8
**Operating System : window10
**Occurs On: Download
**Proxy Enabled:** No

[Extension Host] Windows_NT
2workbench.main.js:121 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}I.logExtensionHostMessage @ workbench.main.js:121
workbench.main.js:90 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

**Comment by shanalikhan** [comment] 2016-11-14 13:55
> {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}I.logExtensionHostMessage @ workbench.main.js

Possible duplicate of https://github.com/shanalikhan/code-settings-sync/issues/59
Check the solution there

**Closed** 2016-11-15 20:34 UTC
Labels: question
