### ISSUE TITLE
Custom repository suggestion

### ISSUE THREAD

**Issue by YeeP79** [shanalikhan/code-settings-sync#731] opened 2018-12-10 15:29 UTC
💡 **Is your feature request related to a problem? Please describe.**
My company does not allow us to sync code (gist or repo) with github.com

💡 **Describe the solution you'd like**
We have Gitlab implemented on our internal network, it would be great if I could adjust the settings for the extension to specify using the internal Gitlab I do have access to.

💡 **Additional context**
Awesome extension, I love it!

**Comment by shanalikhan** [comment] 2018-12-10 15:30
Duplicate of #413

**Closed by shanalikhan** 2018-12-10 15:30 UTC

**Comment by YeeP79** [comment] 2018-12-10 15:34
Thank you, my search parameters did not lead me to the already existing issue. My mistake.
