### ISSUE TITLE
Support For GHE

### ISSUE THREAD

**Issue by charbel14** [shanalikhan/code-settings-sync#211] opened 2017-02-11 19:33 UTC
Hi,

The current github service only works for the public github. To make it work for the enteprise the host needs to be configrable and the pathPrefix. This should be a good and easy enhacment to have. I did not look at how you expect to read such configuration - but I believe should be easy enough to expose that somewhere.

```
github = new GitHubApi({
    host: "<enterprise-host>",
    proxy: proxyURL,
    pathPrefix: "/api/v3",
    version: "3.0.0",
});
```

**Comment by shanalikhan** [comment] 2017-02-11 20:28
its a duplicate of https://github.com/shanalikhan/code-settings-sync/issues/67
Thanks,  would you please provide an multiple examples about `host` property and `pathPrefix` so i can understand it better. Public host will only contain `host:github.com` ?

**Comment by charbel14** [comment] 2017-02-11 21:34
The enterprise host would be something like github.companyname.com .

Prefix is /api/v3

Two ways to do this :
If configured you can use, else omit and keep existing functionality as is.


Or I need to dig up the public git details when I get the chance.  I think
it is api.github.com and probably same prefix.  Need to test.

I will get back to you when I get chance.


On Feb 11, 2017 15:28, "Shan Khan" <notifications@github.com> wrote:

its a duplicate of #67
<https://github.com/shanalikhan/code-settings-sync/issues/67>
Thanks, would you please provide an multiple examples about host property
and pathPrefix so i can understand it better. Public host will only contain
host:github.com ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shanalikhan/code-settings-sync/issues/211#issuecomment-279173403>,
or mute the thread

**Comment by charbel14** [comment] 2017-02-11 21:41
Public host is api.github.com,  prefix is empty string.

**Comment by charbel14** [comment] 2017-02-12 02:18
The change to introduce these values may impact some menus. i.e. Upload to public or where ever public is mentioned...

I would probably add the json payload of  githubservice in your settings files. This will give you felxibility  to simply feed in whatever github module takes without a code change.

One more thing I should add - The settings.json file contains a couple of properties lastupload and lastdownload. The initial values are null. If you upload from one machine and try to download into another they will throw an error in extension.js line 268/269 ...  I had to put a default dummt dates there to get it going.

Is it possible to copy the history too? i.e. recently opened and the state of what is already opened and the unsaved files. Not sure how Code keeps this info.

**Comment by shanalikhan** [comment] 2017-02-12 08:46
Thanks, will look into this in upcoming versions

**Closed** 2017-02-12 08:45 UTC
Labels: duplicate
