### ISSUE TITLE
Sync not happening

### ISSUE THREAD

**Issue by stevenbaert** [shanalikhan/code-settings-sync#790] opened 2019-03-06 09:56 UTC
Hi,

I have installed Sync in Visual Code and was able to succesfully upload settings (machine01), then tried on another machine (machine02) and configured Sync again. No errors but Sync does not come through (machine02)

Upload on machine01 was ok:
--------------------
Files Uploaded:
  extensions.json > extensions.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.

Machine02 doesn't show output though I have enabled it (toggle show summary).
When downloading settings, it says
Sync: you already have latest version ... but no extensions or config appears.

Please advise.

**Comment by shanalikhan** [comment] 2019-03-06 09:57
please use the proper issue format while posting issue so i know all the details.

**Comment by stevenbaert** [comment] 2019-03-06 10:56
What is the "proper issue format" (what input do you expect from me)?

**Comment by shanalikhan** [comment] 2019-03-06 11:00
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.


🌴 **Visual Studio Code Version :** [ VERSION_HERE ] 
🌴 **Code Settings Sync Version :** [ VERSION_HERE ] 
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [ VERSION_HERE ] 
🌴 **Occurs On:** [Upload / Download / Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [ ID_HERE ]



📰 **To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by LuisUrrutia** [comment] 2019-03-06 11:02
Related to #789

**Comment by shanalikhan** [comment] 2019-03-06 12:51
Duplicate of #789

**Closed by shanalikhan** 2019-03-06 12:51 UTC
