### ISSUE TITLE
GitHub Enterprise Issue

### ISSUE THREAD

**Issue by tibmeister** [shanalikhan/code-settings-sync#973] opened 2019-07-19 20:35 UTC
🐛 **Describe the bug**  
When trying to sync to GitHub Enterprise, receiving an error of HttpError.  Looking at the Developer Tools -> Console only has the following information:

[Extension Host] HttpError    at module.exports.then.t.text.then.t (c:\Users\tibmeister\.vscode\extensions\shan.code-settings-sync-3.4.0\out\extension.js:767:736)    at process._tickCallback (internal/process/next_tick.js:68:7)

Would be happy to provide more logging if I knew where it was.

🌴 **Visual Studio Code Version :** 1.36.1
🌴 **Code Settings Sync Version :** 3.4.0
🌴 **Standard or Insiders :** Standard 
🌴 **Portable or Installed :** User Setup 
🌴 **OSS or Official Build :** Official Build 
🌴 **Operating System :** Windows 10 1903 
🌴 **Occurs On:** Help Configuring
🌴 **Proxy Enabled:** No
🌴 **Gist Id:**

**Comment by naikrovek** [comment] 2019-08-08 13:15
I have the exact same issue.

Viewing the Electron console logs will get you more error detail.  In VS Code: Help > Toggle Developer Tools

**Comment by adschw1** [comment] 2019-09-05 13:51
Bump, having this exact same issue. It appears to be calling the wrong URL. For instance:
Expected: `https://github.enterprise.com/gist/user/gist-id`
Actual: `https://github.enterprise.com/gists/gist-id`

`github.enterprise.com/gists` automatically redirects to `github.enterprise.com/gist` but when you start adding on `/gist-id` you start running into 404's

**Comment by naikrovek** [comment] 2019-09-05 18:09
Ok, all three of us work for the same company and I'm 100% sure that our issues are caused completely by our employer's ... unique way of handling infrastructure decisions.  

This issue can probably be closed, and can certainly be safely ignored so long as it's just the three of us who have commented.

**Comment by shanalikhan** [comment] 2019-09-06 04:26
Yes, the issue is opened since July. No one from another company has reported this. It is safe to close this issue.
Thanks

**Closed by shanalikhan** 2019-09-06 04:26 UTC
