### ISSUE TITLE
Could Sync support the portable mode of Code 1.25 ?

### ISSUE THREAD

**Issue by waiaan** [shanalikhan/code-settings-sync#579] opened 2018-07-06 01:37 UTC
**Is your feature request related to a problem? Please describe.**

The Code of ver 1.25 now has portable mode, when I enable the portable ,the Sync still download the settings/extens to userdata folder instead of the data folder within Code's folder.  
Could it be fixed?
Thank you !

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by linsui** [comment] 2018-07-06 05:54
> "command 'extension.downloadSettings' not found"

 when I download setting with portable mode

**Comment by grapehunter** [comment] 2018-07-06 17:52
1. Vscode supports portable mode since v1.25.
In windows, you can simply make a dir named `data` to enable portable mode , and all user data and extension will be placed in here.
2. As @waiaan said , in portable mode , the setting sync will cause an exception with message `command 'extension.downloadSettings' not found`.
3. Now in dev tool, we can see the `c:\users\name\appdata\roaming\code\user\sync.lock` not found

**Comment by shanalikhan** [comment] 2018-07-06 21:39
Yes, it would be great if you can send me Pull Request
I will release v3.0.0 with this feature.

**Comment by shanalikhan** [comment] 2018-07-06 21:40
Duplicate of #331

**Closed by shanalikhan** 2018-07-06 21:40 UTC
