### ISSUE TITLE
Join keybindings & keybindingsMac json files

### ISSUE THREAD

**Issue by SlavDimov** [shanalikhan/code-settings-sync#699] opened 2018-10-26 09:45 UTC
💡 **Is your feature request related to a problem? Please describe.**
I own a Mac and a PC and i regularly have to switch between them, for which I use this awesome extension to keep my VS Code synced, however I noticed that when the extension syncs keybindings, it uploads them to the gist as KeybindingsMac.json (when on a Mac), instead of Keybindings.json (as it is on a PC, and in VS Code). I get that since most of the keybindings on a Mac are different than the ones on a PC, this was necessary, but since the last few updates of VS Code, one can now set up when a keybinding should be valid with the OS variables. For example:

```
{
        "key": "ctrl+i",
        "command": "editor.action.transformToLowercase",
        "when": "editorTextFocus && !isMac",
    },
{
        "key": "cmd+i",
        "command": "editor.action.transformToLowercase",
        "when": "editorTextFocus && isMac",
    },
```
More info on that is available on the [VS Code website](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts).

💡 **Describe the solution you'd like**
I would like that feature to be removed from the extension, or If there are people that still prefer the keybindings separate, then to have a flag somewhere that can trigger it on/off.

Thanks!

**Comment by shanalikhan** [comment] 2018-10-26 09:46
Duplicate of #515

**Closed** 2018-10-26 09:46 UTC
