### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by iamluodong** [shanalikhan/code-settings-sync#66] opened 2016-08-17 13:41 UTC
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Sync Settings Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]

Please make sure to write the versions and console logged error picture or copied text.
![image](https://cloud.githubusercontent.com/assets/4755525/17738292/3cf6b75a-64c3-11e6-8708-5701735903b2.png)

**Comment by shanalikhan** [comment] 2016-08-17 13:43
Duplicate of [#59](https://github.com/shanalikhan/code-settings-sync/issues/59).
> this is due to invalid gist ID. please reset the settings by sync reset settings command and then again try to download.

**Closed by shanalikhan** 2016-08-17 13:43 UTC
Labels: duplicate, question

**Comment by iamluodong** [comment] 2016-08-17 14:10
OK ,sync ok.
