### ISSUE TITLE
Choice between GitHub Gist or GitLab Snippet?

### ISSUE THREAD

**Issue by chris-c-thomas** [shanalikhan/code-settings-sync#443] opened 2017-11-06 18:56 UTC
I realize this is me being very particular but just curious how hard this would be? I'm itching to move everything over from GitHub to GitLab for myself and if I could maintain all my Gists over there that'd be great too.

I'm also intrigued by this idea: https://github.com/shanalikhan/code-settings-sync/issues/413 in regards to backing up to a repo instead of a Gist. In that case, could we select between GitHub, GitLab, BitBucket, etc ?

**Comment by dylanh724** [comment] 2017-11-25 14:59
I'd like this. GitLab is superior with all their features, usability, unlimited private repos, 10gb free, etc etc.

**Comment by carlos-algms** [comment] 2017-12-14 20:11
Please, if it is possible, don't forget to allow private corporate gitlab as well.

**Comment by fnkr** [comment] 2018-09-10 08:34
GitLab Snippets are not versioned. I would rather sync with a GitLab repository instead. I think it would be better if setting-sync would gain the ability to sync with an arbitrary Git repository instead of creating more vendor-specific implementations for syncing.

**Comment by shanalikhan** [comment] 2018-09-20 10:14
it's better to sync with the repository.
1. Github Gist
2. Repository [ Mainly support, Github and GitLab ]

See the feature here available for bounty. #EarnAndFix

https://github.com/shanalikhan/code-settings-sync/issues/413

**Comment by connorshea** [comment] 2018-12-02 21:51
Snippets also don’t support more than one file, so using GitLab snippets would require some really weird compromises.

**Comment by v6** [comment] 2019-05-29 21:38
Also, the "private gist" sharing via a link is not available on GitLab.

**Comment by simonwiles** [comment] 2019-06-21 23:17
Am I the only one who just wants to do this via local files that I can sync/copy/upload/download/check-in/check-out however I please?

**Comment by shanalikhan** [comment] 2019-07-11 16:18
@simonwiles Import / Export to Local Files is also on backlog -  #256.

Settings Sync will become one solution for all ( with time :) )

**Comment by shanalikhan** [comment] 2019-07-15 10:50
I'm closing this issue and marking it as duplicate to #413 

Settings Sync will only contain three interfaces.

1. Github Gist
2. File Import / Export
   - You can improve/ setup it with your google drive or dropbox later on by putting locations or import / export on that folder.
3. Git Repo
   - Mainly support Github and Gitlab but anyone can use their own git platform.

**Comment by shanalikhan** [comment] 2019-07-15 10:50
Duplicate of #413

**Closed by shanalikhan** 2019-07-15 10:50 UTC
Labels: feature-request  💡

**Comment by sdudnic** [comment] 2022-10-04 08:19
> 



> GitLab Snippets are not versioned.

That is not true, snippets **are** versionned via git
