### ISSUE TITLE
check for empty space before //

### ISSUE THREAD

**Issue by ctf0** [shanalikhan/code-settings-sync#875] opened 2019-05-04 20:02 UTC
🐛 **Describe the bug**  
when using `@sync host=something` the ext will comment and uncomment the next line based on the active host, however the regex responsible for that is not correct because it simply removes any `//` which affects text like `file:///C:/Users/abc/....`

🌴 **Visual Studio Code Version :** 1.33.1
🌴 **Code Settings Sync Version :** 3.2.9
🌴 **Standard or Insiders :** Standard 
🌴 **Portable or Installed :** Installed 
🌴 **OSS or Official Build :** Official 
🌴 **Operating System :** windows 7
🌴 **Occurs On:** Download 
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
1. https://github.com/be5invis/vscode-custom-css#getting-started

💪 **Expected behavior**
regex should check if `//` have a space before it to make sure its a comment not a path.

**Comment by shanalikhan** [comment] 2019-05-06 10:48
Duplicate of #865

**Comment by shanalikhan** [comment] 2019-05-06 10:48
cc : @ioprotium

**Closed by shanalikhan** 2019-05-06 10:48 UTC
