### ISSUE TITLE
Per-platform / per-hostname inline settings

### ISSUE THREAD

**Issue by jacobdufault** [shanalikhan/code-settings-sync#555] opened 2018-05-21 05:50 UTC
I use code-settings-sync across multiple operating systems. `replaceCodeSettings` may mostly work, but I think the following approach may be more flexible/have merit.

```json
// @beginsync hostname PERSONAL_DESKTOP
"someSetting": 3
// @endsync

// @beginsync os linux
"someLinuxOnlySetting": "foobar"
// @endsync
```

The `@beginsync` and `@endsync` blocks are commented out when uploaded to the gist.

```json
// @beginsync hostname PERSONAL_DESKTOP
//@ "someSetting": 3
// @endsync

// @beginsync os linux
//@ "someLinuxOnlySetting": "foobar"
// @endsync
```

When synced locally, the relevant settings are uncommented. For example, on a linux machine with hostname=foo the downloaded settings would be:

```json
// @beginsync hostname PERSONAL_DESKTOP
//@ "someSetting": 3
// @endsync

// @beginsync os linux
"someLinuxOnlySetting": "foobar"
// @endsync
```

Thoughts? If you're open to the idea I may have time to submit a PR.

**Comment by momon** [comment] 2018-05-22 16:18
I like this idea, recently started using this extension and loving it but realized I would have issues if I try to include my php executable config line when syncronizing across macOS, Windows and Linux (I use all 3 on 3 different desktops).

Having the ability to selectively exclude or re-adjust local settings on specific environments would be ideal.

+1.

**Comment by jacobdufault** [comment] 2018-05-29 20:30
Unfortunately it looks like I won't have time to implement this; I realized recently that github gists are always public, which makes this a bit less useful since you do not want to store any secrets/etc in the device-specific settings.

**Comment by robertpeteuil** [comment] 2018-09-04 21:10
@shanalikhan - I like this approach a lot.  It would really help in maintaining machine specific settings.

@jacobdufault  - github gists can be private if you have a paid github account.  My vs-code settings are synced to a "secret" gist.

**Comment by shanalikhan** [comment] 2018-09-13 09:37
Duplicate of #640

**Closed by shanalikhan** 2018-09-13 09:37 UTC
Labels: feature-request  💡
