### ISSUE TITLE
@builtin extensions are not included in the sync [Upload/Download]

### ISSUE THREAD

**Issue by n3rd4i** [shanalikhan/code-settings-sync#722] opened 2018-12-02 21:11 UTC
🐛 **Describe the bug**  
@builtin extensions are not considered by this plugin?

🌴 **Visual Studio Code Version :** 1.29.1 (user setup)
🌴 **Code Settings Sync Version :** 3.2.2 
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** OSS
🌴 **Operating System :** Microsoft Windows [Version 10.0.18290.1000] 
🌴 **Occurs On:** [Upload / Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ https://gist.github.com/8a21ee7c3475e267287cabce2abfa546 ]

📰 **To Reproduce**
1. Install Settings Sync and configure it
2. Disable some @builtin extensions
3. Upload first configuration
4. After downloading the configuration on different machine, @builtin extensions are not configured

💪 **Expected behavior**
@builtin extensions should be included in the the sync-ed configuration.

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.

📺  **Additional context**

**Comment by shanalikhan** [comment] 2018-12-05 15:45
Please update the appropriate steps in above post.
1. Which extensions are installed in code and code is reloaded after installating those extensions and they are activated.
2. What is your gist ID, and which installed extensions are missing in your gist.

**Comment by n3rd4i** [comment] 2018-12-06 06:45
As I already mention in the issue, the VSCode BuildIn plugins.

Those are default installed in every VSCode installation.

The issue as its already explaining, if one disables **some** of them, they sync-plugin does NOT take that into account. e.g:
1. Install VSCode + Sync plugin
2. disable CSS build in language support
3. upload config within gist with sync plugin
4. download this, with sync plugin, on another machine
5. the build-in language, CSS, which one disabled on the first machine, is not disabled on this second machine (after config synced with the plugin)

**Comment by shanalikhan** [comment] 2018-12-07 12:54
Duplicate of #143

**Closed** 2018-12-07 12:54 UTC
