### ISSUE TITLE
Sync broken: "Not Found","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"

### ISSUE THREAD

**Issue by krupenja** [shanalikhan/code-settings-sync#575] opened 2018-06-25 17:49 UTC
**Describe the bug**
Sync is broken, `"Not Found","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"` in Developer Console (see screenshot below). `"sync.gist"` ID is correct. [https://developer.github.com/v3/gists/#edit-a-gist](https://developer.github.com/v3/gists/#edit-a-gist) opens OK in browser.

**Visual Studio Code Version :** 1.24.1
**Code Settings Sync Version :** 2.9.2
**Operating System :** macOS 10.13.5
**Occurs On:** Upload
**Proxy Enabled:** NO
**Gist Id:** b6e46411753ca3222c0f553b02042923

**To Reproduce**
1. Open command palette.
2. Execute Sync: Update/Upload settings.

**Expected behaviour**
Sync performed correctly.

**Console Error Log**
![image](https://user-images.githubusercontent.com/26354715/41866489-f6cad4ee-78b8-11e8-8f49-c3ba32ba6264.png)

**Additional context**
None.

**Comment by shanalikhan** [comment] 2018-06-30 19:42
Duplicate of #177

**Comment by shanalikhan** [comment] 2018-06-30 19:43
see the solution there.

**Closed** 2018-07-01 07:35 UTC
